// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DMACommandTracker(	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
  input        clock,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
  input        reset,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
  input        io_alloc_valid,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  output       io_alloc_ready,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  input  [5:0] io_alloc_bits_tag_rob_id,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  input  [9:0] io_alloc_bits_bytes_to_read,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  output [1:0] io_alloc_bits_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  input        io_request_returned_valid,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  input  [9:0] io_request_returned_bits_bytes_read,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  input  [1:0] io_request_returned_bits_cmd_id,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  input        io_cmd_completed_ready,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  output       io_cmd_completed_valid,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  output [5:0] io_cmd_completed_bits_tag_rob_id,	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
  output       io_busy	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:12:14]
);

  reg             cmds_0_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg  [5:0]      cmds_0_tag_rob_id;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg  [9:0]      cmds_0_bytes_left;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg             cmds_1_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg  [5:0]      cmds_1_tag_rob_id;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg  [9:0]      cmds_1_bytes_left;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg             cmds_2_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg  [5:0]      cmds_2_tag_rob_id;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  reg  [9:0]      cmds_2_bytes_left;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  wire [1:0]      next_empty_alloc = cmds_0_valid ? (cmds_1_valid ? {~cmds_2_valid, 1'h0} : 2'h1) : 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17, :64:85, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire            _io_alloc_ready_T_1 = cmds_0_valid & cmds_1_valid & cmds_2_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :66:42]
  wire            _io_cmd_completed_valid_T = cmds_0_bytes_left == 10'h0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :72:34]
  wire            _io_cmd_completed_valid_T_2 = cmds_1_bytes_left == 10'h0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :72:34]
  wire            _io_cmd_completed_valid_T_4 = cmds_2_bytes_left == 10'h0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :72:34]
  wire [1:0]      cmd_completed_id = cmds_0_valid & _io_cmd_completed_valid_T ? 2'h0 : cmds_1_valid & _io_cmd_completed_valid_T_2 ? 2'h1 : {cmds_2_valid & _io_cmd_completed_valid_T_4, 1'h0};	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17, :72:{16,34}, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire            io_cmd_completed_valid_0 = cmds_0_valid & _io_cmd_completed_valid_T | cmds_1_valid & _io_cmd_completed_valid_T_2 | cmds_2_valid & _io_cmd_completed_valid_T_4;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :72:34, :74:{55,91}]
  wire [3:0][5:0] _GEN = {{cmds_0_tag_rob_id}, {cmds_2_tag_rob_id}, {cmds_1_tag_rob_id}, {cmds_0_tag_rob_id}};	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :76:29]
  wire [3:0]      _GEN_0 = {{cmds_0_valid}, {cmds_2_valid}, {cmds_1_valid}, {cmds_0_valid}};	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :86:56]
  wire [3:0][9:0] _GEN_1 = {{cmds_0_bytes_left}, {cmds_2_bytes_left}, {cmds_1_bytes_left}, {cmds_0_bytes_left}};	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :86:56]
  wire            _GEN_2 = io_request_returned_valid & ~reset;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
  `ifndef SYNTHESIS	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
    always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
      if (_GEN_2 & ~_GEN_0[io_request_returned_bits_cmd_id]) begin	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:86:56, :88:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
          $error("Assertion failed\n    at DMACommandTracker.scala:88 assert(cmds(cmd_id).valid)\n");	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
      end
      if (_GEN_2 & _GEN_1[io_request_returned_bits_cmd_id] < io_request_returned_bits_bytes_read) begin	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:86:56, :88:11, :89:{11,36}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:89:11]
          $error("Assertion failed\n    at DMACommandTracker.scala:89 assert(cmds(cmd_id).bytes_left >= io.request_returned.bits.bytes_read)\n");	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:89:11]
        if (`STOP_COND_)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:89:11]
          $fatal;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:89:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire            _GEN_3 = io_alloc_valid & ~_io_alloc_ready_T_1;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:27:40, :66:{21,42}]
  wire            _GEN_4 = _GEN_3 & next_empty_alloc == 2'h0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :27:40, :61:17, :78:26, :79:34, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire            _GEN_5 = _GEN_3 & next_empty_alloc == 2'h1;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :27:40, :61:17, :78:26, :79:34, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire            _GEN_6 = _GEN_3 & next_empty_alloc == 2'h2;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :27:40, :61:17, :78:26, :79:34, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [9:0]      _cmds_bytes_left_T = _GEN_1[io_request_returned_bits_cmd_id] - io_request_returned_bits_bytes_read;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:86:56]
  wire            _GEN_7 = io_cmd_completed_ready & io_cmd_completed_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:74:91, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
    if (_GEN_2)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:88:11]
      assert__assert: assert(_GEN_0[io_request_returned_bits_cmd_id]);	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:86:56, :88:11]
    cmds_0_valid <= ~(reset | _GEN_7 & cmd_completed_id == 2'h0) & (_GEN_4 | cmds_0_valid);	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :56:13, :61:17, :78:26, :79:34, :92:32, :93:46, :96:23, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (_GEN_4)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :78:26, :79:34]
      cmds_0_tag_rob_id <= io_alloc_bits_tag_rob_id;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
    if (io_request_returned_valid & io_request_returned_bits_cmd_id == 2'h0)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :78:26, :84:35, :86:29]
      cmds_0_bytes_left <= _cmds_bytes_left_T;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :86:56]
    else if (_GEN_4)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :78:26, :79:34]
      cmds_0_bytes_left <= io_alloc_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
    cmds_1_valid <= ~(reset | _GEN_7 & cmd_completed_id == 2'h1) & (_GEN_5 | cmds_1_valid);	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :56:13, :61:17, :78:26, :79:34, :92:32, :93:46, :96:23, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (_GEN_5)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :78:26, :79:34]
      cmds_1_tag_rob_id <= io_alloc_bits_tag_rob_id;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
    if (io_request_returned_valid & io_request_returned_bits_cmd_id == 2'h1)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :78:26, :84:35, :86:29]
      cmds_1_bytes_left <= _cmds_bytes_left_T;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :86:56]
    else if (_GEN_5)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :78:26, :79:34]
      cmds_1_bytes_left <= io_alloc_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
    cmds_2_valid <= ~(reset | _GEN_7 & cmd_completed_id == 2'h2) & (_GEN_6 | cmds_2_valid);	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :56:13, :61:17, :78:26, :79:34, :92:32, :93:46, :96:23, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/Mux.scala:126:16]
    if (_GEN_6)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :78:26, :79:34]
      cmds_2_tag_rob_id <= io_alloc_bits_tag_rob_id;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
    if (io_request_returned_valid & io_request_returned_bits_cmd_id == 2'h2)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :78:26, :84:35, :86:29]
      cmds_2_bytes_left <= _cmds_bytes_left_T;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :86:56]
    else if (_GEN_6)	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17, :78:26, :79:34]
      cmds_2_bytes_left <= io_alloc_bits_bytes_to_read;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:61:17]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
        cmds_0_valid = _RANDOM[1'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_0_tag_rob_id = _RANDOM[1'h0][6:1];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_0_bytes_left = _RANDOM[1'h0][16:7];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_1_valid = _RANDOM[1'h0][17];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_1_tag_rob_id = _RANDOM[1'h0][23:18];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_1_bytes_left = {_RANDOM[1'h0][31:24], _RANDOM[1'h1][1:0]};	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_2_valid = _RANDOM[1'h1][2];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_2_tag_rob_id = _RANDOM[1'h1][8:3];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
        cmds_2_bytes_left = _RANDOM[1'h1][18:9];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_alloc_ready = ~_io_alloc_ready_T_1;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :66:{21,42}]
  assign io_alloc_bits_cmd_id = next_empty_alloc;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_cmd_completed_valid = io_cmd_completed_valid_0;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :74:91]
  assign io_cmd_completed_bits_tag_rob_id = _GEN[cmd_completed_id];	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :76:29, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_busy = cmds_0_valid | cmds_1_valid | cmds_2_valid;	// @[generators/gemmini/src/main/scala/gemmini/DMACommandTracker.scala:9:7, :61:17, :69:34]
endmodule

