// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue2_VectorScalarMultiplierReq_1(	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input          clock,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  input          reset,	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
  output         io_enq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_4,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_5,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_6,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_in_7,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_scale,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [15:0]  io_enq_bits_repeats,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_last,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [255:0] io_enq_bits_tag_data,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [9:0]   io_enq_bits_tag_addr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_4,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_5,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_6,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_7,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_8,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_9,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_10,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_11,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_12,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_13,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_14,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_15,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_16,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_17,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_18,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_19,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_20,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_21,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_22,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_23,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_24,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_25,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_26,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_27,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_28,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_29,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_30,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_mask_31,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_is_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_accumulate,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_has_acc_bitwidth,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [31:0]  io_enq_bits_tag_scale,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [15:0]  io_enq_bits_tag_repeats,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [15:0]  io_enq_bits_tag_pixel_repeats,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [15:0]  io_enq_bits_tag_len,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_enq_bits_tag_last,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]   io_enq_bits_tag_bytes_read,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input  [7:0]   io_enq_bits_tag_cmd_id,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  input          io_deq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_4,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_5,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_6,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [31:0]  io_deq_bits_in_7,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [15:0]  io_deq_bits_repeats,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_last,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [9:0]   io_deq_bits_tag_addr,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_0,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_1,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_2,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_3,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_4,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_5,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_6,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_7,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_8,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_9,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_10,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_11,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_12,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_13,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_14,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_15,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_16,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_17,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_18,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_19,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_20,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_21,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_22,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_23,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_24,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_25,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_26,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_27,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_28,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_29,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_30,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_mask_31,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_is_acc,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output         io_deq_bits_tag_accumulate,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [7:0]   io_deq_bits_tag_bytes_read,	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
  output [7:0]   io_deq_bits_tag_cmd_id	// @[src/main/scala/chisel3/util/Decoupled.scala:255:14]
);

  wire [332:0] _ram_ext_R0_data;	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  reg          wrap;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg          wrap_1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg          maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27]
  wire         ptr_match = wrap == wrap_1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:260:33]
  wire         empty = ptr_match & ~maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :261:{25,28}]
  wire         full = ptr_match & maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:259:27, :260:33, :262:24]
  wire         do_enq = ~full & io_enq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :262:24, :286:19]
  wire         do_deq = io_deq_ready & ~empty;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :261:25, :285:19]
  always @(posedge clock) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    if (reset) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      wrap <= 1'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7]
      wrap_1 <= 1'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7]
      maybe_full <= 1'h0;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27]
    end
    else begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        wrap <= wrap - 1'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (do_deq)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        wrap_1 <= wrap_1 - 1'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (~(do_enq == do_deq))	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27, :276:{15,27}, :277:16]
        maybe_full <= do_enq;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, :259:27]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    initial begin	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
        wrap = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7]
        wrap_1 = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7]
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][2];	// @[src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:243:7, :259:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_2x333 ram_ext (	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
    .R0_addr (wrap_1),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (wrap),	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    .W0_en   (do_enq),	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_tag_cmd_id, io_enq_bits_tag_bytes_read, io_enq_bits_tag_accumulate, io_enq_bits_tag_is_acc, io_enq_bits_tag_mask_31, io_enq_bits_tag_mask_30, io_enq_bits_tag_mask_29, io_enq_bits_tag_mask_28, io_enq_bits_tag_mask_27, io_enq_bits_tag_mask_26, io_enq_bits_tag_mask_25, io_enq_bits_tag_mask_24, io_enq_bits_tag_mask_23, io_enq_bits_tag_mask_22, io_enq_bits_tag_mask_21, io_enq_bits_tag_mask_20, io_enq_bits_tag_mask_19, io_enq_bits_tag_mask_18, io_enq_bits_tag_mask_17, io_enq_bits_tag_mask_16, io_enq_bits_tag_mask_15, io_enq_bits_tag_mask_14, io_enq_bits_tag_mask_13, io_enq_bits_tag_mask_12, io_enq_bits_tag_mask_11, io_enq_bits_tag_mask_10, io_enq_bits_tag_mask_9, io_enq_bits_tag_mask_8, io_enq_bits_tag_mask_7, io_enq_bits_tag_mask_6, io_enq_bits_tag_mask_5, io_enq_bits_tag_mask_4, io_enq_bits_tag_mask_3, io_enq_bits_tag_mask_2, io_enq_bits_tag_mask_1, io_enq_bits_tag_mask_0, io_enq_bits_tag_addr, io_enq_bits_last, io_enq_bits_repeats, io_enq_bits_in_7, io_enq_bits_in_6, io_enq_bits_in_5, io_enq_bits_in_4, io_enq_bits_in_3, io_enq_bits_in_2, io_enq_bits_in_1, io_enq_bits_in_0})	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:256:91]
  assign io_enq_ready = ~full;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :262:24, :286:19]
  assign io_deq_valid = ~empty;	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :261:25, :285:19]
  assign io_deq_bits_in_0 = _ram_ext_R0_data[31:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_1 = _ram_ext_R0_data[63:32];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_2 = _ram_ext_R0_data[95:64];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_3 = _ram_ext_R0_data[127:96];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_4 = _ram_ext_R0_data[159:128];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_5 = _ram_ext_R0_data[191:160];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_6 = _ram_ext_R0_data[223:192];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_in_7 = _ram_ext_R0_data[255:224];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_repeats = _ram_ext_R0_data[271:256];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_last = _ram_ext_R0_data[272];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_addr = _ram_ext_R0_data[282:273];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_0 = _ram_ext_R0_data[283];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_1 = _ram_ext_R0_data[284];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_2 = _ram_ext_R0_data[285];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_3 = _ram_ext_R0_data[286];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_4 = _ram_ext_R0_data[287];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_5 = _ram_ext_R0_data[288];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_6 = _ram_ext_R0_data[289];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_7 = _ram_ext_R0_data[290];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_8 = _ram_ext_R0_data[291];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_9 = _ram_ext_R0_data[292];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_10 = _ram_ext_R0_data[293];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_11 = _ram_ext_R0_data[294];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_12 = _ram_ext_R0_data[295];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_13 = _ram_ext_R0_data[296];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_14 = _ram_ext_R0_data[297];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_15 = _ram_ext_R0_data[298];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_16 = _ram_ext_R0_data[299];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_17 = _ram_ext_R0_data[300];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_18 = _ram_ext_R0_data[301];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_19 = _ram_ext_R0_data[302];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_20 = _ram_ext_R0_data[303];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_21 = _ram_ext_R0_data[304];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_22 = _ram_ext_R0_data[305];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_23 = _ram_ext_R0_data[306];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_24 = _ram_ext_R0_data[307];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_25 = _ram_ext_R0_data[308];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_26 = _ram_ext_R0_data[309];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_27 = _ram_ext_R0_data[310];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_28 = _ram_ext_R0_data[311];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_29 = _ram_ext_R0_data[312];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_30 = _ram_ext_R0_data[313];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_mask_31 = _ram_ext_R0_data[314];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_is_acc = _ram_ext_R0_data[315];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_accumulate = _ram_ext_R0_data[316];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_bytes_read = _ram_ext_R0_data[324:317];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
  assign io_deq_bits_tag_cmd_id = _ram_ext_R0_data[332:325];	// @[src/main/scala/chisel3/util/Decoupled.scala:243:7, :256:91]
endmodule

