// Generated by CIRCT af5369d
module tinytpu_dma_load(	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  input         clk,
                rst,
                start,
  input  [31:0] dram_addr_in,
                bram_addr_in,
                length_in,
                dmem_rd0_data,
  output        done,
  output [31:0] dmem_rd0_addr,
                bram_wr0_addr,
                bram_wr0_data,
  output        bram_wr0_we
);

  wire        _GEN;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire [31:0] _GEN_2;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_3;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_4;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg  [31:0] r0_sv1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg  [31:0] r0_sv0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  initial begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // initial
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r0_sv0 <= 32'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r0_sv0 <= start ? bram_addr_in : r0_sv0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r0_sv1 <= 32'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r0_sv1 <= start ? dram_addr_in : r0_sv1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  reg         r0_done;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r0_done <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r0_done <= _GEN_4;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  wire        _GEN_5 = ~start;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_6 = _GEN_5 & r0_done;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign _GEN_4 = start | _GEN_6;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         _GEN_7;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_7 <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_7 <= _GEN_6;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  reg         _GEN_8;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_8 <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_8 <= _GEN_3;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  assign _GEN_3 = _GEN_5 & (_GEN_6 & ~_GEN_7 | _GEN_8);	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_9 = _GEN_3 & ~_GEN_8;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_10 = _GEN_9 & $signed(length_in) > 32'sh0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         r1_run;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r1_run <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r1_run <= _GEN_1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  wire        _GEN_11 = r1_run | _GEN_10;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg  [31:0] i;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      i <= 32'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      i <= _GEN_2;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  wire [31:0] _GEN_12 = _GEN_10 ? 32'h0 : i;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire [31:0] _GEN_13 = _GEN_12 + 32'h1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign _GEN_2 = _GEN_11 ? _GEN_13 : r1_run ? i : 32'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  wire        _GEN_14 = _GEN_11 & $signed(_GEN_13) >= $signed(length_in);	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign _GEN_1 = _GEN_11 & ~_GEN_14;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         r1_v1 = 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always @(posedge clk)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    r1_v1 <= _GEN_11;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg  [12:0] _GEN_15 = 13'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always @(posedge clk)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    _GEN_15 <= _GEN_12[12:0];	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         r1_v1_0 = 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always @(posedge clk)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    r1_v1_0 <= _GEN_9 & $signed(length_in) < 32'sh1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         r1_v1_1 = 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always @(posedge clk)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    r1_v1_1 <= _GEN_14;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         r1_done;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r1_done <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      r1_done <= _GEN_0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  wire        _GEN_16 = ~_GEN_9 & r1_done;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign _GEN_0 = r1_v1_0 | r1_v1_1 | _GEN_16;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  reg         _GEN_17;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_17 <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_17 <= _GEN_16;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  reg         _GEN_18;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  always_ff @(posedge clk) begin	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    if (rst)	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_18 <= 1'h0;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
    else	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
      _GEN_18 <= _GEN;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  end // always_ff @(posedge)
  wire        _GEN_19 = _GEN_16 & ~_GEN_17 | _GEN_18;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign _GEN = _GEN_5 & _GEN_19;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign done = _GEN_3 & _GEN_19;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign dmem_rd0_addr = {16'h0, _GEN_12[15:0] + r0_sv1[15:0]};	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign bram_wr0_addr = {19'h0, _GEN_15 + r0_sv0[12:0]};	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign bram_wr0_data = dmem_rd0_data;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
  assign bram_wr0_we = r1_v1;	// /home/sk3463/allo/examples/accelerator/tinytpu/microarch.py:60
endmodule

