// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_6_7_Pipeline_VITIS_LOOP_10792_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v6259_dout,
        v6259_num_data_valid,
        v6259_fifo_cap,
        v6259_empty_n,
        v6259_read,
        v6122_dout,
        v6122_num_data_valid,
        v6122_fifo_cap,
        v6122_empty_n,
        v6122_read,
        v6179_dout,
        v6179_num_data_valid,
        v6179_fifo_cap,
        v6179_empty_n,
        v6179_read,
        v6187_din,
        v6187_num_data_valid,
        v6187_fifo_cap,
        v6187_full_n,
        v6187_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v6259_dout;
input  [2:0] v6259_num_data_valid;
input  [2:0] v6259_fifo_cap;
input   v6259_empty_n;
output   v6259_read;
input  [7:0] v6122_dout;
input  [4:0] v6122_num_data_valid;
input  [4:0] v6122_fifo_cap;
input   v6122_empty_n;
output   v6122_read;
input  [31:0] v6179_dout;
input  [4:0] v6179_num_data_valid;
input  [4:0] v6179_fifo_cap;
input   v6179_empty_n;
output   v6179_read;
output  [31:0] v6187_din;
input  [4:0] v6187_num_data_valid;
input  [4:0] v6187_fifo_cap;
input   v6187_full_n;
output   v6187_write;
input  [15:0] empty;

reg ap_idle;
reg v6259_read;
reg v6122_read;
reg v6179_read;
reg v6187_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] v4926_reg_255;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10792_fu_126_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v6122_blk_n;
wire    ap_block_pp0_stage0;
reg    v6179_blk_n;
reg    v6187_blk_n;
reg    v6259_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v4926_fu_149_p2;
reg   [31:0] v4934_reg_259;
reg  signed [31:0] v4934_reg_259_pp0_iter4_reg;
reg   [31:0] v4920_fu_56;
wire   [31:0] v4923_fu_143_p2;
wire    ap_loop_init;
reg   [15:0] v4919_fu_60;
wire   [15:0] v4919_2_fu_131_p2;
reg  signed [7:0] weight56_fu_64;
wire   [7:0] v4929_fu_170_p1;
reg   [31:0] v4925_fu_68;
wire   [31:0] zext_ln10814_fu_184_p1;
reg   [31:0] ap_sig_allocacmp_v4925_load;
wire  signed [31:0] grp_fu_209_p3;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] v4931_fu_174_p4;
reg    grp_fu_209_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_279;
reg    ap_condition_283;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 v4920_fu_56 = 32'd0;
#0 v4919_fu_60 = 16'd0;
#0 weight56_fu_64 = 8'd0;
#0 v4925_fu_68 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_mac_muladd_8s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_4_1_U1187(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v6122_dout),
    .din1(weight56_fu_64),
    .din2(v4934_reg_259_pp0_iter4_reg),
    .ce(grp_fu_209_ce),
    .dout(grp_fu_209_p3)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v4919_fu_60 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln10792_fu_126_p2 == 1'd0))) begin
            v4919_fu_60 <= v4919_2_fu_131_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v4920_fu_56 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_283)) begin
            v4920_fu_56 <= v4923_fu_143_p2;
        end else if ((1'b1 == ap_condition_279)) begin
            v4920_fu_56 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
                        v4925_fu_68[0] <= 1'b0;
            v4925_fu_68[1] <= 1'b0;
            v4925_fu_68[2] <= 1'b0;
            v4925_fu_68[3] <= 1'b0;
            v4925_fu_68[4] <= 1'b0;
            v4925_fu_68[5] <= 1'b0;
            v4925_fu_68[6] <= 1'b0;
            v4925_fu_68[7] <= 1'b0;
            v4925_fu_68[8] <= 1'b0;
            v4925_fu_68[9] <= 1'b0;
            v4925_fu_68[10] <= 1'b0;
            v4925_fu_68[11] <= 1'b0;
        end else if (((v4926_reg_255 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v4925_fu_68[11 : 0] <= zext_ln10814_fu_184_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            weight56_fu_64 <= 8'd0;
        end else if (((v4926_reg_255 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            weight56_fu_64 <= v4929_fu_170_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v4926_reg_255 <= v4926_fu_149_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        v4934_reg_259 <= v6179_dout;
        v4934_reg_259_pp0_iter4_reg <= v4934_reg_259;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln10792_fu_126_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v4926_reg_255 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_v4925_load = zext_ln10814_fu_184_p1;
    end else begin
        ap_sig_allocacmp_v4925_load = v4925_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_209_ce = 1'b1;
    end else begin
        grp_fu_209_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v6122_blk_n = v6122_empty_n;
    end else begin
        v6122_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v6122_read = 1'b1;
    end else begin
        v6122_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v6179_blk_n = v6179_empty_n;
    end else begin
        v6179_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        v6179_read = 1'b1;
    end else begin
        v6179_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        v6187_blk_n = v6187_full_n;
    end else begin
        v6187_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        v6187_write = 1'b1;
    end else begin
        v6187_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v4926_reg_255 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6259_blk_n = v6259_empty_n;
    end else begin
        v6259_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (v4926_reg_255 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6259_read = 1'b1;
    end else begin
        v6259_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v4926_reg_255 == 1'd0) & (v6259_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((v6179_empty_n == 1'b0) | (v6122_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = (v6187_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_279 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v4926_fu_149_p2 == 1'd0) & (icmp_ln10792_fu_126_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_283 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v4926_fu_149_p2 == 1'd1) & (icmp_ln10792_fu_126_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln10792_fu_126_p2 = ((v4919_fu_60 == empty) ? 1'b1 : 1'b0);

assign v4919_2_fu_131_p2 = (v4919_fu_60 + 16'd1);

assign v4923_fu_143_p2 = (v4920_fu_56 + 32'd1);

assign v4926_fu_149_p2 = (($signed(v4923_fu_143_p2) < $signed(ap_sig_allocacmp_v4925_load)) ? 1'b1 : 1'b0);

assign v4929_fu_170_p1 = v6259_dout[7:0];

assign v4931_fu_174_p4 = {{v6259_dout[19:8]}};

assign v6187_din = grp_fu_209_p3;

assign zext_ln10814_fu_184_p1 = v4931_fu_174_p4;

always @ (posedge ap_clk) begin
    v4925_fu_68[31:12] <= 20'b00000000000000000000;
end

endmodule //tinytpu_isa_pe_6_7_Pipeline_VITIS_LOOP_10792_1
