// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_0_2_Pipeline_VITIS_LOOP_6216_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v6206_dout,
        v6206_num_data_valid,
        v6206_fifo_cap,
        v6206_empty_n,
        v6206_read,
        v6069_dout,
        v6069_num_data_valid,
        v6069_fifo_cap,
        v6069_empty_n,
        v6069_read,
        v6134_din,
        v6134_num_data_valid,
        v6134_fifo_cap,
        v6134_full_n,
        v6134_write,
        v6070_din,
        v6070_num_data_valid,
        v6070_fifo_cap,
        v6070_full_n,
        v6070_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v6206_dout;
input  [2:0] v6206_num_data_valid;
input  [2:0] v6206_fifo_cap;
input   v6206_empty_n;
output   v6206_read;
input  [7:0] v6069_dout;
input  [4:0] v6069_num_data_valid;
input  [4:0] v6069_fifo_cap;
input   v6069_empty_n;
output   v6069_read;
output  [31:0] v6134_din;
input  [4:0] v6134_num_data_valid;
input  [4:0] v6134_fifo_cap;
input   v6134_full_n;
output   v6134_write;
output  [7:0] v6070_din;
input  [4:0] v6070_num_data_valid;
input  [4:0] v6070_fifo_cap;
input   v6070_full_n;
output   v6070_write;
input  [15:0] empty;

reg ap_idle;
reg v6206_read;
reg v6069_read;
reg v6134_write;
reg v6070_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] v2647_reg_259;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln6216_fu_129_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v6069_blk_n;
wire    ap_block_pp0_stage0;
reg    v6134_blk_n;
reg    v6070_blk_n;
reg    v6206_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v2647_fu_152_p2;
reg  signed [7:0] v2654_reg_263;
reg  signed [7:0] v2654_reg_263_pp0_iter3_reg;
wire   [15:0] v2664_fu_211_p2;
reg   [15:0] v2664_reg_269;
reg   [31:0] v2641_fu_58;
wire   [31:0] v2644_fu_146_p2;
wire    ap_loop_init;
reg   [15:0] v2640_fu_62;
wire   [15:0] v2640_2_fu_134_p2;
reg  signed [7:0] weight2_fu_66;
wire   [7:0] v2650_fu_173_p1;
reg   [31:0] v2646_fu_70;
wire   [31:0] zext_ln6238_fu_187_p1;
reg   [31:0] ap_sig_allocacmp_v2646_load;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] v2652_fu_177_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_257;
reg    ap_condition_260;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 v2641_fu_58 = 32'd0;
#0 v2640_fu_62 = 16'd0;
#0 weight2_fu_66 = 8'd0;
#0 v2646_fu_70 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U562(
    .din0(v2654_reg_263),
    .din1(weight2_fu_66),
    .dout(v2664_fu_211_p2)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v2640_fu_62 <= 16'd0;
        end else if (((icmp_ln6216_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            v2640_fu_62 <= v2640_2_fu_134_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v2641_fu_58 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_260)) begin
            v2641_fu_58 <= v2644_fu_146_p2;
        end else if ((1'b1 == ap_condition_257)) begin
            v2641_fu_58 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
                        v2646_fu_70[0] <= 1'b0;
            v2646_fu_70[1] <= 1'b0;
            v2646_fu_70[2] <= 1'b0;
            v2646_fu_70[3] <= 1'b0;
            v2646_fu_70[4] <= 1'b0;
            v2646_fu_70[5] <= 1'b0;
            v2646_fu_70[6] <= 1'b0;
            v2646_fu_70[7] <= 1'b0;
            v2646_fu_70[8] <= 1'b0;
            v2646_fu_70[9] <= 1'b0;
            v2646_fu_70[10] <= 1'b0;
            v2646_fu_70[11] <= 1'b0;
        end else if (((v2647_reg_259 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v2646_fu_70[11 : 0] <= zext_ln6238_fu_187_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            weight2_fu_66 <= 8'd0;
        end else if (((v2647_reg_259 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            weight2_fu_66 <= v2650_fu_173_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v2647_reg_259 <= v2647_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        v2654_reg_263 <= v6069_dout;
        v2654_reg_263_pp0_iter3_reg <= v2654_reg_263;
        v2664_reg_269 <= v2664_fu_211_p2;
    end
end

always @ (*) begin
    if (((icmp_ln6216_fu_129_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v2647_reg_259 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_v2646_load = zext_ln6238_fu_187_p1;
    end else begin
        ap_sig_allocacmp_v2646_load = v2646_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6069_blk_n = v6069_empty_n;
    end else begin
        v6069_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6069_read = 1'b1;
    end else begin
        v6069_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6070_blk_n = v6070_full_n;
    end else begin
        v6070_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6070_write = 1'b1;
    end else begin
        v6070_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6134_blk_n = v6134_full_n;
    end else begin
        v6134_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6134_write = 1'b1;
    end else begin
        v6134_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v2647_reg_259 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6206_blk_n = v6206_empty_n;
    end else begin
        v6206_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (v2647_reg_259 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6206_read = 1'b1;
    end else begin
        v6206_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v6069_empty_n == 1'b0) | ((v2647_reg_259 == 1'd0) & (v6206_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((v6070_full_n == 1'b0) | (v6134_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_257 = ((icmp_ln6216_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (v2647_fu_152_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_260 = ((icmp_ln6216_fu_129_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (v2647_fu_152_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln6216_fu_129_p2 = ((v2640_fu_62 == empty) ? 1'b1 : 1'b0);

assign v2640_2_fu_134_p2 = (v2640_fu_62 + 16'd1);

assign v2644_fu_146_p2 = (v2641_fu_58 + 32'd1);

assign v2647_fu_152_p2 = (($signed(v2644_fu_146_p2) < $signed(ap_sig_allocacmp_v2646_load)) ? 1'b1 : 1'b0);

assign v2650_fu_173_p1 = v6206_dout[7:0];

assign v2652_fu_177_p4 = {{v6206_dout[19:8]}};

assign v6070_din = v2654_reg_263_pp0_iter3_reg;

assign v6134_din = $signed(v2664_reg_269);

assign zext_ln6238_fu_187_p1 = v2652_fu_177_p4;

always @ (posedge ap_clk) begin
    v2646_fu_70[31:12] <= 20'b00000000000000000000;
end

endmodule //tinytpu_isa_pe_0_2_Pipeline_VITIS_LOOP_6216_1
