#=========================================================================
# ORFS Common Helpers
#=========================================================================

name: orfs-common

outputs:
  - orfs-checkpoint.py

commands:
  - cp orfs-checkpoint.py outputs/orfs-checkpoint.py

parameters: {}