# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Catapult RTL of a U3 unit form vs the Phase 0 oracle, in Verilator, per row.

    $ALLO_PYTHON u3c_cmp.py <unit> <prj> [--inst I] [--top K] [--n N]

Generalises ``latency_report_2026-10-02/cmp_rtl.py`` to a kernel with any
number of Connections In/Out ports of any width (the tree has four outputs,
the transpose 1,024-bit words). Every input port offers row ``t`` until it is
accepted; every output is always ready; each row's accept edge (the last input
port's) and each output row's edge are stamped, so the per-output latency
``L`` (edges, rtl.py's count) and the rate are measured.

``valid`` units (``sfu``): values against ``rtl.run(u.RTL, stimulus)``;
``L`` is the unit's latency and is held to the declared one.
``trace`` units: the command trace is ``check._trace_all``'s (every directed
and random trace of the instance, plus the seeds); the RTL oracle runs the
same trace (``rtl.run_trace``), ``u.REF`` masks undefined slots, and the
Catapult RTL's row ``t`` is held to the oracle's row ``t`` on every defined
slot (as ``check_trace`` does for csim). The forms carry the RTL's register
edges as rows, so row equality plus ``L == 1`` on every output means
cycle-equal to MiniTPU (the Pop->Push edge is the row's own edge); ``L`` is
also held to ``latency.json`` (D-10).
"""
import argparse, hashlib, importlib, os, re, subprocess, sys, time
import numpy as np

sys.path.insert(0, os.getcwd())
from examples.minitpu.harness import check, latency, rtl  # noqa: E402

# port order of each unit's forms (region arg order = emitted port order)
PORTS = {
    "sfu": (["op_i", "operand_i"], ["result_o"]),
    "xlu_reduction_tree": (["rst_ni", "valid_i", "op_i", "data_i"],
                           ["valid_o", "result_o", "lane_valid_o", "lane_result_o"]),
    "xlu_transpose": (["rst_ni", "write_valid_i", "write_index_i", "write_data_i", "read_valid_i", "read_index_i"],
                      ["read_valid_o", "read_data_o"]),
}

ap = argparse.ArgumentParser()
ap.add_argument("unit"); ap.add_argument("prj")
ap.add_argument("--inst", default=None)
ap.add_argument("--top", default=None)
ap.add_argument("--n", type=int, default=0)
a = ap.parse_args()
u = importlib.import_module(f"examples.minitpu.units.{a.unit}")
inst = a.inst or getattr(u, "DEFAULT", None)
name = os.path.basename(a.prj.rstrip("/")).replace(".prj", "")
k = open(os.path.join(a.prj, "kernel.cpp")).read()
top = a.top or re.search(r"SC_MODULE\((\w+_0)\)", k).group(1)
blk = k[k.index(f"SC_MODULE({top})"):]
blk = blk[: blk.index("\n};")]


def _w(t):
    m = re.match(r"ac_int<(\d+),", t)
    return int(m.group(1)) if m else {"bool": 1}[t]


ins = [(p, _w(t)) for t, p in re.findall(r"Connections::In< (.+?) > (\w+);", blk)]
outs = [(p, _w(t)) for t, p in re.findall(r"Connections::Out< (.+?) > (\w+);", blk)]
pin_names, pout_names = PORTS[a.unit]
assert len(ins) == len(pin_names) and len(outs) == len(pout_names), (ins, outs)
src = os.path.abspath(os.path.join(a.prj, "build", "Catapult", f"{top}.v1", "concat_sim_rtl.v"))
nw = rtl.nwords


def driver():
    win = sum(nw(w) for _, w in ins)
    drive, fire, zero = [], [], []
    for i, (p, w) in enumerate(ins):
        off = sum(nw(w2) for _, w2 in ins[:i])
        drive.append(f"    dut.{p}_vld = k[{i}] < n;")
        drive.append(f"    if (k[{i}] < n) setp(dut.{p}_dat, &in[k[{i}] * {win} + {off}]); else setp(dut.{p}_dat, zeros);")
        fire.append(f"    fire[{i}] = dut.{p}_vld && dut.{p}_rdy;")
    ni, no = len(ins), len(outs)
    rdy = "\n".join(f"    dut.{p}_rdy = 1;" for p, _ in outs)
    ocap = []
    for o, (p, w) in enumerate(outs):
        ocap.append(f"""    if (dut.{p}_vld && dut.{p}_rdy) {{
      if (j[{o}] < n) {{ getp(dut.{p}_dat, &out{o}[j[{o}] * {nw(w) + 1}]); out{o}[j[{o}] * {nw(w) + 1} + {nw(w)}] = cyc; }}
      ++j[{o}]; last = cyc;
    }}""")
    decl = "\n".join(f"  std::vector<uint64_t> out{o}(n * {nw(w) + 1}, 0);" for o, (p, w) in enumerate(outs))
    wr = "\n".join(f"  std::fwrite(out{o}.data(), 8, out{o}.size(), fo);" for o in range(no))
    done = " && ".join(f"j[{o}] >= n" for o in range(no))
    nl = "\n"
    return f"""// generated by u3c_cmp.py: multi-port Connections driver
#include "V{top}.h"
#include "verilated.h"
#include <cstdint>
#include <cstdio>
#include <vector>
{rtl._TRACE_HELPERS}
int main(int argc, char** argv) {{
  Verilated::commandArgs(argc, argv);
  FILE* fi = std::fopen(argv[1], "rb");
  std::fseek(fi, 0, SEEK_END);
  const uint64_t n = std::ftell(fi) / 8 / {win};
  std::fseek(fi, 0, SEEK_SET);
  std::vector<uint64_t> in(n * {win}), acc(n, 0);
  static const uint64_t zeros[64] = {{0}};
{decl}
  if (std::fread(in.data(), 8, n * {win}, fi) != n * {win}) return 2;
  std::fclose(fi);
  V{top} dut;
  uint64_t k[{ni}] = {{0}}, j[{no}] = {{0}};
  bool fire[{ni}];
  for (int i = 0; i < {ni}; ++i) k[i] = n;
  dut.rst = 0;
{nl.join(drive)}
  for (int r = 0; r < 4; ++r) {{ dut.clk = 0; dut.eval(); dut.clk = 1; dut.eval(); }}
  dut.rst = 1;
  for (int i = 0; i < {ni}; ++i) k[i] = 0;
  uint64_t cyc = 0, last = 0;
  while (!({done})) {{
    dut.clk = 0;
{nl.join(drive)}
{rdy}
    dut.eval();
{nl.join(fire)}
{nl.join(ocap)}
    dut.clk = 1;
    dut.eval();
    for (int i = 0; i < {ni}; ++i)
      if (fire[i]) {{ if (k[i] < n && acc[k[i]] < cyc) acc[k[i]] = cyc; ++k[i]; last = cyc; }}
    ++cyc;
    if (cyc - last > 10000) {{
      std::fprintf(stderr, "stalled at cycle %llu: outputs", (unsigned long long)cyc);
      for (int o = 0; o < {no}; ++o) std::fprintf(stderr, " %llu", (unsigned long long)j[o]);
      std::fprintf(stderr, " of %llu\\n", (unsigned long long)n);
      return 4;
    }}
  }}
  std::printf("STREAM cycles=%llu n=%llu\\n", (unsigned long long)cyc, (unsigned long long)n);
  FILE* fo = std::fopen(argv[2], "wb");
  std::fwrite(acc.data(), 8, n, fo);
{wr}
  std::fclose(fo);
  return 0;
}}
"""


def build():
    cache = os.environ.get("MINITPU_HARNESS_CACHE", "/work/shared/users/phd/sk3463/scratch/u3c/hcache")
    code = driver()
    h = hashlib.sha256(code.encode() + open(src, "rb").read()).hexdigest()[:16]
    d = os.path.join(cache, f"cat-{top}-{h}")
    exe = os.path.join(d, f"V{top}")
    if os.path.exists(exe):
        return exe
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, "driver.cpp"), "w").write(code)
    cmd = ["verilator", "--cc", "--exe", "--build", "-Wno-fatal", "-O3", "--top-module", top, "--Mdir", d,
           "-j", "8", src, os.path.join(d, "driver.cpp"), "-CFLAGS", "-std=c++17 -O2"]
    r = subprocess.run(cmd, env=dict(os.environ, CXX=rtl._cxx()), capture_output=True, text=True)
    if r.returncode != 0 or not os.path.exists(exe):
        raise RuntimeError(f"verilator build failed:\n{r.stdout[-3000:]}\n{r.stderr[-3000:]}")
    return exe


def run(rows):
    """rows: {port: uint64[n, nw]} per input port -> (acc[n], {out: uint64[n, nw]}, {out: cyc[n]}, cycles)."""
    cols = [np.asarray(rows[p], dtype=np.uint64).reshape(-1, nw(w)) for p, w in ins]
    n = len(cols[0])
    stim = np.ascontiguousarray(np.concatenate(cols, axis=1), dtype=np.uint64)
    exe = build()
    d = os.path.dirname(exe)
    fi, fo = os.path.join(d, f"in.{os.getpid()}"), os.path.join(d, f"out.{os.getpid()}")
    stim.tofile(fi)
    try:
        r = subprocess.run([exe, fi, fo], capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"driver exited {r.returncode}: {r.stderr[-1500:]}")
        raw = np.fromfile(fo, dtype=np.uint64)
    finally:
        for p in (fi, fo):
            if os.path.exists(p):
                os.remove(p)
    acc, off = raw[:n], n
    got, cyc = {}, {}
    for p, w in outs:
        blk_ = raw[off: off + n * (nw(w) + 1)].reshape(n, nw(w) + 1)
        off += n * (nw(w) + 1)
        col = blk_[:, : nw(w)].copy()
        if w % 64:
            col[:, -1] &= np.uint64((1 << (w % 64)) - 1)
        got[p] = col
        cyc[p] = blk_[:, nw(w)].astype(np.int64)
    cycles = int(re.search(r"cycles=(\d+)", r.stdout).group(1))
    return acc.astype(np.int64), got, cyc, cycles


def hist(x):
    v, c = np.unique(x, return_counts=True)
    return dict(zip(v.tolist(), c.tolist()))


man = latency.load(a.prj) if os.path.exists(os.path.join(a.prj, "latency.json")) else None
t0 = time.time()
if u.RTL.shape == "valid":
    stim = u.stimulus()
    if a.n:
        stim = stim[: a.n]
    n = len(stim)
    want, wl = rtl.run(u.RTL, stim.astype(np.uint64))
    want = want[:, 0]
    rows = {p: rtl.pack(stim[:, i].astype(np.int64), w) for i, (p, w) in enumerate(ins)}
    acc, got, cyc, cycles = run(rows)
    p = outs[0][0]
    g = got[p][:, 0]
    kd = int((g != want).sum())
    lat = hist(cyc[p] - acc)
    tag = "UNIT-MATCH" if kd == 0 else "UNIT-DIFF "
    print(f"{tag} {a.unit} {name} catapult-rtl {n - kd}/{n} vs MiniTPU RTL; latency {lat} (declared {u.RTL.latency}); "
          f"{cycles / n:.4f} cyc/vector ({time.time() - t0:.1f}s)", flush=True)
    if kd:
        for nm, idx in check.classify(stim, g, want, getattr(u, "EXPLAIN", [])).items():
            ex = ", ".join("/".join(f"{int(x):x}" for x in stim[i]) + f": catapult {int(g[i]):x} minitpu {int(want[i]):x}" for i in idx[:2])
            print(f"    {len(idx):8d}  {nm}  e.g. {ex}")
    if man:
        print("    " + latency.verdict(man, top, lat, cycles / n, u.RTL.latency))
else:
    unit = u.INSTANCES[inst]
    cmd, spans = check._trace_all(u, inst, a.n)
    n = len(next(iter(cmd.values())))
    packed = {p: rtl.pack(cmd[p], wd) for p, wd in unit.inputs}
    rtl_out = rtl.run_trace(unit, packed, seed=1)
    want, reason, _ = u.REF(inst, packed)
    ndef = sum(int((reason[p] == "").sum()) for p in want)
    bad_ref = sum(int(((reason[p] == "") & (rtl_out[p] != want[p]).any(axis=1)).sum()) for p in want)
    print(f"RTL {unit.top}:{inst}: {n} cycles in {len(spans)} traces, {ndef} defined slots, "
          f"RTL vs reference on defined: {ndef - bad_ref}/{ndef}", flush=True)
    rows = {}
    for (p, w), oracle_p in zip(ins, pin_names):
        rows[p] = rtl.pack(cmd[oracle_p], w)
    acc, got, cyc, cycles = run(rows)
    kbad = tot = masked = masked_eq = 0
    per_label, first, census = {}, [], {}
    lats = {}
    for (p, w), op in zip(outs, pout_names):
        g, r_ = got[p], rtl_out[op]
        lats[op] = hist(cyc[p] - acc)
        for i in range(n):
            why = reason[op][i]
            eq = bool((g[i] == r_[i]).all())
            if why:
                masked += 1
                census[why] = census.get(why, 0) + 1
                masked_eq += int(eq)
                continue
            tot += 1
            if not eq:
                kbad += 1
                lab = next(lb for lb, s0, s1 in spans if s0 <= i < s1)
                per_label[lab] = per_label.get(lab, 0) + 1
                if len(first) < 4:
                    first.append(f"{lab} cycle {i} {op}: catapult {rtl.unpack(g[i:i+1])[0]:x} rtl {rtl.unpack(r_[i:i+1])[0]:x}")
    tag = "UNIT-MATCH" if kbad == 0 else "UNIT-DIFF "
    cen = ", ".join(f"{x}={y}" for x, y in sorted(census.items()))
    eq1 = all(set(h) == {1} for h in lats.values())
    print(f"{tag} {a.unit}:{inst} {name} catapult-rtl {tot - kbad}/{tot} defined ({masked} masked: {cen}; "
          f"catapult==rtl on {masked_eq}) cycle=per-row; L per output {lats}; {cycles / n:.4f} cyc/row; "
          f"CYCLE-EQUAL {'yes' if eq1 and kbad == 0 else 'no'} ({time.time() - t0:.1f}s)", flush=True)
    if kbad:
        print("    differing defined slots by trace: " + ", ".join(f"{lb}={c}" for lb, c in per_label.items()))
        for f in first:
            print(f"    e.g. {f}")
    if man:
        allh = {}
        for h in lats.values():
            for L, c in h.items():
                allh[L] = allh.get(L, 0) + c
        print("    " + latency.verdict(man, top, allh, cycles / n, 1))
