# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate ``../forms/dma_bits_packed.py``: ``dma.bits`` (plan D1, one kernel)
with its four lane arrays as one wide port per row (U3 track C C1).

A text transform of ``examples/minitpu/units/dma.py``'s ``bits`` (the body is
500 lines; copying it by hand would fork it): the signature types, every
``cin[t, J]`` read as a slice of the row word read once at the top, the two
``din``/``dout`` lane loops written out for ``L = 8``, every ``cout[t, J]``
write into a row word stored once at the end. Each rewrite is asserted to
apply the expected number of times. usage: gen_dma_bits_form.py <worktree>
"""
import re
import sys

root = sys.argv[1]
src = open(f"{root}/examples/minitpu/units/dma.py").read().split("\n")
i0 = next(i for i, l in enumerate(src) if l.startswith("def bits(n, w=256"))
i1 = next(i for i, l in enumerate(src) if i > i0 and l.startswith("    return top"))
body = "\n".join(src[i0:i1 + 1])
L = 8


def sub(pat, rep, s, count, flags=0):
    out, k = re.subn(pat, rep, s, flags=flags)
    assert k == count, (pat, k, count)
    return out


body = sub(r"^def bits\(n, w=256, inst=\"core\", payload=\"unreset\"\):", 'def make(n, w=256, inst="core", payload="reset"):', body, 1, re.M)
body = sub(r"(    NO = len\(COUT_NAMES\)\n)", r"\1    CIW = 32 * NC\n    COW = 32 * NO\n    DIW = 64 * L\n    assert L == 8\n", body, 1)
body = sub(r"UInt\(32\)\[n, NC\]", "UInt(CIW)[n]", body, 2)
body = sub(r"UInt\(32\)\[n, NO\]", "UInt(COW)[n]", body, 2)
body = sub(r"UInt\(32\)\[n, 2 \* L\]", "UInt(DIW)[n]", body, 4)
body = sub(r"(\n            for t in range\(n\):\n)", r"\1                ciw: UInt(CIW) = cin[t]\n                diw: UInt(DIW) = din[t]\n                cow: UInt(COW) = 0\n                dow: UInt(DIW) = 0\n", body, 1)
body = sub(r"cin\[t, (\d+)\]", lambda m: f"ciw[{32 * int(m.group(1))}:{32 * int(m.group(1)) + 32}]", body, 15)
body = sub(r"cout\[t, (\d+)\] = ", lambda m: f"cow[{32 * int(m.group(1))}:{32 * int(m.group(1)) + 32}] = ", body, 20)
din_loop = ("                for k in range(L):\n                    rdata[k] = din[t, k]\n"
            "                    vdata[k] = din[t, L + k]\n")
assert body.count(din_loop) == 1
body = body.replace(din_loop, "".join(
    f"                rdata[{k}] = diw[{32 * k}:{32 * k + 32}]\n                vdata[{k}] = diw[{32 * (L + k)}:{32 * (L + k) + 32}]\n"
    for k in range(L)))
dout_loop = ("                for k in range(L):\n                    dout[t, k] = st_data[k]\n"
             "                    dout[t, L + k] = lnd_data[lnd_head, k]\n")
assert body.count(dout_loop) == 1
body = body.replace(dout_loop, "".join(
    f"                dow[{32 * k}:{32 * k + 32}] = st_data[{k}]\n                dow[{32 * (L + k)}:{32 * (L + k) + 32}] = lnd_data[lnd_head, {k}]\n"
    for k in range(L)) + "                cout[t] = cow\n                dout[t] = dow\n")
assert "cin[t," not in body and "din[t," not in body and "cout[t," not in body and "dout[t," not in body
head = '''# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Track-D form of ``dma.bits_reset`` (plan D1, one kernel) for Catapult --
GENERATED by ``../scripts/gen_dma_bits_form.py`` from ``units/dma.py``'s
``bits``; do not edit. Ports: one ``UInt(32 k)`` word per row (U3 track C C1);
``payload`` defaults to ``"reset"`` (``bits`` itself, ``reset=False``, is C2's
refusal). Runner ``dma.run_bits``."""
import allo.dataflow as df  # noqa: F401
from allo.ir.types import Stateful, UInt, int32  # noqa: F401

from examples.minitpu.units.dma import *  # noqa: F401,F403  (the names the body reads)
from examples.minitpu.units.dma import CIN_NAMES, COUT_NAMES, GEOMETRIES, run_bits  # noqa: F401

'''
open(f"{root}/dev/records/minitpu/u4_track_d_2026-10-08/forms/dma_bits_packed.py", "w").write(
    head + body + "\n\n\nrun = run_bits\n")
print("written")
