#=========================================================================
# OpenRAM SRAM Generation
#=========================================================================
# Author : Julian Bushlow
# Date   : June 17, 2026
#

name: openram-sram-generation

inputs: []

outputs:
  - srams

commands:
  - bash run.sh

parameters:
  construct_path: undefined
  sram_manifest: rtl/sram_manifest.yml
  python_bin: python
  openram_script: ""
  tech_name: freepdk45
  process_corner: TT
  supply_voltage: 1.1
  temperature: 25
  check_lvsdrc: False
  route_supplies: True
  analytical_delay: True
  use_sram_cache: False
  sram_cache_path: undefined

preconditions:
  - assert Tool( 'python' )
  - assert Tool( 'lc_shell' )
  - |
    import pathlib
    import openram

    openram_root = pathlib.Path(openram.__file__).resolve().parent
    sram_compiler = openram_root / "sram_compiler.py"

    assert sram_compiler.is_file(), f"Missing OpenRAM SRAM compiler: {sram_compiler}"

postconditions:
  - assert File( 'outputs/srams' )
