"""Functional cosim of the EVA (eva_sb_syscredit_rtprime) chip on the Allo
SystemC backend, using a REAL workload and a numpy golden (independent of the
JIT simulator).

Workload: single-node (1x1) systolic passthrough -- one PE loops MOV west->east
K times; a K-long ramp enters the WEST input and must exit EAST unchanged. The
collector compacts valid tokens from index 0, so out_e[0, 0:K] == ramp.

rtprime specifics handled here:
  * prime_cfg: int32[M,N] runtime-prime input, all = PRIME_TOKENS (6), passed as
    the FIRST positional arg (the `node` kernel is discovered first).
  * NSTEP margin: rtprime's runtime-prime credit flow needs more drain cycles
    than the compile-time-prime variant -- a generous margin (>=160) is required
    or the tokens never drain (all-zero output).

Run from this directory with the SystemC env set (see README.md):
    python cosim_eva_systemc.py
"""
import os, sys, numpy as np
os.environ.setdefault("OMP_NUM_THREADS", "8")
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)                 # eva_sb_syscredit_rtprime.py + eva_workloads.py

import eva_sb_syscredit_rtprime as e
e.M, e.N = 1, 1
sys.modules["eva"] = e                   # eva_workloads' `import eva` binds this chip
import eva_workloads as wl
import allo.dataflow as df
from allo.ir.types import float16

zi = lambda *s: np.zeros(s, np.int32)
z  = lambda *s: np.zeros(s, np.float16)
_NOP = e.OP_MOV | (6 << 4) | (6 << 8)

# ---- passthrough workload (single MOV west->east, looped K) ----
M, N, K = 1, 1, 6
e.IRF_DEPTH, e.DATADRIVEN = 8, 1
pc = M * (e.IRF_DEPTH + 2) + M + 4        # cycle by which the program is delivered (=15)
e.NSTEP = pc + 200                        # generous margin for rtprime's credit drain
e.LANELEN = e.NSTEP
L = e.LANELEN
print(f"config: M=N=1  K={K}  pc={pc}  NSTEP={L}  PRIME_TOKENS={e.PRIME_TOKENS}")

INSTR = e.OP_MOV | (0xF << 4) | (0xE << 8)          # MOV west-rx -> east-tx
prog = zi(M, N, e.IRF_DEPTH); prog[:] = _NOP; prog[0, 0, 0] = INSTR
rin_s_pkts = wl.load_prog_packets(prog, M, N, cfg=(1, K, 0))    # program over the router

PRJ = os.path.join(HERE, "generated")
os.system(f"rm -rf {PRJ}")
# Recreate the .gitignore that `rm -rf` just deleted. Without this the transient csim
# artifacts (a ~1.5 MB csim_sim binary and the *.data vectors) come back UNIGNORED, and
# the next `git add -A` commits them -- which is exactly what happened in 72c70dc.
os.makedirs(PRJ, exist_ok=True)
with open(os.path.join(PRJ, ".gitignore"), "w") as _f:
    _f.write(
        "# transient csim artifacts (regenerated by build_eva_systemc.py / cosim_eva_systemc.py)\n"
        "sim\ncsim_sim\n*.data\n*.o\n"
    )
mod = df.build(e.get_eva_top(float16), target="systemc", mode="csim", project=PRJ)
print("=== built EVA systemc; driving workload ===")

in_w, in_e, in_n, in_s = z(M, L), z(M, L), z(N, L), z(N, L)
out_w, out_e, out_n, out_s = z(M, L), z(M, L), z(N, L), z(N, L)
iv_w, iv_e, iv_n, iv_s = zi(M, L), zi(M, L), zi(N, L), zi(N, L)
rin_w, rin_e, rin_n, rin_s = zi(M, L), zi(M, L), zi(N, L), zi(N, L)
rout_w, rout_e, rout_n, rout_s = zi(M, L), zi(M, L), zi(N, L), zi(N, L)
prime_cfg = np.full((M, N), e.PRIME_TOKENS, np.int32)     # runtime prime = 6 per tile

ramp = np.arange(1, K + 1, dtype=np.float16)
for t in range(K):
    in_w[0, pc + t] = ramp[t]; iv_w[0, pc + t] = 1
rin_s[:] = rin_s_pkts

# arg order: prime_cfg FIRST (node discovered first), then the systolic/router args
mod(prime_cfg,
    in_w, iv_w, in_e, iv_e, in_n, iv_n, in_s, iv_s,
    out_w, out_e, out_n, out_s,
    rin_w, rin_e, rin_n, rin_s,
    rout_w, rout_e, rout_n, rout_s)

got = out_e[0, :K]
print("EXPECT ramp    :", ramp.astype(np.float32).tolist())
print("SYSTEMC out_e  :", got.astype(np.float32).tolist())
print("COSIM RESULT   :", "PASS (bit-exact)" if np.array_equal(got, ramp) else "MISMATCH")
