// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_accu_0_Pipeline_VITIS_LOOP_11667_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v5982_dout,
        v5982_num_data_valid,
        v5982_fifo_cap,
        v5982_empty_n,
        v5982_read,
        v6203_dout,
        v6203_num_data_valid,
        v6203_fifo_cap,
        v6203_empty_n,
        v6203_read,
        v5987_din,
        v5987_num_data_valid,
        v5987_fifo_cap,
        v5987_full_n,
        v5987_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] v5982_dout;
input  [3:0] v5982_num_data_valid;
input  [3:0] v5982_fifo_cap;
input   v5982_empty_n;
output   v5982_read;
input  [255:0] v6203_dout;
input  [3:0] v6203_num_data_valid;
input  [3:0] v6203_fifo_cap;
input   v6203_empty_n;
output   v6203_read;
output  [63:0] v5987_din;
input  [3:0] v5987_num_data_valid;
input  [3:0] v5987_fifo_cap;
input   v5987_full_n;
output   v5987_write;
input  [15:0] empty;

reg ap_idle;
reg v5982_read;
reg v6203_read;
reg v5987_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln11667_reg_1645;
reg   [0:0] v5348_reg_1649;
reg    ap_predicate_op49_read_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] icmp_ln11667_reg_1645_pp0_iter5_reg;
reg   [31:0] op3_2_reg_1668;
reg   [31:0] op3_2_reg_1668_pp0_iter5_reg;
reg    ap_predicate_op158_read_state7;
reg    ap_block_state7_pp0_stage0_iter6;
reg   [31:0] op3_2_reg_1668_pp0_iter6_reg;
reg    ap_predicate_op248_write_state8;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln11667_fu_362_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v5982_blk_n;
wire    ap_block_pp0_stage0;
reg    v5987_blk_n;
reg    v6203_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln11667_reg_1645_pp0_iter2_reg;
reg   [0:0] icmp_ln11667_reg_1645_pp0_iter3_reg;
reg   [0:0] icmp_ln11667_reg_1645_pp0_iter4_reg;
wire   [0:0] v5348_fu_385_p2;
wire   [7:0] trunc_ln11713_fu_498_p1;
reg   [7:0] trunc_ln11713_reg_1653;
wire   [0:0] v5376_fu_502_p1;
reg   [0:0] v5376_reg_1658;
reg   [7:0] v5369_reg_1663;
wire   [31:0] op3_2_load_fu_525_p1;
reg   [31:0] op3_2_reg_1668_pp0_iter4_reg;
wire   [0:0] v5530_fu_552_p2;
reg   [0:0] v5530_reg_1672;
reg   [0:0] v5530_reg_1672_pp0_iter4_reg;
reg   [0:0] v5530_reg_1672_pp0_iter5_reg;
reg   [0:0] v5530_reg_1672_pp0_iter6_reg;
wire   [7:0] wa1_fu_575_p3;
reg   [7:0] wa1_reg_1676;
reg   [7:0] wa1_reg_1676_pp0_iter4_reg;
reg   [7:0] wa1_reg_1676_pp0_iter5_reg;
reg   [7:0] wa1_reg_1676_pp0_iter6_reg;
wire   [7:0] ra1_fu_603_p3;
reg   [7:0] ra1_reg_1681;
wire   [0:0] v5422_fu_611_p2;
reg   [0:0] v5422_reg_1686;
reg   [0:0] v5422_reg_1686_pp0_iter4_reg;
reg   [0:0] v5422_reg_1686_pp0_iter5_reg;
wire   [255:0] ar_q1;
reg   [255:0] v5703_reg_1696;
wire   [255:0] zext_ln12421_fu_860_p1;
wire   [255:0] v5636_tmp_fu_992_p9;
wire   [255:0] v5527_tmp_fu_1214_p9;
wire   [7:0] v5710_fu_1270_p3;
reg   [7:0] v5710_reg_1749;
wire   [7:0] v5721_fu_1311_p3;
reg   [7:0] v5721_reg_1754;
wire   [7:0] v5732_fu_1352_p3;
reg   [7:0] v5732_reg_1759;
wire   [7:0] v5743_fu_1393_p3;
reg   [7:0] v5743_reg_1764;
wire   [7:0] v5754_fu_1434_p3;
reg   [7:0] v5754_reg_1769;
wire   [7:0] v5765_fu_1475_p3;
reg   [7:0] v5765_reg_1774;
wire   [7:0] v5776_fu_1516_p3;
reg   [7:0] v5776_reg_1779;
wire   [7:0] v5787_fu_1557_p3;
reg   [7:0] v5787_reg_1784;
wire   [7:0] ar_address0;
reg    ar_ce0;
reg    ar_we0;
wire   [7:0] ar_address1;
reg    ar_ce1;
wire   [255:0] ap_phi_reg_pp0_iter0_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter1_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter2_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter3_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter4_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter5_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter6_z_3_ph_reg_244;
reg   [255:0] ap_phi_reg_pp0_iter7_z_3_ph_reg_244;
reg    ap_predicate_pred284_state7;
reg    ap_predicate_pred290_state7;
reg    ap_predicate_pred295_state7;
wire   [63:0] zext_ln11788_fu_617_p1;
wire   [63:0] zext_ln12656_fu_1565_p1;
reg    ap_predicate_pred310_state8;
reg   [15:0] v5341_fu_160;
wire   [15:0] v5341_2_fu_367_p2;
wire    ap_loop_init;
reg   [31:0] v5342_fu_164;
wire   [31:0] v5345_fu_379_p2;
reg   [255:0] v5625_tmp_fu_168;
reg    ap_predicate_pred345_state6;
reg   [31:0] v5347_fu_172;
wire   [31:0] zext_ln11709_fu_466_p1;
reg   [31:0] ap_sig_allocacmp_v5347_load;
reg   [31:0] f22_fu_176;
wire   [31:0] zext_ln11703_fu_452_p1;
reg   [31:0] f13_fu_180;
wire   [31:0] zext_ln11697_fu_438_p1;
reg   [31:0] f03_fu_184;
wire   [31:0] zext_ln11691_fu_424_p1;
reg   [31:0] op3_fu_188;
wire   [31:0] zext_ln11685_fu_410_p1;
reg    ap_block_pp0_stage0_01001;
reg    ap_predicate_pred407_state7;
wire   [5:0] v5351_fu_406_p1;
wire   [11:0] v5354_fu_414_p4;
wire   [11:0] v5357_fu_428_p4;
wire   [11:0] v5360_fu_442_p4;
wire   [7:0] v5363_fu_456_p4;
wire   [0:0] v5367_fu_540_p2;
wire   [7:0] rr_fu_546_p3;
wire   [7:0] trunc_ln11713_3_fu_536_p1;
wire   [7:0] trunc_ln11713_2_fu_532_p1;
wire   [0:0] v5390_fu_569_p2;
wire   [7:0] v5382_fu_557_p2;
wire   [7:0] v5388_fu_563_p2;
wire   [0:0] v5398_fu_583_p2;
wire   [7:0] trunc_ln11713_1_fu_528_p1;
wire   [7:0] v5414_fu_597_p2;
wire   [7:0] ra1_3_fu_589_p3;
wire   [0:0] v5643_fu_629_p3;
wire   [30:0] trunc_ln12258_fu_626_p1;
wire   [30:0] re_fu_636_p3;
wire   [0:0] v5651_fu_657_p3;
wire   [30:0] trunc_ln1_fu_648_p4;
wire   [30:0] re1_fu_664_p3;
wire   [0:0] v5659_fu_685_p3;
wire   [30:0] trunc_ln2_fu_676_p4;
wire   [30:0] re2_fu_692_p3;
wire   [0:0] v5667_fu_713_p3;
wire   [30:0] trunc_ln3_fu_704_p4;
wire   [30:0] re3_fu_720_p3;
wire   [0:0] v5675_fu_741_p3;
wire   [30:0] trunc_ln4_fu_732_p4;
wire   [30:0] re4_fu_748_p3;
wire   [0:0] v5683_fu_769_p3;
wire   [30:0] trunc_ln5_fu_760_p4;
wire   [30:0] re5_fu_776_p3;
wire   [0:0] v5691_fu_797_p3;
wire   [30:0] trunc_ln6_fu_788_p4;
wire   [30:0] re6_fu_804_p3;
wire   [0:0] v5699_fu_825_p3;
wire   [30:0] trunc_ln7_fu_816_p4;
wire   [30:0] re7_fu_832_p3;
wire   [31:0] zext_ln12390_fu_812_p1;
wire   [31:0] zext_ln12369_fu_784_p1;
wire   [31:0] zext_ln12348_fu_756_p1;
wire   [31:0] zext_ln12327_fu_728_p1;
wire   [31:0] zext_ln12306_fu_700_p1;
wire   [31:0] zext_ln12285_fu_672_p1;
wire   [31:0] zext_ln12264_fu_644_p1;
wire   [254:0] v5702_tmp_fu_840_p9;
wire   [31:0] v5536_fu_871_p1;
wire   [31:0] v5534_fu_867_p1;
wire   [31:0] grp_fu_256_p4;
wire   [31:0] v5547_fu_880_p4;
wire   [31:0] grp_fu_265_p4;
wire   [31:0] v5560_fu_896_p4;
wire   [31:0] grp_fu_274_p4;
wire   [31:0] v5573_fu_912_p4;
wire   [31:0] grp_fu_283_p4;
wire   [31:0] v5586_fu_928_p4;
wire   [31:0] grp_fu_292_p4;
wire   [31:0] v5599_fu_944_p4;
wire   [31:0] grp_fu_301_p4;
wire   [31:0] v5612_fu_960_p4;
wire   [31:0] grp_fu_310_p4;
wire   [31:0] v5625_fu_976_p4;
wire   [31:0] v5633_fu_986_p2;
wire   [31:0] v5620_fu_970_p2;
wire   [31:0] v5607_fu_954_p2;
wire   [31:0] v5594_fu_938_p2;
wire   [31:0] v5581_fu_922_p2;
wire   [31:0] v5568_fu_906_p2;
wire   [31:0] v5555_fu_890_p2;
wire   [31:0] v5542_fu_874_p2;
wire   [255:0] base_fu_1012_p3;
wire   [31:0] v5427_fu_1022_p1;
wire   [31:0] v5425_fu_1018_p1;
wire   [31:0] v5440_fu_1042_p4;
wire   [31:0] v5438_fu_1032_p4;
wire   [31:0] v5453_fu_1068_p4;
wire   [31:0] v5451_fu_1058_p4;
wire   [31:0] v5466_fu_1094_p4;
wire   [31:0] v5464_fu_1084_p4;
wire   [31:0] v5479_fu_1120_p4;
wire   [31:0] v5477_fu_1110_p4;
wire   [31:0] v5492_fu_1146_p4;
wire   [31:0] v5490_fu_1136_p4;
wire   [31:0] v5505_fu_1172_p4;
wire   [31:0] v5503_fu_1162_p4;
wire   [31:0] v5518_fu_1198_p4;
wire   [31:0] v5516_fu_1188_p4;
wire   [31:0] v5524_fu_1208_p2;
wire   [31:0] v5511_fu_1182_p2;
wire   [31:0] v5498_fu_1156_p2;
wire   [31:0] v5485_fu_1130_p2;
wire   [31:0] v5472_fu_1104_p2;
wire   [31:0] v5459_fu_1078_p2;
wire   [31:0] v5446_fu_1052_p2;
wire   [31:0] v5433_fu_1026_p2;
wire   [24:0] tmp_3_fu_1237_p4;
wire   [0:0] v5706_fu_1246_p2;
wire   [31:0] v5704_fu_1234_p1;
wire   [31:0] te_fu_1252_p3;
wire   [0:0] v5708_fu_1260_p2;
wire   [7:0] trunc_ln12446_fu_1266_p1;
wire   [24:0] tmp_4_fu_1278_p4;
wire   [0:0] v5717_fu_1287_p2;
wire   [31:0] te1_fu_1293_p3;
wire   [0:0] v5719_fu_1301_p2;
wire   [7:0] trunc_ln12473_fu_1307_p1;
wire   [24:0] tmp_5_fu_1319_p4;
wire   [0:0] v5728_fu_1328_p2;
wire   [31:0] te2_fu_1334_p3;
wire   [0:0] v5730_fu_1342_p2;
wire   [7:0] trunc_ln12500_fu_1348_p1;
wire   [24:0] tmp_6_fu_1360_p4;
wire   [0:0] v5739_fu_1369_p2;
wire   [31:0] te3_fu_1375_p3;
wire   [0:0] v5741_fu_1383_p2;
wire   [7:0] trunc_ln12527_fu_1389_p1;
wire   [24:0] tmp_7_fu_1401_p4;
wire   [0:0] v5750_fu_1410_p2;
wire   [31:0] te4_fu_1416_p3;
wire   [0:0] v5752_fu_1424_p2;
wire   [7:0] trunc_ln12554_fu_1430_p1;
wire   [24:0] tmp_8_fu_1442_p4;
wire   [0:0] v5761_fu_1451_p2;
wire   [31:0] te5_fu_1457_p3;
wire   [0:0] v5763_fu_1465_p2;
wire   [7:0] trunc_ln12581_fu_1471_p1;
wire   [24:0] tmp_9_fu_1483_p4;
wire   [0:0] v5772_fu_1492_p2;
wire   [31:0] te6_fu_1498_p3;
wire   [0:0] v5774_fu_1506_p2;
wire   [7:0] trunc_ln12608_fu_1512_p1;
wire   [24:0] tmp_10_fu_1524_p4;
wire   [0:0] v5783_fu_1533_p2;
wire   [31:0] te7_fu_1539_p3;
wire   [0:0] v5785_fu_1547_p2;
wire   [7:0] trunc_ln12635_fu_1553_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_93;
reg    ap_enable_state5_pp0_iter4_stage0;
reg    ap_enable_operation_94;
reg    ap_enable_state6_pp0_iter5_stage0;
reg    ap_predicate_op245_store_state8;
reg    ap_enable_operation_245;
reg    ap_enable_state8_pp0_iter7_stage0;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1244;
reg    ap_condition_1249;
reg    ap_condition_1253;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 v5341_fu_160 = 16'd0;
#0 v5342_fu_164 = 32'd0;
#0 v5625_tmp_fu_168 = 256'd0;
#0 v5347_fu_172 = 32'd0;
#0 f22_fu_176 = 32'd0;
#0 f13_fu_180 = 32'd0;
#0 f03_fu_184 = 32'd0;
#0 op3_fu_188 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_accu_0_Pipeline_VITIS_LOOP_11667_1_ar_RAM_AUTO_1R1W #(
    .DataWidth( 256 ),
    .AddressRange( 136 ),
    .AddressWidth( 8 ))
ar_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ar_address0),
    .ce0(ar_ce0),
    .we0(ar_we0),
    .d0(ap_phi_reg_pp0_iter7_z_3_ph_reg_244),
    .address1(ar_address1),
    .ce1(ar_ce1),
    .q1(ar_q1)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        if ((ap_predicate_pred295_state7 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_z_3_ph_reg_244 <= v5527_tmp_fu_1214_p9;
        end else if ((ap_predicate_pred290_state7 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_z_3_ph_reg_244 <= zext_ln12421_fu_860_p1;
        end else if ((ap_predicate_pred284_state7 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_z_3_ph_reg_244 <= v5636_tmp_fu_992_p9;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter6_z_3_ph_reg_244;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f03_fu_184[0] <= 1'b0;
            f03_fu_184[1] <= 1'b0;
            f03_fu_184[2] <= 1'b0;
            f03_fu_184[3] <= 1'b0;
            f03_fu_184[4] <= 1'b0;
            f03_fu_184[5] <= 1'b0;
            f03_fu_184[6] <= 1'b0;
            f03_fu_184[7] <= 1'b0;
            f03_fu_184[8] <= 1'b0;
            f03_fu_184[9] <= 1'b0;
            f03_fu_184[10] <= 1'b0;
            f03_fu_184[11] <= 1'b0;
        end else if ((1'b1 == ap_condition_1244)) begin
                        f03_fu_184[11 : 0] <= zext_ln11691_fu_424_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f13_fu_180[0] <= 1'b0;
            f13_fu_180[1] <= 1'b0;
            f13_fu_180[2] <= 1'b0;
            f13_fu_180[3] <= 1'b0;
            f13_fu_180[4] <= 1'b0;
            f13_fu_180[5] <= 1'b0;
            f13_fu_180[6] <= 1'b0;
            f13_fu_180[7] <= 1'b0;
            f13_fu_180[8] <= 1'b0;
            f13_fu_180[9] <= 1'b0;
            f13_fu_180[10] <= 1'b0;
            f13_fu_180[11] <= 1'b0;
        end else if ((1'b1 == ap_condition_1244)) begin
                        f13_fu_180[11 : 0] <= zext_ln11697_fu_438_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f22_fu_176[0] <= 1'b0;
            f22_fu_176[1] <= 1'b0;
            f22_fu_176[2] <= 1'b0;
            f22_fu_176[3] <= 1'b0;
            f22_fu_176[4] <= 1'b0;
            f22_fu_176[5] <= 1'b0;
            f22_fu_176[6] <= 1'b0;
            f22_fu_176[7] <= 1'b0;
            f22_fu_176[8] <= 1'b0;
            f22_fu_176[9] <= 1'b0;
            f22_fu_176[10] <= 1'b0;
            f22_fu_176[11] <= 1'b0;
        end else if ((1'b1 == ap_condition_1244)) begin
                        f22_fu_176[11 : 0] <= zext_ln11703_fu_452_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        op3_fu_188[0] <= 1'b0;
            op3_fu_188[1] <= 1'b0;
            op3_fu_188[2] <= 1'b0;
            op3_fu_188[3] <= 1'b0;
            op3_fu_188[4] <= 1'b0;
            op3_fu_188[5] <= 1'b0;
        end else if ((1'b1 == ap_condition_1244)) begin
                        op3_fu_188[5 : 0] <= zext_ln11685_fu_410_p1[5 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v5341_fu_160 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln11667_fu_362_p2 == 1'd0))) begin
            v5341_fu_160 <= v5341_2_fu_367_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v5342_fu_164 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_1253)) begin
            v5342_fu_164 <= v5345_fu_379_p2;
        end else if ((1'b1 == ap_condition_1249)) begin
            v5342_fu_164 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        v5347_fu_172[0] <= 1'b0;
            v5347_fu_172[1] <= 1'b0;
            v5347_fu_172[2] <= 1'b0;
            v5347_fu_172[3] <= 1'b0;
            v5347_fu_172[4] <= 1'b0;
            v5347_fu_172[5] <= 1'b0;
            v5347_fu_172[6] <= 1'b0;
            v5347_fu_172[7] <= 1'b0;
        end else if ((1'b1 == ap_condition_1244)) begin
                        v5347_fu_172[7 : 0] <= zext_ln11709_fu_466_p1[7 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            v5625_tmp_fu_168 <= 256'd0;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_predicate_pred345_state6 == 1'b1))) begin
            v5625_tmp_fu_168 <= ar_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln11667_reg_1645 <= icmp_ln11667_fu_362_p2;
        v5348_reg_1649 <= v5348_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_predicate_pred284_state7 <= ((v5530_reg_1672_pp0_iter4_reg == 1'd1) & (op3_2_reg_1668_pp0_iter4_reg == 32'd5) & (icmp_ln11667_reg_1645_pp0_iter4_reg == 1'd0));
        ap_predicate_pred290_state7 <= ((op3_2_reg_1668_pp0_iter4_reg == 32'd6) & (icmp_ln11667_reg_1645_pp0_iter4_reg == 1'd0));
        ap_predicate_pred295_state7 <= ((op3_2_reg_1668_pp0_iter4_reg == 32'd4) & (icmp_ln11667_reg_1645_pp0_iter4_reg == 1'd0));
        ap_predicate_pred310_state8 <= ((op3_2_reg_1668_pp0_iter5_reg == 32'd4) | ((op3_2_reg_1668_pp0_iter5_reg == 32'd6) | ((op3_2_reg_1668_pp0_iter5_reg == 32'd5) & (v5530_reg_1672_pp0_iter5_reg == 1'd1))));
        ap_predicate_pred345_state6 <= ((op3_2_reg_1668 == 32'd5) & (v5530_reg_1672 == 1'd0));
        ap_predicate_pred407_state7 <= (~(op3_2_reg_1668_pp0_iter4_reg == 32'd4) & ~(op3_2_reg_1668_pp0_iter4_reg == 32'd6) & ~(op3_2_reg_1668_pp0_iter4_reg == 32'd5));
        icmp_ln11667_reg_1645_pp0_iter2_reg <= icmp_ln11667_reg_1645;
        icmp_ln11667_reg_1645_pp0_iter3_reg <= icmp_ln11667_reg_1645_pp0_iter2_reg;
        icmp_ln11667_reg_1645_pp0_iter4_reg <= icmp_ln11667_reg_1645_pp0_iter3_reg;
        icmp_ln11667_reg_1645_pp0_iter5_reg <= icmp_ln11667_reg_1645_pp0_iter4_reg;
        op3_2_reg_1668[5 : 0] <= op3_fu_188[5 : 0];
        op3_2_reg_1668_pp0_iter4_reg[5 : 0] <= op3_2_reg_1668[5 : 0];
        op3_2_reg_1668_pp0_iter5_reg[5 : 0] <= op3_2_reg_1668_pp0_iter4_reg[5 : 0];
        op3_2_reg_1668_pp0_iter6_reg[5 : 0] <= op3_2_reg_1668_pp0_iter5_reg[5 : 0];
        ra1_reg_1681 <= ra1_fu_603_p3;
        trunc_ln11713_reg_1653 <= trunc_ln11713_fu_498_p1;
        v5369_reg_1663 <= {{v5342_fu_164[8:1]}};
        v5376_reg_1658 <= v5376_fu_502_p1;
        v5422_reg_1686 <= v5422_fu_611_p2;
        v5422_reg_1686_pp0_iter4_reg <= v5422_reg_1686;
        v5422_reg_1686_pp0_iter5_reg <= v5422_reg_1686_pp0_iter4_reg;
        v5530_reg_1672 <= v5530_fu_552_p2;
        v5530_reg_1672_pp0_iter4_reg <= v5530_reg_1672;
        v5530_reg_1672_pp0_iter5_reg <= v5530_reg_1672_pp0_iter4_reg;
        v5530_reg_1672_pp0_iter6_reg <= v5530_reg_1672_pp0_iter5_reg;
        v5710_reg_1749 <= v5710_fu_1270_p3;
        v5721_reg_1754 <= v5721_fu_1311_p3;
        v5732_reg_1759 <= v5732_fu_1352_p3;
        v5743_reg_1764 <= v5743_fu_1393_p3;
        v5754_reg_1769 <= v5754_fu_1434_p3;
        v5765_reg_1774 <= v5765_fu_1475_p3;
        v5776_reg_1779 <= v5776_fu_1516_p3;
        v5787_reg_1784 <= v5787_fu_1557_p3;
        wa1_reg_1676 <= wa1_fu_575_p3;
        wa1_reg_1676_pp0_iter4_reg <= wa1_reg_1676;
        wa1_reg_1676_pp0_iter5_reg <= wa1_reg_1676_pp0_iter4_reg;
        wa1_reg_1676_pp0_iter6_reg <= wa1_reg_1676_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter0_z_3_ph_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter1_z_3_ph_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter2_z_3_ph_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter3_z_3_ph_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter4_z_3_ph_reg_244;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_z_3_ph_reg_244 <= ap_phi_reg_pp0_iter5_z_3_ph_reg_244;
        v5703_reg_1696 <= ar_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln11667_fu_362_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v5348_reg_1649 == 1'd0) & (icmp_ln11667_reg_1645 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_v5347_load = zext_ln11709_fu_466_p1;
    end else begin
        ap_sig_allocacmp_v5347_load = v5347_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ar_ce0 = 1'b1;
    end else begin
        ar_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ar_ce1 = 1'b1;
    end else begin
        ar_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_pred310_state8 == 1'b1))) begin
        ar_we0 = 1'b1;
    end else begin
        ar_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op49_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v5982_blk_n = v5982_empty_n;
    end else begin
        v5982_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op49_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v5982_read = 1'b1;
    end else begin
        v5982_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op248_write_state8 == 1'b1))) begin
        v5987_blk_n = v5987_full_n;
    end else begin
        v5987_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (ap_predicate_op248_write_state8 == 1'b1))) begin
        v5987_write = 1'b1;
    end else begin
        v5987_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op158_read_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        v6203_blk_n = v6203_empty_n;
    end else begin
        v6203_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op158_read_state7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        v6203_read = 1'b1;
    end else begin
        v6203_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage0_iter7)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op49_read_state3 == 1'b1) & (v5982_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((ap_predicate_op158_read_state7 == 1'b1) & (v6203_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = ((v5987_full_n == 1'b0) & (ap_predicate_op248_write_state8 == 1'b1));
end

always @ (*) begin
    ap_condition_1244 = ((v5348_reg_1649 == 1'd0) & (icmp_ln11667_reg_1645 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1249 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v5348_fu_385_p2 == 1'd0) & (icmp_ln11667_fu_362_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1253 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v5348_fu_385_p2 == 1'd1) & (icmp_ln11667_fu_362_p2 == 1'd0));
end

always @ (*) begin
    ap_enable_operation_245 = (ap_predicate_op245_store_state8 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_93 = (icmp_ln11667_reg_1645_pp0_iter3_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_94 = (icmp_ln11667_reg_1645_pp0_iter4_reg == 1'd0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state5_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state6_pp0_iter5_stage0 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state8_pp0_iter7_stage0 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_z_3_ph_reg_244 = 'bx;

always @ (*) begin
    ap_predicate_op158_read_state7 = ((op3_2_reg_1668_pp0_iter5_reg == 32'd4) & (icmp_ln11667_reg_1645_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op245_store_state8 = ((op3_2_reg_1668_pp0_iter6_reg == 32'd4) | ((op3_2_reg_1668_pp0_iter6_reg == 32'd6) | ((v5530_reg_1672_pp0_iter6_reg == 1'd1) & (op3_2_reg_1668_pp0_iter6_reg == 32'd5))));
end

always @ (*) begin
    ap_predicate_op248_write_state8 = (~(op3_2_reg_1668_pp0_iter6_reg == 32'd6) & ~(op3_2_reg_1668_pp0_iter6_reg == 32'd5) & ~(op3_2_reg_1668_pp0_iter6_reg == 32'd4));
end

always @ (*) begin
    ap_predicate_op49_read_state3 = ((v5348_reg_1649 == 1'd0) & (icmp_ln11667_reg_1645 == 1'd0));
end

assign ar_address0 = zext_ln12656_fu_1565_p1;

assign ar_address1 = zext_ln11788_fu_617_p1;

assign base_fu_1012_p3 = ((v5422_reg_1686_pp0_iter5_reg[0:0] == 1'b1) ? v5703_reg_1696 : 256'd0);

assign grp_fu_256_p4 = {{v5703_reg_1696[63:32]}};

assign grp_fu_265_p4 = {{v5703_reg_1696[95:64]}};

assign grp_fu_274_p4 = {{v5703_reg_1696[127:96]}};

assign grp_fu_283_p4 = {{v5703_reg_1696[159:128]}};

assign grp_fu_292_p4 = {{v5703_reg_1696[191:160]}};

assign grp_fu_301_p4 = {{v5703_reg_1696[223:192]}};

assign grp_fu_310_p4 = {{v5703_reg_1696[255:224]}};

assign icmp_ln11667_fu_362_p2 = ((v5341_fu_160 == empty) ? 1'b1 : 1'b0);

assign op3_2_load_fu_525_p1 = op3_fu_188;

assign ra1_3_fu_589_p3 = ((v5398_fu_583_p2[0:0] == 1'b1) ? v5388_fu_563_p2 : v5382_fu_557_p2);

assign ra1_fu_603_p3 = ((v5530_fu_552_p2[0:0] == 1'b1) ? v5414_fu_597_p2 : ra1_3_fu_589_p3);

assign re1_fu_664_p3 = ((v5651_fu_657_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln1_fu_648_p4);

assign re2_fu_692_p3 = ((v5659_fu_685_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln2_fu_676_p4);

assign re3_fu_720_p3 = ((v5667_fu_713_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln3_fu_704_p4);

assign re4_fu_748_p3 = ((v5675_fu_741_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln4_fu_732_p4);

assign re5_fu_776_p3 = ((v5683_fu_769_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln5_fu_760_p4);

assign re6_fu_804_p3 = ((v5691_fu_797_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln6_fu_788_p4);

assign re7_fu_832_p3 = ((v5699_fu_825_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln7_fu_816_p4);

assign re_fu_636_p3 = ((v5643_fu_629_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln12258_fu_626_p1);

assign rr_fu_546_p3 = ((v5367_fu_540_p2[0:0] == 1'b1) ? v5369_reg_1663 : trunc_ln11713_reg_1653);

assign te1_fu_1293_p3 = ((v5717_fu_1287_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_256_p4);

assign te2_fu_1334_p3 = ((v5728_fu_1328_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_265_p4);

assign te3_fu_1375_p3 = ((v5739_fu_1369_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_274_p4);

assign te4_fu_1416_p3 = ((v5750_fu_1410_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_283_p4);

assign te5_fu_1457_p3 = ((v5761_fu_1451_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_292_p4);

assign te6_fu_1498_p3 = ((v5772_fu_1492_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_301_p4);

assign te7_fu_1539_p3 = ((v5783_fu_1533_p2[0:0] == 1'b1) ? 32'd127 : grp_fu_310_p4);

assign te_fu_1252_p3 = ((v5706_fu_1246_p2[0:0] == 1'b1) ? 32'd127 : v5704_fu_1234_p1);

assign tmp_10_fu_1524_p4 = {{v5703_reg_1696[255:231]}};

assign tmp_3_fu_1237_p4 = {{v5703_reg_1696[31:7]}};

assign tmp_4_fu_1278_p4 = {{v5703_reg_1696[63:39]}};

assign tmp_5_fu_1319_p4 = {{v5703_reg_1696[95:71]}};

assign tmp_6_fu_1360_p4 = {{v5703_reg_1696[127:103]}};

assign tmp_7_fu_1401_p4 = {{v5703_reg_1696[159:135]}};

assign tmp_8_fu_1442_p4 = {{v5703_reg_1696[191:167]}};

assign tmp_9_fu_1483_p4 = {{v5703_reg_1696[223:199]}};

assign trunc_ln11713_1_fu_528_p1 = f22_fu_176[7:0];

assign trunc_ln11713_2_fu_532_p1 = f03_fu_184[7:0];

assign trunc_ln11713_3_fu_536_p1 = f13_fu_180[7:0];

assign trunc_ln11713_fu_498_p1 = v5342_fu_164[7:0];

assign trunc_ln12258_fu_626_p1 = v5703_reg_1696[30:0];

assign trunc_ln12446_fu_1266_p1 = te_fu_1252_p3[7:0];

assign trunc_ln12473_fu_1307_p1 = te1_fu_1293_p3[7:0];

assign trunc_ln12500_fu_1348_p1 = te2_fu_1334_p3[7:0];

assign trunc_ln12527_fu_1389_p1 = te3_fu_1375_p3[7:0];

assign trunc_ln12554_fu_1430_p1 = te4_fu_1416_p3[7:0];

assign trunc_ln12581_fu_1471_p1 = te5_fu_1457_p3[7:0];

assign trunc_ln12608_fu_1512_p1 = te6_fu_1498_p3[7:0];

assign trunc_ln12635_fu_1553_p1 = te7_fu_1539_p3[7:0];

assign trunc_ln1_fu_648_p4 = {{v5703_reg_1696[62:32]}};

assign trunc_ln2_fu_676_p4 = {{v5703_reg_1696[94:64]}};

assign trunc_ln3_fu_704_p4 = {{v5703_reg_1696[126:96]}};

assign trunc_ln4_fu_732_p4 = {{v5703_reg_1696[158:128]}};

assign trunc_ln5_fu_760_p4 = {{v5703_reg_1696[190:160]}};

assign trunc_ln6_fu_788_p4 = {{v5703_reg_1696[222:192]}};

assign trunc_ln7_fu_816_p4 = {{v5703_reg_1696[254:224]}};

assign v5341_2_fu_367_p2 = (v5341_fu_160 + 16'd1);

assign v5345_fu_379_p2 = (v5342_fu_164 + 32'd1);

assign v5348_fu_385_p2 = (($signed(v5345_fu_379_p2) < $signed(ap_sig_allocacmp_v5347_load)) ? 1'b1 : 1'b0);

assign v5351_fu_406_p1 = v5982_dout[5:0];

assign v5354_fu_414_p4 = {{v5982_dout[17:6]}};

assign v5357_fu_428_p4 = {{v5982_dout[29:18]}};

assign v5360_fu_442_p4 = {{v5982_dout[41:30]}};

assign v5363_fu_456_p4 = {{v5982_dout[61:54]}};

assign v5367_fu_540_p2 = ((op3_fu_188 == 32'd5) ? 1'b1 : 1'b0);

assign v5376_fu_502_p1 = v5342_fu_164[0:0];

assign v5382_fu_557_p2 = (rr_fu_546_p3 + trunc_ln11713_3_fu_536_p1);

assign v5388_fu_563_p2 = (rr_fu_546_p3 + trunc_ln11713_2_fu_532_p1);

assign v5390_fu_569_p2 = ((op3_fu_188 == 32'd4) ? 1'b1 : 1'b0);

assign v5398_fu_583_p2 = ((op3_fu_188 == 32'd7) ? 1'b1 : 1'b0);

assign v5414_fu_597_p2 = (rr_fu_546_p3 + trunc_ln11713_1_fu_528_p1);

assign v5422_fu_611_p2 = ((f22_fu_176 == 32'd1) ? 1'b1 : 1'b0);

assign v5425_fu_1018_p1 = base_fu_1012_p3[31:0];

assign v5427_fu_1022_p1 = v6203_dout[31:0];

assign v5433_fu_1026_p2 = (v5427_fu_1022_p1 + v5425_fu_1018_p1);

assign v5438_fu_1032_p4 = {{base_fu_1012_p3[63:32]}};

assign v5440_fu_1042_p4 = {{v6203_dout[63:32]}};

assign v5446_fu_1052_p2 = (v5440_fu_1042_p4 + v5438_fu_1032_p4);

assign v5451_fu_1058_p4 = {{base_fu_1012_p3[95:64]}};

assign v5453_fu_1068_p4 = {{v6203_dout[95:64]}};

assign v5459_fu_1078_p2 = (v5453_fu_1068_p4 + v5451_fu_1058_p4);

assign v5464_fu_1084_p4 = {{base_fu_1012_p3[127:96]}};

assign v5466_fu_1094_p4 = {{v6203_dout[127:96]}};

assign v5472_fu_1104_p2 = (v5466_fu_1094_p4 + v5464_fu_1084_p4);

assign v5477_fu_1110_p4 = {{base_fu_1012_p3[159:128]}};

assign v5479_fu_1120_p4 = {{v6203_dout[159:128]}};

assign v5485_fu_1130_p2 = (v5479_fu_1120_p4 + v5477_fu_1110_p4);

assign v5490_fu_1136_p4 = {{base_fu_1012_p3[191:160]}};

assign v5492_fu_1146_p4 = {{v6203_dout[191:160]}};

assign v5498_fu_1156_p2 = (v5492_fu_1146_p4 + v5490_fu_1136_p4);

assign v5503_fu_1162_p4 = {{base_fu_1012_p3[223:192]}};

assign v5505_fu_1172_p4 = {{v6203_dout[223:192]}};

assign v5511_fu_1182_p2 = (v5505_fu_1172_p4 + v5503_fu_1162_p4);

assign v5516_fu_1188_p4 = {{base_fu_1012_p3[255:224]}};

assign v5518_fu_1198_p4 = {{v6203_dout[255:224]}};

assign v5524_fu_1208_p2 = (v5518_fu_1198_p4 + v5516_fu_1188_p4);

assign v5527_tmp_fu_1214_p9 = {{{{{{{{v5524_fu_1208_p2}, {v5511_fu_1182_p2}}, {v5498_fu_1156_p2}}, {v5485_fu_1130_p2}}, {v5472_fu_1104_p2}}, {v5459_fu_1078_p2}}, {v5446_fu_1052_p2}}, {v5433_fu_1026_p2}};

assign v5530_fu_552_p2 = (v5376_reg_1658 & v5367_fu_540_p2);

assign v5534_fu_867_p1 = v5625_tmp_fu_168[31:0];

assign v5536_fu_871_p1 = v5703_reg_1696[31:0];

assign v5542_fu_874_p2 = (v5536_fu_871_p1 + v5534_fu_867_p1);

assign v5547_fu_880_p4 = {{v5625_tmp_fu_168[63:32]}};

assign v5555_fu_890_p2 = (grp_fu_256_p4 + v5547_fu_880_p4);

assign v5560_fu_896_p4 = {{v5625_tmp_fu_168[95:64]}};

assign v5568_fu_906_p2 = (grp_fu_265_p4 + v5560_fu_896_p4);

assign v5573_fu_912_p4 = {{v5625_tmp_fu_168[127:96]}};

assign v5581_fu_922_p2 = (grp_fu_274_p4 + v5573_fu_912_p4);

assign v5586_fu_928_p4 = {{v5625_tmp_fu_168[159:128]}};

assign v5594_fu_938_p2 = (grp_fu_283_p4 + v5586_fu_928_p4);

assign v5599_fu_944_p4 = {{v5625_tmp_fu_168[191:160]}};

assign v5607_fu_954_p2 = (grp_fu_292_p4 + v5599_fu_944_p4);

assign v5612_fu_960_p4 = {{v5625_tmp_fu_168[223:192]}};

assign v5620_fu_970_p2 = (grp_fu_301_p4 + v5612_fu_960_p4);

assign v5625_fu_976_p4 = {{v5625_tmp_fu_168[255:224]}};

assign v5633_fu_986_p2 = (grp_fu_310_p4 + v5625_fu_976_p4);

assign v5636_tmp_fu_992_p9 = {{{{{{{{v5633_fu_986_p2}, {v5620_fu_970_p2}}, {v5607_fu_954_p2}}, {v5594_fu_938_p2}}, {v5581_fu_922_p2}}, {v5568_fu_906_p2}}, {v5555_fu_890_p2}}, {v5542_fu_874_p2}};

assign v5643_fu_629_p3 = v5703_reg_1696[32'd31];

assign v5651_fu_657_p3 = v5703_reg_1696[32'd63];

assign v5659_fu_685_p3 = v5703_reg_1696[32'd95];

assign v5667_fu_713_p3 = v5703_reg_1696[32'd127];

assign v5675_fu_741_p3 = v5703_reg_1696[32'd159];

assign v5683_fu_769_p3 = v5703_reg_1696[32'd191];

assign v5691_fu_797_p3 = v5703_reg_1696[32'd223];

assign v5699_fu_825_p3 = v5703_reg_1696[32'd255];

assign v5702_tmp_fu_840_p9 = {{{{{{{{re7_fu_832_p3}, {zext_ln12390_fu_812_p1}}, {zext_ln12369_fu_784_p1}}, {zext_ln12348_fu_756_p1}}, {zext_ln12327_fu_728_p1}}, {zext_ln12306_fu_700_p1}}, {zext_ln12285_fu_672_p1}}, {zext_ln12264_fu_644_p1}};

assign v5704_fu_1234_p1 = v5703_reg_1696[31:0];

assign v5706_fu_1246_p2 = (($signed(tmp_3_fu_1237_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5708_fu_1260_p2 = (($signed(te_fu_1252_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5710_fu_1270_p3 = ((v5708_fu_1260_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12446_fu_1266_p1);

assign v5717_fu_1287_p2 = (($signed(tmp_4_fu_1278_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5719_fu_1301_p2 = (($signed(te1_fu_1293_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5721_fu_1311_p3 = ((v5719_fu_1301_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12473_fu_1307_p1);

assign v5728_fu_1328_p2 = (($signed(tmp_5_fu_1319_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5730_fu_1342_p2 = (($signed(te2_fu_1334_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5732_fu_1352_p3 = ((v5730_fu_1342_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12500_fu_1348_p1);

assign v5739_fu_1369_p2 = (($signed(tmp_6_fu_1360_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5741_fu_1383_p2 = (($signed(te3_fu_1375_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5743_fu_1393_p3 = ((v5741_fu_1383_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12527_fu_1389_p1);

assign v5750_fu_1410_p2 = (($signed(tmp_7_fu_1401_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5752_fu_1424_p2 = (($signed(te4_fu_1416_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5754_fu_1434_p3 = ((v5752_fu_1424_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12554_fu_1430_p1);

assign v5761_fu_1451_p2 = (($signed(tmp_8_fu_1442_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5763_fu_1465_p2 = (($signed(te5_fu_1457_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5765_fu_1475_p3 = ((v5763_fu_1465_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12581_fu_1471_p1);

assign v5772_fu_1492_p2 = (($signed(tmp_9_fu_1483_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5774_fu_1506_p2 = (($signed(te6_fu_1498_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5776_fu_1516_p3 = ((v5774_fu_1506_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12608_fu_1512_p1);

assign v5783_fu_1533_p2 = (($signed(tmp_10_fu_1524_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign v5785_fu_1547_p2 = (($signed(te7_fu_1539_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign v5787_fu_1557_p3 = ((v5785_fu_1547_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln12635_fu_1553_p1);

assign v5987_din = {{{{{{{{v5787_reg_1784}, {v5776_reg_1779}}, {v5765_reg_1774}}, {v5754_reg_1769}}, {v5743_reg_1764}}, {v5732_reg_1759}}, {v5721_reg_1754}}, {v5710_reg_1749}};

assign wa1_fu_575_p3 = ((v5390_fu_569_p2[0:0] == 1'b1) ? v5382_fu_557_p2 : v5388_fu_563_p2);

assign zext_ln11685_fu_410_p1 = v5351_fu_406_p1;

assign zext_ln11691_fu_424_p1 = v5354_fu_414_p4;

assign zext_ln11697_fu_438_p1 = v5357_fu_428_p4;

assign zext_ln11703_fu_452_p1 = v5360_fu_442_p4;

assign zext_ln11709_fu_466_p1 = v5363_fu_456_p4;

assign zext_ln11788_fu_617_p1 = ra1_reg_1681;

assign zext_ln12264_fu_644_p1 = re_fu_636_p3;

assign zext_ln12285_fu_672_p1 = re1_fu_664_p3;

assign zext_ln12306_fu_700_p1 = re2_fu_692_p3;

assign zext_ln12327_fu_728_p1 = re3_fu_720_p3;

assign zext_ln12348_fu_756_p1 = re4_fu_748_p3;

assign zext_ln12369_fu_784_p1 = re5_fu_776_p3;

assign zext_ln12390_fu_812_p1 = re6_fu_804_p3;

assign zext_ln12421_fu_860_p1 = v5702_tmp_fu_840_p9;

assign zext_ln12656_fu_1565_p1 = wa1_reg_1676_pp0_iter6_reg;

always @ (posedge ap_clk) begin
    op3_2_reg_1668[31:6] <= 26'b00000000000000000000000000;
    op3_2_reg_1668_pp0_iter5_reg[31:6] <= 26'b00000000000000000000000000;
    op3_2_reg_1668_pp0_iter6_reg[31:6] <= 26'b00000000000000000000000000;
    op3_2_reg_1668_pp0_iter4_reg[31:6] <= 26'b00000000000000000000000000;
    v5347_fu_172[31:8] <= 24'b000000000000000000000000;
    f22_fu_176[31:12] <= 20'b00000000000000000000;
    f13_fu_180[31:12] <= 20'b00000000000000000000;
    f03_fu_184[31:12] <= 20'b00000000000000000000;
    op3_fu_188[31:6] <= 26'b00000000000000000000000000;
end

endmodule //tinytpu_isa_accu_0_Pipeline_VITIS_LOOP_11667_1
