// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_1_5 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        v6217_dout,
        v6217_num_data_valid,
        v6217_fifo_cap,
        v6217_empty_n,
        v6217_read,
        v6080_dout,
        v6080_num_data_valid,
        v6080_fifo_cap,
        v6080_empty_n,
        v6080_read,
        v6137_dout,
        v6137_num_data_valid,
        v6137_fifo_cap,
        v6137_empty_n,
        v6137_read,
        v6145_din,
        v6145_num_data_valid,
        v6145_fifo_cap,
        v6145_full_n,
        v6145_write,
        v6081_din,
        v6081_num_data_valid,
        v6081_fifo_cap,
        v6081_full_n,
        v6081_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] v6217_dout;
input  [2:0] v6217_num_data_valid;
input  [2:0] v6217_fifo_cap;
input   v6217_empty_n;
output   v6217_read;
input  [7:0] v6080_dout;
input  [3:0] v6080_num_data_valid;
input  [3:0] v6080_fifo_cap;
input   v6080_empty_n;
output   v6080_read;
input  [31:0] v6137_dout;
input  [3:0] v6137_num_data_valid;
input  [3:0] v6137_fifo_cap;
input   v6137_empty_n;
output   v6137_read;
output  [31:0] v6145_din;
input  [3:0] v6145_num_data_valid;
input  [3:0] v6145_fifo_cap;
input   v6145_full_n;
output   v6145_write;
output  [7:0] v6081_din;
input  [3:0] v6081_num_data_valid;
input  [3:0] v6081_fifo_cap;
input   v6081_full_n;
output   v6081_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg v6217_read;
reg v6080_read;
reg v6137_read;
reg v6145_write;
reg v6081_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    v6217_blk_n;
wire   [15:0] trunc_ln7139_fu_47_p1;
reg   [15:0] trunc_ln7139_reg_51;
reg    ap_block_state1;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_idle;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_ready;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6217_read;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6080_read;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6137_read;
wire   [31:0] grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6145_din;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6145_write;
wire   [7:0] grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6081_din;
wire    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6081_write;
reg    grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start_reg = 1'b0;
end

tinytpu_isa_pe_1_5_Pipeline_VITIS_LOOP_7151_1 grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start),
    .ap_done(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done),
    .ap_idle(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_idle),
    .ap_ready(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_ready),
    .v6217_dout(v6217_dout),
    .v6217_num_data_valid(3'd0),
    .v6217_fifo_cap(3'd0),
    .v6217_empty_n(v6217_empty_n),
    .v6217_read(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6217_read),
    .v6080_dout(v6080_dout),
    .v6080_num_data_valid(4'd0),
    .v6080_fifo_cap(4'd0),
    .v6080_empty_n(v6080_empty_n),
    .v6080_read(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6080_read),
    .v6137_dout(v6137_dout),
    .v6137_num_data_valid(4'd0),
    .v6137_fifo_cap(4'd0),
    .v6137_empty_n(v6137_empty_n),
    .v6137_read(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6137_read),
    .v6145_din(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6145_din),
    .v6145_num_data_valid(4'd0),
    .v6145_fifo_cap(4'd0),
    .v6145_full_n(v6145_full_n),
    .v6145_write(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6145_write),
    .v6081_din(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6081_din),
    .v6081_num_data_valid(4'd0),
    .v6081_fifo_cap(4'd0),
    .v6081_full_n(v6081_full_n),
    .v6081_write(grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6081_write),
    .empty(trunc_ln7139_reg_51)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_ready == 1'b1)) begin
            grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln7139_reg_51 <= trunc_ln7139_fu_47_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v6080_read = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6080_read;
    end else begin
        v6080_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v6081_write = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6081_write;
    end else begin
        v6081_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v6137_read = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6137_read;
    end else begin
        v6137_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v6145_write = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6145_write;
    end else begin
        v6145_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        v6217_blk_n = v6217_empty_n;
    end else begin
        v6217_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v6217_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v6217_read = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6217_read;
    end else begin
        v6217_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (v6217_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_ap_start_reg;

assign start_out = real_start;

assign trunc_ln7139_fu_47_p1 = v6217_dout[15:0];

assign v6081_din = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6081_din;

assign v6145_din = grp_pe_1_5_Pipeline_VITIS_LOOP_7151_1_fu_32_v6145_din;

endmodule //tinytpu_isa_pe_1_5
