// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_7_1_Pipeline_VITIS_LOOP_10978_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v6261_dout,
        v6261_num_data_valid,
        v6261_fifo_cap,
        v6261_empty_n,
        v6261_read,
        v6124_dout,
        v6124_num_data_valid,
        v6124_fifo_cap,
        v6124_empty_n,
        v6124_read,
        v6181_dout,
        v6181_num_data_valid,
        v6181_fifo_cap,
        v6181_empty_n,
        v6181_read,
        v6196_dout,
        v6196_num_data_valid,
        v6196_fifo_cap,
        v6196_empty_n,
        v6196_read,
        v6197_din,
        v6197_num_data_valid,
        v6197_fifo_cap,
        v6197_full_n,
        v6197_write,
        v6125_din,
        v6125_num_data_valid,
        v6125_fifo_cap,
        v6125_full_n,
        v6125_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v6261_dout;
input  [2:0] v6261_num_data_valid;
input  [2:0] v6261_fifo_cap;
input   v6261_empty_n;
output   v6261_read;
input  [7:0] v6124_dout;
input  [3:0] v6124_num_data_valid;
input  [3:0] v6124_fifo_cap;
input   v6124_empty_n;
output   v6124_read;
input  [31:0] v6181_dout;
input  [3:0] v6181_num_data_valid;
input  [3:0] v6181_fifo_cap;
input   v6181_empty_n;
output   v6181_read;
input  [255:0] v6196_dout;
input  [3:0] v6196_num_data_valid;
input  [3:0] v6196_fifo_cap;
input   v6196_empty_n;
output   v6196_read;
output  [255:0] v6197_din;
input  [3:0] v6197_num_data_valid;
input  [3:0] v6197_fifo_cap;
input   v6197_full_n;
output   v6197_write;
output  [7:0] v6125_din;
input  [3:0] v6125_num_data_valid;
input  [3:0] v6125_fifo_cap;
input   v6125_full_n;
output   v6125_write;
input  [15:0] empty;

reg ap_idle;
reg v6261_read;
reg v6124_read;
reg v6181_read;
reg v6196_read;
reg v6197_write;
reg v6125_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] v5017_reg_293;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln10978_fu_153_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v6124_blk_n;
wire    ap_block_pp0_stage0;
reg    v6181_blk_n;
reg    v6196_blk_n;
reg    v6197_blk_n;
reg    v6125_blk_n;
reg    v6261_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v5017_fu_176_p2;
reg  signed [7:0] v5024_reg_297;
reg  signed [7:0] v5024_reg_297_pp0_iter4_reg;
reg  signed [7:0] v5024_reg_297_pp0_iter5_reg;
reg   [31:0] v5025_reg_302;
reg  signed [31:0] v5025_reg_302_pp0_iter4_reg;
reg   [255:0] v5042_reg_317;
reg   [255:0] v5042_reg_317_pp0_iter4_reg;
reg   [255:0] v5042_reg_317_pp0_iter5_reg;
reg   [31:0] v5011_fu_70;
wire   [31:0] v5014_fu_170_p2;
wire    ap_loop_init;
reg   [15:0] v5010_fu_74;
wire   [15:0] v5010_2_fu_158_p2;
reg  signed [7:0] w58_fu_78;
wire   [7:0] v5020_fu_197_p1;
reg   [31:0] v5016_fu_82;
wire   [31:0] zext_ln11000_fu_211_p1;
reg   [31:0] ap_sig_allocacmp_v5016_load;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] v5022_fu_201_p4;
wire  signed [31:0] grp_fu_247_p3;
reg    grp_fu_247_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_314;
reg    ap_condition_318;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 v5011_fu_70 = 32'd0;
#0 v5010_fu_74 = 16'd0;
#0 w58_fu_78 = 8'd0;
#0 v5016_fu_82 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_mac_muladd_8s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_4_1_U1209(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v6124_dout),
    .din1(w58_fu_78),
    .din2(v5025_reg_302_pp0_iter4_reg),
    .ce(grp_fu_247_ce),
    .dout(grp_fu_247_p3)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v5010_fu_74 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln10978_fu_153_p2 == 1'd0))) begin
            v5010_fu_74 <= v5010_2_fu_158_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v5011_fu_70 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_318)) begin
            v5011_fu_70 <= v5014_fu_170_p2;
        end else if ((1'b1 == ap_condition_314)) begin
            v5011_fu_70 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
                        v5016_fu_82[0] <= 1'b0;
            v5016_fu_82[1] <= 1'b0;
            v5016_fu_82[2] <= 1'b0;
            v5016_fu_82[3] <= 1'b0;
            v5016_fu_82[4] <= 1'b0;
            v5016_fu_82[5] <= 1'b0;
            v5016_fu_82[6] <= 1'b0;
            v5016_fu_82[7] <= 1'b0;
            v5016_fu_82[8] <= 1'b0;
            v5016_fu_82[9] <= 1'b0;
            v5016_fu_82[10] <= 1'b0;
            v5016_fu_82[11] <= 1'b0;
        end else if (((v5017_reg_293 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v5016_fu_82[11 : 0] <= zext_ln11000_fu_211_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w58_fu_78 <= 8'd0;
        end else if (((v5017_reg_293 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            w58_fu_78 <= v5020_fu_197_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v5017_reg_293 <= v5017_fu_176_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        v5024_reg_297 <= v6124_dout;
        v5024_reg_297_pp0_iter4_reg <= v5024_reg_297;
        v5024_reg_297_pp0_iter5_reg <= v5024_reg_297_pp0_iter4_reg;
        v5025_reg_302 <= v6181_dout;
        v5025_reg_302_pp0_iter4_reg <= v5025_reg_302;
        v5042_reg_317 <= v6196_dout;
        v5042_reg_317_pp0_iter4_reg <= v5042_reg_317;
        v5042_reg_317_pp0_iter5_reg <= v5042_reg_317_pp0_iter4_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln10978_fu_153_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((v5017_reg_293 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_v5016_load = zext_ln11000_fu_211_p1;
    end else begin
        ap_sig_allocacmp_v5016_load = v5016_fu_82;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_247_ce = 1'b1;
    end else begin
        grp_fu_247_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6124_blk_n = v6124_empty_n;
    end else begin
        v6124_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6124_read = 1'b1;
    end else begin
        v6124_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6125_blk_n = v6125_full_n;
    end else begin
        v6125_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6125_write = 1'b1;
    end else begin
        v6125_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6181_blk_n = v6181_empty_n;
    end else begin
        v6181_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6181_read = 1'b1;
    end else begin
        v6181_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6196_blk_n = v6196_empty_n;
    end else begin
        v6196_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6196_read = 1'b1;
    end else begin
        v6196_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6197_blk_n = v6197_full_n;
    end else begin
        v6197_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6197_write = 1'b1;
    end else begin
        v6197_write = 1'b0;
    end
end

always @ (*) begin
    if (((v5017_reg_293 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6261_blk_n = v6261_empty_n;
    end else begin
        v6261_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((v5017_reg_293 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6261_read = 1'b1;
    end else begin
        v6261_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v5017_reg_293 == 1'd0) & (v6261_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((v6196_empty_n == 1'b0) | (v6181_empty_n == 1'b0) | (v6124_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((v6197_full_n == 1'b0) | (v6125_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_314 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v5017_fu_176_p2 == 1'd0) & (icmp_ln10978_fu_153_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_318 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v5017_fu_176_p2 == 1'd1) & (icmp_ln10978_fu_153_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln10978_fu_153_p2 = ((v5010_fu_74 == empty) ? 1'b1 : 1'b0);

assign v5010_2_fu_158_p2 = (v5010_fu_74 + 16'd1);

assign v5014_fu_170_p2 = (v5011_fu_70 + 32'd1);

assign v5017_fu_176_p2 = (($signed(v5014_fu_170_p2) < $signed(ap_sig_allocacmp_v5016_load)) ? 1'b1 : 1'b0);

assign v5020_fu_197_p1 = v6261_dout[7:0];

assign v5022_fu_201_p4 = {{v6261_dout[19:8]}};

assign v6125_din = v5024_reg_297_pp0_iter5_reg;

assign v6197_din = {{v5042_reg_317_pp0_iter5_reg[255:64]}, {grp_fu_247_p3}, {v5042_reg_317_pp0_iter5_reg[31:0]}};

assign zext_ln11000_fu_211_p1 = v5022_fu_201_p4;

always @ (posedge ap_clk) begin
    v5016_fu_82[31:12] <= 20'b00000000000000000000;
end

endmodule //tinytpu_isa_pe_7_1_Pipeline_VITIS_LOOP_10978_1
