// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_3_1_Pipeline_VITIS_LOOP_8195_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v6229_dout,
        v6229_num_data_valid,
        v6229_fifo_cap,
        v6229_empty_n,
        v6229_read,
        v6092_dout,
        v6092_num_data_valid,
        v6092_fifo_cap,
        v6092_empty_n,
        v6092_read,
        v6149_dout,
        v6149_num_data_valid,
        v6149_fifo_cap,
        v6149_empty_n,
        v6149_read,
        v6157_din,
        v6157_num_data_valid,
        v6157_fifo_cap,
        v6157_full_n,
        v6157_write,
        v6093_din,
        v6093_num_data_valid,
        v6093_fifo_cap,
        v6093_full_n,
        v6093_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v6229_dout;
input  [2:0] v6229_num_data_valid;
input  [2:0] v6229_fifo_cap;
input   v6229_empty_n;
output   v6229_read;
input  [7:0] v6092_dout;
input  [4:0] v6092_num_data_valid;
input  [4:0] v6092_fifo_cap;
input   v6092_empty_n;
output   v6092_read;
input  [31:0] v6149_dout;
input  [4:0] v6149_num_data_valid;
input  [4:0] v6149_fifo_cap;
input   v6149_empty_n;
output   v6149_read;
output  [31:0] v6157_din;
input  [4:0] v6157_num_data_valid;
input  [4:0] v6157_fifo_cap;
input   v6157_full_n;
output   v6157_write;
output  [7:0] v6093_din;
input  [4:0] v6093_num_data_valid;
input  [4:0] v6093_fifo_cap;
input   v6093_full_n;
output   v6093_write;
input  [15:0] empty;

reg ap_idle;
reg v6229_read;
reg v6092_read;
reg v6149_read;
reg v6157_write;
reg v6093_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] v3631_reg_266;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln8195_fu_137_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v6092_blk_n;
wire    ap_block_pp0_stage0;
reg    v6149_blk_n;
reg    v6157_blk_n;
reg    v6093_blk_n;
reg    v6229_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v3631_fu_160_p2;
reg  signed [7:0] v3638_reg_270;
reg  signed [7:0] v3638_reg_270_pp0_iter4_reg;
reg  signed [7:0] v3638_reg_270_pp0_iter5_reg;
reg   [31:0] v3639_reg_275;
reg  signed [31:0] v3639_reg_275_pp0_iter4_reg;
reg   [31:0] v3625_fu_60;
wire   [31:0] v3628_fu_154_p2;
wire    ap_loop_init;
reg   [15:0] v3624_fu_64;
wire   [15:0] v3624_2_fu_142_p2;
reg  signed [7:0] weight26_fu_68;
wire   [7:0] v3634_fu_181_p1;
reg   [31:0] v3630_fu_72;
wire   [31:0] zext_ln8217_fu_195_p1;
reg   [31:0] ap_sig_allocacmp_v3630_load;
wire  signed [31:0] grp_fu_220_p3;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] v3636_fu_185_p4;
reg    grp_fu_220_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_292;
reg    ap_condition_296;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 v3625_fu_60 = 32'd0;
#0 v3624_fu_64 = 16'd0;
#0 weight26_fu_68 = 8'd0;
#0 v3630_fu_72 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_mac_muladd_8s_8s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_8s_8s_32s_32_4_1_U827(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v6092_dout),
    .din1(weight26_fu_68),
    .din2(v3639_reg_275_pp0_iter4_reg),
    .ce(grp_fu_220_ce),
    .dout(grp_fu_220_p3)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v3624_fu_64 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln8195_fu_137_p2 == 1'd0))) begin
            v3624_fu_64 <= v3624_2_fu_142_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v3625_fu_60 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_296)) begin
            v3625_fu_60 <= v3628_fu_154_p2;
        end else if ((1'b1 == ap_condition_292)) begin
            v3625_fu_60 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
                        v3630_fu_72[0] <= 1'b0;
            v3630_fu_72[1] <= 1'b0;
            v3630_fu_72[2] <= 1'b0;
            v3630_fu_72[3] <= 1'b0;
            v3630_fu_72[4] <= 1'b0;
            v3630_fu_72[5] <= 1'b0;
            v3630_fu_72[6] <= 1'b0;
            v3630_fu_72[7] <= 1'b0;
            v3630_fu_72[8] <= 1'b0;
            v3630_fu_72[9] <= 1'b0;
            v3630_fu_72[10] <= 1'b0;
            v3630_fu_72[11] <= 1'b0;
        end else if (((v3631_reg_266 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v3630_fu_72[11 : 0] <= zext_ln8217_fu_195_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            weight26_fu_68 <= 8'd0;
        end else if (((v3631_reg_266 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            weight26_fu_68 <= v3634_fu_181_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v3631_reg_266 <= v3631_fu_160_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        v3638_reg_270 <= v6092_dout;
        v3638_reg_270_pp0_iter4_reg <= v3638_reg_270;
        v3638_reg_270_pp0_iter5_reg <= v3638_reg_270_pp0_iter4_reg;
        v3639_reg_275 <= v6149_dout;
        v3639_reg_275_pp0_iter4_reg <= v3639_reg_275;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8195_fu_137_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((v3631_reg_266 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_v3630_load = zext_ln8217_fu_195_p1;
    end else begin
        ap_sig_allocacmp_v3630_load = v3630_fu_72;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_220_ce = 1'b1;
    end else begin
        grp_fu_220_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6092_blk_n = v6092_empty_n;
    end else begin
        v6092_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6092_read = 1'b1;
    end else begin
        v6092_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6093_blk_n = v6093_full_n;
    end else begin
        v6093_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6093_write = 1'b1;
    end else begin
        v6093_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6149_blk_n = v6149_empty_n;
    end else begin
        v6149_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6149_read = 1'b1;
    end else begin
        v6149_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6157_blk_n = v6157_full_n;
    end else begin
        v6157_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6157_write = 1'b1;
    end else begin
        v6157_write = 1'b0;
    end
end

always @ (*) begin
    if (((v3631_reg_266 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v6229_blk_n = v6229_empty_n;
    end else begin
        v6229_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((v3631_reg_266 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v6229_read = 1'b1;
    end else begin
        v6229_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v3631_reg_266 == 1'd0) & (v6229_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((v6149_empty_n == 1'b0) | (v6092_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((v6093_full_n == 1'b0) | (v6157_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_292 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v3631_fu_160_p2 == 1'd0) & (icmp_ln8195_fu_137_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_296 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v3631_fu_160_p2 == 1'd1) & (icmp_ln8195_fu_137_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln8195_fu_137_p2 = ((v3624_fu_64 == empty) ? 1'b1 : 1'b0);

assign v3624_2_fu_142_p2 = (v3624_fu_64 + 16'd1);

assign v3628_fu_154_p2 = (v3625_fu_60 + 32'd1);

assign v3631_fu_160_p2 = (($signed(v3628_fu_154_p2) < $signed(ap_sig_allocacmp_v3630_load)) ? 1'b1 : 1'b0);

assign v3634_fu_181_p1 = v6229_dout[7:0];

assign v3636_fu_185_p4 = {{v6229_dout[19:8]}};

assign v6093_din = v3638_reg_270_pp0_iter5_reg;

assign v6157_din = grp_fu_220_p3;

assign zext_ln8217_fu_195_p1 = v3636_fu_185_p4;

always @ (posedge ap_clk) begin
    v3630_fu_72[31:12] <= 20'b00000000000000000000;
end

endmodule //tinytpu_isa_pe_3_1_Pipeline_VITIS_LOOP_8195_1
