// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_0_0_Pipeline_VITIS_LOOP_6042_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v6204_dout,
        v6204_num_data_valid,
        v6204_fifo_cap,
        v6204_empty_n,
        v6204_read,
        v6060_dout,
        v6060_num_data_valid,
        v6060_fifo_cap,
        v6060_empty_n,
        v6060_read,
        v6061_din,
        v6061_num_data_valid,
        v6061_fifo_cap,
        v6061_full_n,
        v6061_write,
        v6132_din,
        v6132_num_data_valid,
        v6132_fifo_cap,
        v6132_full_n,
        v6132_write,
        v6068_din,
        v6068_num_data_valid,
        v6068_fifo_cap,
        v6068_full_n,
        v6068_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v6204_dout;
input  [2:0] v6204_num_data_valid;
input  [2:0] v6204_fifo_cap;
input   v6204_empty_n;
output   v6204_read;
input  [63:0] v6060_dout;
input  [3:0] v6060_num_data_valid;
input  [3:0] v6060_fifo_cap;
input   v6060_empty_n;
output   v6060_read;
output  [63:0] v6061_din;
input  [3:0] v6061_num_data_valid;
input  [3:0] v6061_fifo_cap;
input   v6061_full_n;
output   v6061_write;
output  [31:0] v6132_din;
input  [3:0] v6132_num_data_valid;
input  [3:0] v6132_fifo_cap;
input   v6132_full_n;
output   v6132_write;
output  [7:0] v6068_din;
input  [3:0] v6068_num_data_valid;
input  [3:0] v6068_fifo_cap;
input   v6068_full_n;
output   v6068_write;
input  [15:0] empty;

reg ap_idle;
reg v6204_read;
reg v6060_read;
reg v6061_write;
reg v6132_write;
reg v6068_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] v2562_reg_274;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln6042_fu_140_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v6060_blk_n;
wire    ap_block_pp0_stage0;
reg    v6061_blk_n;
reg    v6132_blk_n;
reg    v6068_blk_n;
reg    v6204_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v2562_fu_163_p2;
reg   [63:0] v2569_reg_278;
reg   [63:0] v2569_reg_278_pp0_iter3_reg;
wire  signed [7:0] v2572_fu_212_p1;
reg  signed [7:0] v2572_reg_283;
reg  signed [7:0] v2572_reg_283_pp0_iter3_reg;
wire   [15:0] v2582_fu_226_p2;
reg   [15:0] v2582_reg_289;
reg   [31:0] v2556_fu_62;
wire   [31:0] v2559_fu_157_p2;
wire    ap_loop_init;
reg   [15:0] v2555_fu_66;
wire   [15:0] v2555_2_fu_145_p2;
reg  signed [7:0] w_fu_70;
wire   [7:0] v2565_fu_184_p1;
reg   [31:0] v2561_fu_74;
wire   [31:0] zext_ln6064_fu_198_p1;
reg   [31:0] ap_sig_allocacmp_v2561_load;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] v2567_fu_188_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_272;
reg    ap_condition_275;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 v2556_fu_62 = 32'd0;
#0 v2555_fu_66 = 16'd0;
#0 w_fu_70 = 8'd0;
#0 v2561_fu_74 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U539(
    .din0(v2572_reg_283),
    .din1(w_fu_70),
    .dout(v2582_fu_226_p2)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v2555_fu_66 <= 16'd0;
        end else if (((icmp_ln6042_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            v2555_fu_66 <= v2555_2_fu_145_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v2556_fu_62 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_275)) begin
            v2556_fu_62 <= v2559_fu_157_p2;
        end else if ((1'b1 == ap_condition_272)) begin
            v2556_fu_62 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
                        v2561_fu_74[0] <= 1'b0;
            v2561_fu_74[1] <= 1'b0;
            v2561_fu_74[2] <= 1'b0;
            v2561_fu_74[3] <= 1'b0;
            v2561_fu_74[4] <= 1'b0;
            v2561_fu_74[5] <= 1'b0;
            v2561_fu_74[6] <= 1'b0;
            v2561_fu_74[7] <= 1'b0;
            v2561_fu_74[8] <= 1'b0;
            v2561_fu_74[9] <= 1'b0;
            v2561_fu_74[10] <= 1'b0;
            v2561_fu_74[11] <= 1'b0;
        end else if (((v2562_reg_274 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v2561_fu_74[11 : 0] <= zext_ln6064_fu_198_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            w_fu_70 <= 8'd0;
        end else if (((v2562_reg_274 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            w_fu_70 <= v2565_fu_184_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v2562_reg_274 <= v2562_fu_163_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        v2569_reg_278 <= v6060_dout;
        v2569_reg_278_pp0_iter3_reg <= v2569_reg_278;
        v2572_reg_283 <= v2572_fu_212_p1;
        v2572_reg_283_pp0_iter3_reg <= v2572_reg_283;
        v2582_reg_289 <= v2582_fu_226_p2;
    end
end

always @ (*) begin
    if (((icmp_ln6042_fu_140_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v2562_reg_274 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_v2561_load = zext_ln6064_fu_198_p1;
    end else begin
        ap_sig_allocacmp_v2561_load = v2561_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6060_blk_n = v6060_empty_n;
    end else begin
        v6060_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6060_read = 1'b1;
    end else begin
        v6060_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6061_blk_n = v6061_full_n;
    end else begin
        v6061_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6061_write = 1'b1;
    end else begin
        v6061_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6068_blk_n = v6068_full_n;
    end else begin
        v6068_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6068_write = 1'b1;
    end else begin
        v6068_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6132_blk_n = v6132_full_n;
    end else begin
        v6132_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v6132_write = 1'b1;
    end else begin
        v6132_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v2562_reg_274 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6204_blk_n = v6204_empty_n;
    end else begin
        v6204_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (v2562_reg_274 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v6204_read = 1'b1;
    end else begin
        v6204_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v6060_empty_n == 1'b0) | ((v2562_reg_274 == 1'd0) & (v6204_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((v6068_full_n == 1'b0) | (v6132_full_n == 1'b0) | (v6061_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_272 = ((icmp_ln6042_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (v2562_fu_163_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_275 = ((icmp_ln6042_fu_140_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (v2562_fu_163_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln6042_fu_140_p2 = ((v2555_fu_66 == empty) ? 1'b1 : 1'b0);

assign v2555_2_fu_145_p2 = (v2555_fu_66 + 16'd1);

assign v2559_fu_157_p2 = (v2556_fu_62 + 32'd1);

assign v2562_fu_163_p2 = (($signed(v2559_fu_157_p2) < $signed(ap_sig_allocacmp_v2561_load)) ? 1'b1 : 1'b0);

assign v2565_fu_184_p1 = v6204_dout[7:0];

assign v2567_fu_188_p4 = {{v6204_dout[19:8]}};

assign v2572_fu_212_p1 = v6060_dout[7:0];

assign v6061_din = v2569_reg_278_pp0_iter3_reg;

assign v6068_din = v2572_reg_283_pp0_iter3_reg;

assign v6132_din = $signed(v2582_reg_289);

assign zext_ln6064_fu_198_p1 = v2567_fu_188_p4;

always @ (posedge ap_clk) begin
    v2561_fu_74[31:12] <= 20'b00000000000000000000;
end

endmodule //tinytpu_isa_pe_0_0_Pipeline_VITIS_LOOP_6042_1
