// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_1010_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v5980_dout,
        v5980_num_data_valid,
        v5980_fifo_cap,
        v5980_empty_n,
        v5980_read,
        v5984_dout,
        v5984_num_data_valid,
        v5984_fifo_cap,
        v5984_empty_n,
        v5984_read,
        v5986_din,
        v5986_num_data_valid,
        v5986_fifo_cap,
        v5986_full_n,
        v5986_write,
        v5988_din,
        v5988_num_data_valid,
        v5988_fifo_cap,
        v5988_full_n,
        v5988_write,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] v5980_dout;
input  [3:0] v5980_num_data_valid;
input  [3:0] v5980_fifo_cap;
input   v5980_empty_n;
output   v5980_read;
input  [63:0] v5984_dout;
input  [3:0] v5984_num_data_valid;
input  [3:0] v5984_fifo_cap;
input   v5984_empty_n;
output   v5984_read;
output  [63:0] v5986_din;
input  [3:0] v5986_num_data_valid;
input  [3:0] v5986_fifo_cap;
input   v5986_full_n;
output   v5986_write;
output  [63:0] v5988_din;
input  [3:0] v5988_num_data_valid;
input  [3:0] v5988_fifo_cap;
input   v5988_full_n;
output   v5988_write;
input  [15:0] empty;

reg ap_idle;
reg v5980_read;
reg v5984_read;
reg v5986_write;
reg v5988_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] v552_reg_457;
reg    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] v586_reg_479;
reg    ap_block_state5_pp0_stage0_iter4;
reg   [0:0] v586_reg_479_pp0_iter4_reg;
reg   [0:0] v598_reg_483;
reg   [0:0] v598_reg_483_pp0_iter4_reg;
reg    ap_predicate_op89_write_state6;
reg    ap_block_state6_pp0_stage0_iter5;
reg   [0:0] v586_reg_479_pp0_iter5_reg;
reg   [0:0] v598_reg_483_pp0_iter5_reg;
reg    ap_predicate_op93_write_state7;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1010_fu_184_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v5984_blk_n;
wire    ap_block_pp0_stage0;
reg    v5980_blk_n;
reg    v5986_blk_n;
reg    v5988_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v552_fu_207_p2;
wire   [8:0] trunc_ln1049_2_fu_301_p1;
reg   [8:0] trunc_ln1049_2_reg_461;
wire   [0:0] v583_fu_305_p2;
reg   [0:0] v583_reg_468;
reg   [0:0] v583_reg_468_pp0_iter3_reg;
reg   [0:0] v583_reg_468_pp0_iter4_reg;
reg   [0:0] v583_reg_468_pp0_iter5_reg;
wire   [8:0] ra_fu_357_p3;
reg   [8:0] ra_reg_474;
wire   [0:0] v586_fu_365_p2;
wire   [0:0] v598_fu_371_p2;
wire   [11:0] v604_fu_377_p1;
reg   [11:0] v604_reg_487;
reg   [11:0] v604_reg_487_pp0_iter4_reg;
reg   [11:0] v604_reg_487_pp0_iter5_reg;
wire   [8:0] v593_fu_381_p2;
reg   [8:0] v593_reg_492;
wire   [63:0] spad_q0;
reg   [63:0] v599_reg_502;
reg   [8:0] spad_address0;
reg    spad_ce0;
reg    spad_we0;
wire   [63:0] zext_ln1090_fu_386_p1;
wire   [63:0] zext_ln1086_fu_390_p1;
reg   [31:0] v546_fu_70;
wire   [31:0] v549_fu_201_p2;
wire    ap_loop_init;
reg   [15:0] v545_fu_74;
wire   [15:0] v545_2_fu_189_p2;
reg   [31:0] op1_fu_78;
wire   [31:0] zext_ln1027_fu_232_p1;
reg   [31:0] f12_fu_82;
wire   [31:0] zext_ln1033_fu_246_p1;
reg   [31:0] f31_fu_86;
wire   [31:0] zext_ln1039_fu_260_p1;
reg   [31:0] v551_fu_90;
wire   [31:0] zext_ln1045_fu_274_p1;
reg   [31:0] ap_sig_allocacmp_v551_load;
reg    ap_block_pp0_stage0_01001;
wire   [5:0] v555_fu_228_p1;
wire   [11:0] v558_fu_236_p4;
wire   [11:0] v561_fu_250_p4;
wire   [7:0] v564_fu_264_p4;
wire   [8:0] trunc_ln1049_1_fu_324_p1;
wire   [8:0] add_ln1067_fu_339_p2;
wire   [8:0] trunc_ln1049_fu_320_p1;
wire   [8:0] v581_fu_344_p2;
wire   [0:0] v573_fu_333_p2;
wire   [8:0] ra_3_fu_350_p3;
wire   [8:0] v571_fu_328_p2;
wire   [63:0] zext_ln1112_fu_394_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_453;
reg    ap_condition_457;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 v546_fu_70 = 32'd0;
#0 v545_fu_74 = 16'd0;
#0 op1_fu_78 = 32'd0;
#0 f12_fu_82 = 32'd0;
#0 f31_fu_86 = 32'd0;
#0 v551_fu_90 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_1010_1_spad_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
spad_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(spad_address0),
    .ce0(spad_ce0),
    .we0(spad_we0),
    .d0(v5984_dout),
    .q0(spad_q0)
);

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f12_fu_82[0] <= 1'b0;
            f12_fu_82[1] <= 1'b0;
            f12_fu_82[2] <= 1'b0;
            f12_fu_82[3] <= 1'b0;
            f12_fu_82[4] <= 1'b0;
            f12_fu_82[5] <= 1'b0;
            f12_fu_82[6] <= 1'b0;
            f12_fu_82[7] <= 1'b0;
            f12_fu_82[8] <= 1'b0;
            f12_fu_82[9] <= 1'b0;
            f12_fu_82[10] <= 1'b0;
            f12_fu_82[11] <= 1'b0;
        end else if (((v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        f12_fu_82[11 : 0] <= zext_ln1033_fu_246_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f31_fu_86[0] <= 1'b0;
            f31_fu_86[1] <= 1'b0;
            f31_fu_86[2] <= 1'b0;
            f31_fu_86[3] <= 1'b0;
            f31_fu_86[4] <= 1'b0;
            f31_fu_86[5] <= 1'b0;
            f31_fu_86[6] <= 1'b0;
            f31_fu_86[7] <= 1'b0;
            f31_fu_86[8] <= 1'b0;
            f31_fu_86[9] <= 1'b0;
            f31_fu_86[10] <= 1'b0;
            f31_fu_86[11] <= 1'b0;
        end else if (((v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        f31_fu_86[11 : 0] <= zext_ln1039_fu_260_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        op1_fu_78[0] <= 1'b0;
            op1_fu_78[1] <= 1'b0;
            op1_fu_78[2] <= 1'b0;
            op1_fu_78[3] <= 1'b0;
            op1_fu_78[4] <= 1'b0;
            op1_fu_78[5] <= 1'b0;
        end else if (((v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        op1_fu_78[5 : 0] <= zext_ln1027_fu_232_p1[5 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v545_fu_74 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1010_fu_184_p2 == 1'd0))) begin
            v545_fu_74 <= v545_2_fu_189_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v546_fu_70 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_457)) begin
            v546_fu_70 <= v549_fu_201_p2;
        end else if ((1'b1 == ap_condition_453)) begin
            v546_fu_70 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        v551_fu_90[0] <= 1'b0;
            v551_fu_90[1] <= 1'b0;
            v551_fu_90[2] <= 1'b0;
            v551_fu_90[3] <= 1'b0;
            v551_fu_90[4] <= 1'b0;
            v551_fu_90[5] <= 1'b0;
            v551_fu_90[6] <= 1'b0;
            v551_fu_90[7] <= 1'b0;
        end else if (((v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v551_fu_90[7 : 0] <= zext_ln1045_fu_274_p1[7 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v552_reg_457 <= v552_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ra_reg_474 <= ra_fu_357_p3;
        trunc_ln1049_2_reg_461 <= trunc_ln1049_2_fu_301_p1;
        v583_reg_468 <= v583_fu_305_p2;
        v583_reg_468_pp0_iter3_reg <= v583_reg_468;
        v583_reg_468_pp0_iter4_reg <= v583_reg_468_pp0_iter3_reg;
        v583_reg_468_pp0_iter5_reg <= v583_reg_468_pp0_iter4_reg;
        v586_reg_479 <= v586_fu_365_p2;
        v586_reg_479_pp0_iter4_reg <= v586_reg_479;
        v586_reg_479_pp0_iter5_reg <= v586_reg_479_pp0_iter4_reg;
        v593_reg_492 <= v593_fu_381_p2;
        v598_reg_483 <= v598_fu_371_p2;
        v598_reg_483_pp0_iter4_reg <= v598_reg_483;
        v598_reg_483_pp0_iter5_reg <= v598_reg_483_pp0_iter4_reg;
        v604_reg_487 <= v604_fu_377_p1;
        v604_reg_487_pp0_iter4_reg <= v604_reg_487;
        v604_reg_487_pp0_iter5_reg <= v604_reg_487_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        v599_reg_502 <= spad_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1010_fu_184_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_v551_load = zext_ln1045_fu_274_p1;
    end else begin
        ap_sig_allocacmp_v551_load = v551_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((v586_reg_479 == 1'd1)) begin
            spad_address0 = zext_ln1086_fu_390_p1;
        end else if ((v586_reg_479 == 1'd0)) begin
            spad_address0 = zext_ln1090_fu_386_p1;
        end else begin
            spad_address0 = 'bx;
        end
    end else begin
        spad_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (v586_reg_479 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (v586_reg_479 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        spad_ce0 = 1'b1;
    end else begin
        spad_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (v586_reg_479 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        spad_we0 = 1'b1;
    end else begin
        spad_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v5980_blk_n = v5980_empty_n;
    end else begin
        v5980_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (v552_reg_457 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v5980_read = 1'b1;
    end else begin
        v5980_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (v586_reg_479 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5984_blk_n = v5984_empty_n;
    end else begin
        v5984_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (v586_reg_479 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        v5984_read = 1'b1;
    end else begin
        v5984_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op89_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        v5986_blk_n = v5986_full_n;
    end else begin
        v5986_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op89_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        v5986_write = 1'b1;
    end else begin
        v5986_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op93_write_state7 == 1'b1))) begin
        v5988_blk_n = v5988_full_n;
    end else begin
        v5988_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (ap_predicate_op93_write_state7 == 1'b1))) begin
        v5988_write = 1'b1;
    end else begin
        v5988_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1067_fu_339_p2 = ($signed(trunc_ln1049_2_reg_461) + $signed(9'd511));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v552_reg_457 == 1'd0) & (v5980_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((v586_reg_479 == 1'd1) & (v5984_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((ap_predicate_op89_write_state6 == 1'b1) & (v5986_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((ap_predicate_op93_write_state7 == 1'b1) & (v5988_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_453 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v552_fu_207_p2 == 1'd0) & (icmp_ln1010_fu_184_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_457 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v552_fu_207_p2 == 1'd1) & (icmp_ln1010_fu_184_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op89_write_state6 = ((v598_reg_483_pp0_iter4_reg == 1'd1) & (v586_reg_479_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op93_write_state7 = ((v598_reg_483_pp0_iter5_reg == 1'd0) & (v586_reg_479_pp0_iter5_reg == 1'd0));
end

assign icmp_ln1010_fu_184_p2 = ((v545_fu_74 == empty) ? 1'b1 : 1'b0);

assign ra_3_fu_350_p3 = ((v583_reg_468[0:0] == 1'b1) ? trunc_ln1049_fu_320_p1 : v581_fu_344_p2);

assign ra_fu_357_p3 = ((v573_fu_333_p2[0:0] == 1'b1) ? ra_3_fu_350_p3 : v571_fu_328_p2);

assign trunc_ln1049_1_fu_324_p1 = f12_fu_82[8:0];

assign trunc_ln1049_2_fu_301_p1 = v546_fu_70[8:0];

assign trunc_ln1049_fu_320_p1 = f31_fu_86[8:0];

assign v545_2_fu_189_p2 = (v545_fu_74 + 16'd1);

assign v549_fu_201_p2 = (v546_fu_70 + 32'd1);

assign v552_fu_207_p2 = (($signed(v549_fu_201_p2) < $signed(ap_sig_allocacmp_v551_load)) ? 1'b1 : 1'b0);

assign v555_fu_228_p1 = v5980_dout[5:0];

assign v558_fu_236_p4 = {{v5980_dout[29:18]}};

assign v561_fu_250_p4 = {{v5980_dout[53:42]}};

assign v564_fu_264_p4 = {{v5980_dout[61:54]}};

assign v571_fu_328_p2 = (trunc_ln1049_2_reg_461 + trunc_ln1049_1_fu_324_p1);

assign v573_fu_333_p2 = ((op1_fu_78 == 32'd4) ? 1'b1 : 1'b0);

assign v581_fu_344_p2 = (add_ln1067_fu_339_p2 + trunc_ln1049_fu_320_p1);

assign v583_fu_305_p2 = ((v546_fu_70 == 32'd0) ? 1'b1 : 1'b0);

assign v586_fu_365_p2 = ((op1_fu_78 == 32'd1) ? 1'b1 : 1'b0);

assign v593_fu_381_p2 = (trunc_ln1049_2_reg_461 + trunc_ln1049_fu_320_p1);

assign v5986_din = spad_q0;

assign v5988_din = ((v583_reg_468_pp0_iter5_reg[0:0] == 1'b1) ? zext_ln1112_fu_394_p1 : v599_reg_502);

assign v598_fu_371_p2 = ((op1_fu_78 == 32'd3) ? 1'b1 : 1'b0);

assign v604_fu_377_p1 = f12_fu_82[11:0];

assign zext_ln1027_fu_232_p1 = v555_fu_228_p1;

assign zext_ln1033_fu_246_p1 = v558_fu_236_p4;

assign zext_ln1039_fu_260_p1 = v561_fu_250_p4;

assign zext_ln1045_fu_274_p1 = v564_fu_264_p4;

assign zext_ln1086_fu_390_p1 = v593_reg_492;

assign zext_ln1090_fu_386_p1 = ra_reg_474;

assign zext_ln1112_fu_394_p1 = v604_reg_487_pp0_iter5_reg;

always @ (posedge ap_clk) begin
    op1_fu_78[31:6] <= 26'b00000000000000000000000000;
    f12_fu_82[31:12] <= 20'b00000000000000000000;
    f31_fu_86[31:12] <= 20'b00000000000000000000;
    v551_fu_90[31:8] <= 24'b000000000000000000000000;
end

endmodule //tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_1010_1
