// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_accu_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        v5982_dout,
        v5982_num_data_valid,
        v5982_fifo_cap,
        v5982_empty_n,
        v5982_read,
        v6203_dout,
        v6203_num_data_valid,
        v6203_fifo_cap,
        v6203_empty_n,
        v6203_read,
        v5987_din,
        v5987_num_data_valid,
        v5987_fifo_cap,
        v5987_full_n,
        v5987_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] v5982_dout;
input  [4:0] v5982_num_data_valid;
input  [4:0] v5982_fifo_cap;
input   v5982_empty_n;
output   v5982_read;
input  [255:0] v6203_dout;
input  [4:0] v6203_num_data_valid;
input  [4:0] v6203_fifo_cap;
input   v6203_empty_n;
output   v6203_read;
output  [63:0] v5987_din;
input  [4:0] v5987_num_data_valid;
input  [4:0] v5987_fifo_cap;
input   v5987_full_n;
output   v5987_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg v5982_read;
reg v6203_read;
reg v5987_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    v5982_blk_n;
wire   [15:0] v5337_fu_39_p1;
reg   [15:0] v5337_reg_43;
reg    ap_block_state1;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_idle;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_ready;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5982_read;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v6203_read;
wire   [63:0] grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5987_din;
wire    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5987_write;
reg    grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start_reg = 1'b0;
end

tinytpu_isa_accu_0_Pipeline_VITIS_LOOP_11667_1 grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start),
    .ap_done(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done),
    .ap_idle(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_idle),
    .ap_ready(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_ready),
    .v5982_dout(v5982_dout),
    .v5982_num_data_valid(5'd0),
    .v5982_fifo_cap(5'd0),
    .v5982_empty_n(v5982_empty_n),
    .v5982_read(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5982_read),
    .v6203_dout(v6203_dout),
    .v6203_num_data_valid(5'd0),
    .v6203_fifo_cap(5'd0),
    .v6203_empty_n(v6203_empty_n),
    .v6203_read(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v6203_read),
    .v5987_din(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5987_din),
    .v5987_num_data_valid(5'd0),
    .v5987_fifo_cap(5'd0),
    .v5987_full_n(v5987_full_n),
    .v5987_write(grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5987_write),
    .empty(v5337_reg_43)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start_reg <= 1'b1;
        end else if ((grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_ready == 1'b1)) begin
            grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v5337_reg_43 <= v5337_fu_39_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        v5982_blk_n = v5982_empty_n;
    end else begin
        v5982_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v5982_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v5982_read = grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5982_read;
    end else begin
        v5982_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v5987_write = grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5987_write;
    end else begin
        v5987_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v6203_read = grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v6203_read;
    end else begin
        v6203_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (v5982_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start = grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_ap_start_reg;

assign v5337_fu_39_p1 = v5982_dout[15:0];

assign v5987_din = grp_accu_0_Pipeline_VITIS_LOOP_11667_1_fu_28_v5987_din;

endmodule //tinytpu_isa_accu_0
