// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_spm_0 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        v5980_dout,
        v5980_num_data_valid,
        v5980_fifo_cap,
        v5980_empty_n,
        v5980_read,
        v5988_din,
        v5988_num_data_valid,
        v5988_fifo_cap,
        v5988_full_n,
        v5988_write,
        v5984_dout,
        v5984_num_data_valid,
        v5984_fifo_cap,
        v5984_empty_n,
        v5984_read,
        v5986_din,
        v5986_num_data_valid,
        v5986_fifo_cap,
        v5986_full_n,
        v5986_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] v5980_dout;
input  [3:0] v5980_num_data_valid;
input  [3:0] v5980_fifo_cap;
input   v5980_empty_n;
output   v5980_read;
output  [63:0] v5988_din;
input  [3:0] v5988_num_data_valid;
input  [3:0] v5988_fifo_cap;
input   v5988_full_n;
output   v5988_write;
input  [63:0] v5984_dout;
input  [3:0] v5984_num_data_valid;
input  [3:0] v5984_fifo_cap;
input   v5984_empty_n;
output   v5984_read;
output  [63:0] v5986_din;
input  [3:0] v5986_num_data_valid;
input  [3:0] v5986_fifo_cap;
input   v5986_full_n;
output   v5986_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg v5980_read;
reg[63:0] v5988_din;
reg v5988_write;
reg v5984_read;
reg v5986_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    v5980_blk_n;
wire    ap_CS_fsm_state2;
reg    v5988_blk_n;
wire   [15:0] v535_fu_52_p1;
reg   [15:0] v535_reg_65;
reg    ap_block_state1;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_idle;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_ready;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5980_read;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5984_read;
wire   [63:0] grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5986_din;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5986_write;
wire   [63:0] grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_din;
wire    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_write;
reg    grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_block_state2;
wire   [63:0] zext_ln993_fu_60_p1;
wire   [31:0] v541_tmp_fu_56_p1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start_reg = 1'b0;
end

tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_1010_1 grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start),
    .ap_done(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done),
    .ap_idle(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_idle),
    .ap_ready(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_ready),
    .v5980_dout(v5980_dout),
    .v5980_num_data_valid(4'd0),
    .v5980_fifo_cap(4'd0),
    .v5980_empty_n(v5980_empty_n),
    .v5980_read(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5980_read),
    .v5984_dout(v5984_dout),
    .v5984_num_data_valid(4'd0),
    .v5984_fifo_cap(4'd0),
    .v5984_empty_n(v5984_empty_n),
    .v5984_read(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5984_read),
    .v5986_din(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5986_din),
    .v5986_num_data_valid(4'd0),
    .v5986_fifo_cap(4'd0),
    .v5986_full_n(v5986_full_n),
    .v5986_write(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5986_write),
    .v5988_din(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_din),
    .v5988_num_data_valid(4'd0),
    .v5988_fifo_cap(4'd0),
    .v5988_full_n(v5988_full_n),
    .v5988_write(grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_write),
    .empty(v535_reg_65)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_NS_fsm_state3))) begin
            grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start_reg <= 1'b1;
        end else if ((grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_ready == 1'b1)) begin
            grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v535_reg_65 <= v535_fu_52_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        v5980_blk_n = v5980_empty_n;
    end else begin
        v5980_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)))) begin
        v5980_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v5980_read = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5980_read;
    end else begin
        v5980_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v5984_read = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5984_read;
    end else begin
        v5984_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v5986_write = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5986_write;
    end else begin
        v5986_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        v5988_blk_n = v5988_full_n;
    end else begin
        v5988_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        v5988_din = zext_ln993_fu_60_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v5988_din = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_din;
    end else begin
        v5988_din = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        v5988_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v5988_write = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5988_write;
    end else begin
        v5988_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((v5980_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((v5988_full_n == 1'b0) | (v5980_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_ap_start_reg;

assign start_out = real_start;

assign v535_fu_52_p1 = v5980_dout[15:0];

assign v541_tmp_fu_56_p1 = v5980_dout[31:0];

assign v5986_din = grp_spm_0_Pipeline_VITIS_LOOP_1010_1_fu_39_v5986_din;

assign zext_ln993_fu_60_p1 = v541_tmp_fu_56_p1;

endmodule //tinytpu_isa_spm_0
