# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Typing stubs for arithmetic, comparison and logical operators.

Each operator accepts scalar or shaped Allo values (and constexpr literals) and
an optional ``acc`` accumulator; everything is typed ``Any`` because operand and
result dtypes are resolved by the compiler, not by the Python type checker.
"""
from typing import Any

__all__ = [
    "add",
    "sub",
    "mul",
    "div",
    "floordiv",
    "mod",
    "pow",
    "lshift",
    "rshift",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "eq",
    "ne",
    "lt",
    "le",
    "gt",
    "ge",
    "pos",
    "neg",
    "invert",
    "logical_and",
    "logical_or",
    "logical_not",
    "max",
    "min",
    "cast",
    "bitcast",
]

def add(x: Any, y: Any, acc: Any = ...) -> Any: ...
def sub(x: Any, y: Any, acc: Any = ...) -> Any: ...
def mul(x: Any, y: Any, acc: Any = ...) -> Any: ...
def div(x: Any, y: Any, acc: Any = ...) -> Any: ...
def floordiv(x: Any, y: Any, acc: Any = ...) -> Any: ...
def mod(x: Any, y: Any, acc: Any = ...) -> Any: ...
def pow(x: Any, y: Any, acc: Any = ...) -> Any: ...
def lshift(x: Any, y: Any, acc: Any = ...) -> Any: ...
def rshift(x: Any, y: Any, acc: Any = ...) -> Any: ...
def bitwise_and(x: Any, y: Any, acc: Any = ...) -> Any: ...
def bitwise_or(x: Any, y: Any, acc: Any = ...) -> Any: ...
def bitwise_xor(x: Any, y: Any, acc: Any = ...) -> Any: ...
def eq(x: Any, y: Any, acc: Any = ..., ordered: Any = ...) -> Any: ...
def ne(x: Any, y: Any, acc: Any = ..., ordered: Any = ...) -> Any: ...
def lt(x: Any, y: Any, acc: Any = ..., ordered: Any = ...) -> Any: ...
def le(x: Any, y: Any, acc: Any = ..., ordered: Any = ...) -> Any: ...
def gt(x: Any, y: Any, acc: Any = ..., ordered: Any = ...) -> Any: ...
def ge(x: Any, y: Any, acc: Any = ..., ordered: Any = ...) -> Any: ...
def pos(x: Any, acc: Any = ...) -> Any: ...
def neg(x: Any, acc: Any = ...) -> Any: ...
def invert(x: Any, acc: Any = ...) -> Any: ...
def logical_and(x: Any, y: Any, acc: Any = ...) -> Any: ...
def logical_or(x: Any, y: Any, acc: Any = ...) -> Any: ...
def logical_not(x: Any, acc: Any = ...) -> Any: ...
def max(x: Any, y: Any, acc: Any = ..., propagate_nan: Any = ...) -> Any: ...
def min(x: Any, y: Any, acc: Any = ..., propagate_nan: Any = ...) -> Any: ...
def cast(x: Any, dst_type: Any) -> Any: ...
def bitcast(x: Any, dst_type: Any) -> Any: ...
