# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Drive one MiniTPU ``.sv`` unit in Verilator with a stimulus array.

A unit is driven through a generated C++ wrapper, built once per unit and
cached by the hash of its sources and its port spec. Stimulus goes in, and
outputs come back, as raw little-endian ``uint64`` files, so a million vectors
cost one process launch.

Three port shapes cover U1:

``comb``
    No clock. Set the inputs, ``eval()``, read the outputs.
``valid``
    ``clk``, active-low reset, ``valid_i`` in and ``valid_o`` out. One vector
    is offered per cycle (II=1). For each output the wrapper records the cycle
    on which it appeared, so the harness measures the latency rather than
    assuming it.
``bare``
    ``clk`` and no valid. Outputs are sampled ``latency`` cycles after their
    inputs, so the declared latency is an input here, not a measurement.

MiniTPU's own ``tb/`` stays the second check (D-7); this is the first.
"""

import hashlib
import os
import shutil
import subprocess
from dataclasses import dataclass, field

import numpy as np


def minitpu_home():
    """The pinned MiniTPU clone: ``$MINITPU_HOME``, else the known places."""
    for p in (
        os.environ.get("MINITPU_HOME"),
        "/work/shared/users/phd/sk3463/minitpu",  # zhang-21 (README D-8)
        os.path.expanduser("~/core/minitpu"),  # ace-01
    ):
        if p and os.path.isdir(p):
            return p
    raise RuntimeError("Set MINITPU_HOME to a MiniTPU clone at b3ba0a4d.")


def _cxx():
    """A g++ new enough for Verilator 5's runtime headers.

    RHEL 8's g++ 8.5 is too old; gcc-toolset-13 is used when present.
    """
    if os.environ.get("CXX"):
        return os.environ["CXX"]
    gts = "/opt/rh/gcc-toolset-13/root/usr/bin/g++"
    return gts if os.path.exists(gts) else "g++"


@dataclass
class RtlUnit:
    top: str
    sources: list  # paths relative to the MiniTPU clone
    inputs: list  # [(port, width)], data ports only
    outputs: list  # [(port, width)]
    shape: str = "comb"  # comb | valid | bare
    latency: int = 0  # declared; sampled at this depth for "bare"
    clk: str = "clk_i"
    rst_n: str = "rst_ni"
    valid_in: str = "valid_i"
    valid_out: str = "valid_o"
    defines: list = field(default_factory=list)

    def key(self, home):
        h = hashlib.sha256(repr(self).encode())
        for s in self.sources:
            with open(os.path.join(home, s), "rb") as f:
                h.update(f.read())
        h.update(WRAPPER_VERSION.encode())
        return h.hexdigest()[:16]


WRAPPER_VERSION = "1"


def _wrapper(u):
    """The C++ driver for one unit."""
    ni, no = len(u.inputs), len(u.outputs)
    set_in = "\n".join(
        f"    dut.{p} = (decltype(dut.{p}))in[k * {ni} + {i}];"
        for i, (p, _) in enumerate(u.inputs)
    )
    get_out = "\n".join(
        f"      out[j * {no + 1} + {i}] = (uint64_t)dut.{p};"
        for i, (p, _) in enumerate(u.outputs)
    )
    zero_in = "\n".join(f"    dut.{p} = 0;" for p, _ in u.inputs)
    if u.shape == "comb":
        body = f"""
  for (uint64_t k = 0; k < n; ++k) {{
{set_in}
    dut.eval();
    {{ uint64_t j = k;
{get_out}
      out[j * {no + 1} + {no}] = 0; }}
  }}"""
    else:
        valid_set = (
            f"dut.{u.valid_in} = k < n;" if u.shape == "valid" else ""
        )
        if u.shape == "valid":
            capture = f"""
    if (dut.{u.valid_out}) {{
      if (j >= n) {{ std::fprintf(stderr, "more outputs than inputs\\n"); return 3; }}
{get_out}
      out[j * {no + 1} + {no}] = cyc;
      ++j;
    }}"""
        else:
            capture = f"""
    if (cyc >= {u.latency} && cyc - {u.latency} < n) {{
      j = cyc - {u.latency};
{get_out}
      out[j * {no + 1} + {no}] = cyc;
    }}"""
        body = f"""
  // reset: four cycles low, inputs idle
  dut.{u.clk} = 0;
  {"dut." + u.rst_n + " = 0;" if u.shape == "valid" else ""}
{zero_in}
  {"dut." + u.valid_in + " = 0;" if u.shape == "valid" else ""}
  for (int r = 0; r < 4; ++r) {{ dut.{u.clk} = 0; dut.eval(); dut.{u.clk} = 1; dut.eval(); }}
  {"dut." + u.rst_n + " = 1;" if u.shape == "valid" else ""}
  uint64_t j = 0;
  const uint64_t limit = n + {u.latency} + 64;
  for (uint64_t cyc = 0; cyc < limit; ++cyc) {{
    // drive input k = cyc on the falling half, sample after the rising edge
    dut.{u.clk} = 0;
    uint64_t k = cyc;
    if (k < n) {{
{set_in.replace("in[k", "in[k")}
    }} else {{
{zero_in}
    }}
    {valid_set}
    dut.eval();
    dut.{u.clk} = 1;
    dut.eval();
{capture}
  }}
  {"if (j != n) { std::fprintf(stderr, \"%llu of %llu outputs\\n\", (unsigned long long)j, (unsigned long long)n); return 4; }" if u.shape == "valid" else ""}"""
    return f"""// generated by examples/minitpu/harness/rtl.py
#include "V{u.top}.h"
#include "verilated.h"
#include <cstdint>
#include <cstdio>
#include <vector>

int main(int argc, char** argv) {{
  Verilated::commandArgs(argc, argv);
  FILE* fi = std::fopen(argv[1], "rb");
  std::fseek(fi, 0, SEEK_END);
  const uint64_t n = std::ftell(fi) / 8 / {ni};
  std::fseek(fi, 0, SEEK_SET);
  std::vector<uint64_t> in(n * {ni}), out(n * {no + 1});
  if (std::fread(in.data(), 8, n * {ni}, fi) != n * {ni}) return 2;
  std::fclose(fi);
  V{u.top} dut;
{body}
  FILE* fo = std::fopen(argv[2], "wb");
  std::fwrite(out.data(), 8, out.size(), fo);
  std::fclose(fo);
  return 0;
}}
"""


def build(u, cache=None):
    """Build the unit's driver once; return the binary's path."""
    home = minitpu_home()
    cache = cache or os.environ.get(
        "MINITPU_HARNESS_CACHE",
        os.path.join(home, ".build", "allo_harness"),
    )
    d = os.path.join(cache, f"{u.top}-{u.key(home)}")
    exe = os.path.join(d, f"V{u.top}")
    if os.path.exists(exe):
        return exe
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "driver.cpp"), "w", encoding="utf-8") as f:
        f.write(_wrapper(u))
    verilator = shutil.which("verilator") or "verilator"
    cmd = (
        [verilator, "--cc", "--exe", "--build", "-Wno-fatal", "-O3"]
        + [f"+define+{d_}" for d_ in u.defines]
        + ["--top-module", u.top, "--Mdir", d, "-j", "8"]
        + [os.path.join(home, s) for s in u.sources]
        + [os.path.join(d, "driver.cpp"), "-CFLAGS", "-std=c++17 -O2"]
    )
    env = dict(os.environ, CXX=_cxx())
    r = subprocess.run(cmd, cwd=home, env=env, capture_output=True, text=True)
    if r.returncode != 0 or not os.path.exists(exe):
        raise RuntimeError(
            f"verilator build of {u.top} failed:\n{r.stdout[-3000:]}\n{r.stderr[-3000:]}"
        )
    return exe


def run(u, stim):
    """Run stimulus ``stim`` (``uint64[n, n_inputs]``) through the RTL unit.

    Returns ``(outputs uint64[n, n_outputs], cycles int64[n])``. ``cycles`` is
    the cycle each output appeared on, counted from the cycle its input was
    offered (so it is the latency for II=1 input); all zero for ``comb``.
    """
    exe = build(u)
    stim = np.ascontiguousarray(stim, dtype=np.uint64)
    assert stim.ndim == 2 and stim.shape[1] == len(u.inputs)
    d = os.path.dirname(exe)
    fi, fo = os.path.join(d, f"in.{os.getpid()}"), os.path.join(d, f"out.{os.getpid()}")
    stim.tofile(fi)
    try:
        r = subprocess.run([exe, fi, fo], capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"{u.top} driver exited {r.returncode}: {r.stderr}")
        raw = np.fromfile(fo, dtype=np.uint64).reshape(-1, len(u.outputs) + 1)
    finally:
        for p in (fi, fo):
            if os.path.exists(p):
                os.remove(p)
    outs = raw[:, :-1]
    for i, (_, w) in enumerate(u.outputs):
        if w < 64:
            outs[:, i] &= np.uint64((1 << w) - 1)
    cycles = raw[:, -1].astype(np.int64)
    if u.shape != "comb":
        cycles = cycles - np.arange(len(cycles), dtype=np.int64)
    return outs, cycles
