# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""U4: ``dma``, MiniTPU's core DMA engine, against a cycle model.

``src/core/dma/dma.sv``: two descriptor channels (IDLE -> PENDING -> ACTIVE
-> DONE, done sticky until a W1C clear), one issue engine serving the
PENDING channels round-robin, a credit counter of ``OUTSTANDING`` bursts, an
in-order order FIFO, a ``LANDING_DEPTH`` landing FIFO that drains response
beats into VMEM (loads) or retires them (stores), a bridge-silence watchdog,
and sticky error/statistics registers. A stride-1 descriptor fuses rows into
bursts of up to 128 DM words, cut at every 4 KiB page; any other stride is
one word per burst. A store reads each beat from VMEM (``vmem_rd_en``, data
``VMEM_DMA_READ_LATENCY`` = 2 cycles later) before sending it.

**Closed loop: open-loop traces from a Python bridge (choice (b)).** The
response side (``dm_rsp_*``) and the VMEM read data depend on the requests
the DMA made. The traces are generated by running the cycle model
(``harness/ref_ctrl_dma.py``) together with a Python model of an in-order
bridge (programmable round trip, response gaps, ``dm_req_ready``
backpressure, SLVERR injection, a dropped response for the watchdog, late
stale beats) and a 2-cycle VMEM read pipe; the inputs it produced are then the
command trace, replayed on the RTL unchanged. No RTL is added (no fixture), so
the DUT is ``dma.sv`` alone and the seeded ``tb_dma_bandwidth`` replays on
the same unit. If the model and the RTL diverge, the RTL meets responses the
model expected; the divergence still shows as a REF-DIFF at its first cycle.

Instances: ``core`` (the parameters ``minitpu_core.sv`` builds: 2 channels,
``OUTSTANDING`` 2, ``LANDING_DEPTH`` 8, watchdog 1024), ``o1``
(``OUTSTANDING`` 1), ``o4`` (``OUTSTANDING`` 4, ``LANDING_DEPTH`` 4: the
equality edge of the ``>=`` rule), ``bw`` (``TIMEOUT_CYCLES`` 0, as
``tb_dma_bandwidth`` builds it; carries that tb's seed).
"""

import hashlib
import os
import random
import shutil
import subprocess

from examples.minitpu.harness import rtl
from examples.minitpu.harness.ref_ctrl_dma import (INPUTS, OUTPUTS, DmaModel, IDLE, dma_trace)
from examples.minitpu.harness.traces import rng_for

SOURCES = ["src/pkg/minitpu_config_pkg.sv", "src/core/vpu/vpu_pkg.sv",
           "src/core/dma/dma_addr_gen.sv", "src/core/dma/dma.sv"]
PARAMS = {
    "core": dict(channels=2, outstanding=2, timeout=1024, landing=8),
    "o1": dict(channels=2, outstanding=1, timeout=1024, landing=8),
    "o4": dict(channels=2, outstanding=4, timeout=1024, landing=4),
    "bw": dict(channels=2, outstanding=2, timeout=0, landing=8),
}


def _unit(p):
    return rtl.RtlUnit(
        top="dma",
        sources=SOURCES,
        inputs=list(INPUTS),
        outputs=[(q, w, "pre") for q, w in OUTPUTS],
        shape="trace",
        clk="clk",
        rst_n="rst_n",
        params={"DMA_CHANNEL_COUNT": p["channels"], "OUTSTANDING": p["outstanding"],
                "TIMEOUT_CYCLES": p["timeout"], "LANDING_DEPTH": p["landing"],
                "M_AXI_DATA_WIDTH": 256},
        assertions=True,
    )


INSTANCES = {k: _unit(p) for k, p in PARAMS.items()}
DEFAULT = "core"
RTL = INSTANCES[DEFAULT]
LATENCY_SOURCE = ("derived from dma.sv (no localparam states them): accept->request 2, "
                  "store VMEM read VMEM_DMA_READ_LATENCY 2 (vpu_pkg.sv:58), last beat->done 2")


def REF(inst, cmd):
    plain = {p: rtl.unpack(cmd[p]) for p, _ in INPUTS}
    n = len(plain["rst_n"])
    out, why, ev = dma_trace(plain, n, PARAMS[inst])
    import numpy as np
    want = {p: rtl.pack(out[p], w) for p, w in OUTPUTS}
    reason = {p: np.array(why[p], dtype=object) for p, _ in OUTPUTS}
    return want, reason, ev


# ---------------------------------------------------------------------------
# Stimulus: the cycle model + a Python bridge and VMEM read pipe
# ---------------------------------------------------------------------------

def _word(seed, k):
    """A deterministic 256-bit word for (seed, k)."""
    h = hashlib.sha256(f"{seed}:{k}".encode()).digest()
    return int.from_bytes(h, "little")


class Bridge:
    """In-order DM bridge: loads answer len+1 beats, stores one B beat after
    their last W beat; each burst becomes eligible ``rtt`` cycles after its
    request (or its last W beat), beats may have gaps; valid is held until
    ``dm_rsp_ready``."""

    def __init__(self, rng, rtt=(2, 12), p_gap=0.1, p_err=0.0, drop=None, late=None):
        self.rng, self.rtt, self.p_gap, self.p_err = rng, rtt, p_gap, p_err
        self.drop = drop  # index of the burst never answered (watchdog)
        self.late = late  # (index, extra cycles): answered that much late (stale beats)
        self.q = []  # [eligible, beats[(data, last, resp)]]
        self.cur = None  # beat on the bus: (data, last, resp)
        self.nburst = 0
        self.st_left = None  # W beats left in the current store burst
        self.st_addr = 0

    def reset(self):
        self.q, self.cur, self.st_left = [], None, None

    def _enqueue(self, t, beats):
        k = self.nburst
        self.nburst += 1
        if k == self.drop:
            return
        lo, hi = self.rtt
        when = t + self.rng.randint(lo, hi) + (self.late[1] if self.late and self.late[0] == k else 0)
        if self.q:
            when = max(when, self.q[-1][0])
        self.q.append([when, beats])

    def drive(self, t):
        """This cycle's response inputs."""
        if self.cur is None and self.q and self.q[0][0] <= t and self.rng.random() >= self.p_gap:
            self.cur = self.q[0][1].pop(0)
            if not self.q[0][1]:
                self.q.pop(0)
        if self.cur is None:
            return dict(dm_rsp_valid=0, dm_rsp_data=_word("idle", t), dm_rsp_last=0, dm_rsp_resp=0)
        d, last, resp = self.cur
        return dict(dm_rsp_valid=1, dm_rsp_data=d, dm_rsp_last=last, dm_rsp_resp=resp)

    def after(self, t, x, o):
        if x["dm_rsp_valid"] and o["dm_rsp_ready"]:
            self.cur = None
        if o["dm_req_valid"] and x["dm_req_ready"]:
            resp = lambda: 2 if self.rng.random() < self.p_err else 0  # noqa: E731
            if o["dm_req_we"]:
                if self.st_left is None:
                    self.st_left = o["dm_req_len"]
                    self.st_addr = o["dm_req_addr"]
                else:
                    self.st_left -= 1
                if self.st_left == 0:
                    self.st_left = None
                    self._enqueue(t, [(_word("b", self.st_addr), 1, resp())])
            else:
                n = o["dm_req_len"] + 1
                a = o["dm_req_addr"]
                self._enqueue(t, [(_word("ddr", a + i), int(i == n - 1), resp()) for i in range(n)])

    def busy(self):
        return bool(self.q) or self.cur is not None


class Program:
    """Descriptors issued as the sequencer issues them (held until accepted);
    a legal program waits for a channel's done and clears it before reusing
    it (``wait.channel``), an illegal one does not."""

    def __init__(self, inst, rng, bridge, p_ready=1.0, p_gnt=1.0):
        self.p = PARAMS[inst]
        self.rng, self.br = rng, bridge
        self.m = DmaModel(**self.p)
        self.rows = []
        self.p_ready, self.p_gnt = p_ready, p_gnt
        self.rd_pipe = {}  # cycle -> vmem_rd_data to drive
        self.ev = {}
        self.cycle(rst_n=0)
        self.cycle(rst_n=0)

    def _defaults(self):
        t = len(self.rows)
        return dict(rst_n=1, desc_valid=0, desc_is_store=0, desc_channel=0, desc_vmem_row=0,
                    desc_rows=0, desc_cols=0, desc_base=0, desc_stride=0, clear_channel_done=0,
                    dm_req_ready=int(self.rng.random() < self.p_ready),
                    vmem_rd_data=self.rd_pipe.pop(t, _word("vjunk", t)),
                    vmem_gnt=int(self.rng.random() < self.p_gnt))

    def cycle(self, **kv):
        t = len(self.rows)
        x = self._defaults()
        x.update(self.br.drive(t) if kv.get("rst_n", 1) else
                 dict(dm_rsp_valid=0, dm_rsp_data=0, dm_rsp_last=0, dm_rsp_resp=0))
        x.update(kv)
        if not x["rst_n"]:
            self.m.reset()
            self.br.reset()
            self.rd_pipe = {}
        o, it = self.m.comb(x)
        if x["rst_n"]:
            self.br.after(t, x, o)
            if o["vmem_rd_en"]:
                self.rd_pipe[t + 2] = _word("vmem", o["vmem_rd_ptr"])
            self.m.edge(x, o, it, self.ev)
        self.rows.append(x)
        return o

    def desc(self, ch, store, vmem, rows, base, stride, legal=True, cols=0):
        """Issue one descriptor; returns the accept cycle."""
        if legal:
            while self.m.st[ch] != IDLE:
                if (self.m.done >> ch) & 1:
                    self.cycle(clear_channel_done=1 << ch)
                else:
                    self.cycle()
        d = dict(desc_valid=1, desc_is_store=store, desc_channel=ch, desc_vmem_row=vmem,
                 desc_rows=rows, desc_cols=cols, desc_base=base & 0xFFFFFFFF,
                 desc_stride=stride & 0xFFFFFFFF)
        for _ in range(20000 if legal else 30):
            t = len(self.rows)
            o = self.cycle(**d)
            if o["desc_accept"]:
                return t
        if not legal:  # the RTL would hang here; give up, then issue it legally
            self.cycle()
            return self.desc(ch, store, vmem, rows, base, stride, legal=True, cols=cols)
        raise RuntimeError("descriptor never accepted")

    def drain(self, limit=6000, clear=True):
        for _ in range(limit):
            if self.m.comb(self._probe_x())[0]["dma_idle"] and not self.br.busy():
                break
            self.cycle()
        if clear:
            self.cycle(clear_channel_done=3)
        self.idle(4)

    def _probe_x(self):
        return dict(desc_valid=0, desc_channel=0)

    def idle(self, k, **kv):
        for _ in range(k):
            self.cycle(**kv)

    def cmd(self):
        return {p: [r[p] for r in self.rows] for p, _ in INPUTS}


def _rand_desc(rng, big=False):
    store = rng.random() < 0.4
    stride = rng.choice([1, 1, 1, 0, 2, 3, 7, 128, 0x10000, rng.getrandbits(32)])
    if store and stride == 0:
        stride = 1  # stride 0 is a load-only broadcast (dma.sv port comment)
    words = rng.choice([1, 1, 2, 4, 8, 16, 33]) if not big else rng.choice([70, 80, 100])
    rows = 4 * words - 1  # dma_desc_adapter: (words + 1) * NUM_SUBLANES - 1 beats
    if rng.random() < 0.1:
        rows = rng.randrange(0, 40)  # a beat count the adapter cannot form: still defined
    vmem = rng.getrandbits(14) & ~3
    base = rng.choice([rng.getrandbits(32), 0x1F80 + rng.randrange(0, 256),
                       0xFFFFFFF0, rng.getrandbits(20)])
    return dict(store=int(store), vmem=vmem, rows=rows, base=base, stride=stride)


def random_program(inst, seed, n=40, p_ready=0.8, p_gnt=1.0, p_err=0.0):
    rng = rng_for("dma", inst, seed)
    br = Bridge(rng, rtt=(1, 20), p_gap=0.15, p_err=p_err)
    pr = Program(inst, rng, br, p_ready=p_ready, p_gnt=p_gnt)
    for _ in range(n):
        d = _rand_desc(rng)
        pr.desc(rng.randrange(2), d["store"], d["vmem"], d["rows"], d["base"], d["stride"])
        pr.idle(rng.choice([0, 0, 1, 3, 10]))
    pr.drain()
    return pr.cmd()


def directed(inst):
    """``[(label, cmd, legal)]``."""
    out = []

    def new(tag, **kw):
        rng = rng_for("dma-dir", inst, tag)
        br = Bridge(rng, **{k: v for k, v in kw.items() if k in ("rtt", "p_gap", "p_err", "drop", "late")})
        return Program(inst, rng, br, **{k: v for k, v in kw.items() if k in ("p_ready", "p_gnt")})

    # one load and one store, contiguous, word-sized
    p = new("ldst", rtt=(3, 3), p_gap=0.0)
    p.desc(0, 0, 0x100, 15, 0x2000, 1)
    p.desc(1, 1, 0x200, 15, 0x3000, 1)
    p.drain()
    out.append(("load+store contiguous", p.cmd(), True))
    # page split: a contiguous load starting 3 words before a 4 KiB boundary, >256 rows
    p = new("page", rtt=(2, 6), p_gap=0.05)
    p.desc(0, 0, 0x40, 299, 0x1000 * 7 + 125, 1)
    p.drain()
    out.append(("page split, 300 rows", p.cmd(), True))
    # store across a page, >256 beats, backpressured
    p = new("stpage", rtt=(2, 9), p_gap=0.1, p_ready=0.6)
    p.desc(1, 1, 0x800, 263, 0x40000 - 2, 1)
    p.drain()
    out.append(("store page split, ready 0.6", p.cmd(), True))
    # stride 0 broadcast load and strided loads/stores
    p = new("strided", rtt=(1, 5))
    p.desc(0, 0, 0x10, 7, 0x5555, 0)
    p.desc(1, 0, 0x30, 11, 0x100, 7)
    p.desc(0, 1, 0x50, 7, 0xFFFFFFF0, 0x10000)
    p.drain()
    out.append(("stride 0 / 7 / 64Ki, wrap", p.cmd(), True))
    # two channels interleaved: both pending at once, round robin
    p = new("rr", rtt=(4, 4), p_gap=0.0)
    p.desc(0, 0, 0x100, 3, 0x10, 2)
    p.desc(1, 1, 0x200, 3, 0x20, 2)
    p.desc(0, 0, 0x300, 3, 0x30, 2)
    p.desc(1, 0, 0x400, 3, 0x40, 2)
    p.drain()
    out.append(("two channels round robin", p.cmd(), True))
    # VMEM grant withheld half the time (the core ties it to 1)
    p = new("gnt", rtt=(1, 4), p_gnt=0.5)
    p.desc(0, 1, 0x60, 11, 0x700, 1)
    p.desc(1, 0, 0x90, 11, 0x900, 1)
    p.drain()
    out.append(("vmem_gnt 0.5", p.cmd(), True))
    # response error: SLVERR on some beats (load beats dropped, sticky error)
    p = new("err", rtt=(1, 6), p_err=0.2)
    p.desc(0, 0, 0x60, 19, 0x700, 3)
    p.desc(1, 1, 0x90, 7, 0x900, 5)
    p.drain()
    out.append(("SLVERR responses", p.cmd(), True))
    if PARAMS[inst]["timeout"]:
        # watchdog: the bridge never answers the 2nd burst, then a stale late beat
        p = new("wd", rtt=(2, 4), drop=1)
        p.desc(0, 0, 0x60, 11, 0x700, 2)
        p.drain(limit=1400)
        p.desc(1, 0, 0x90, 3, 0x900, 1)
        p.drain()
        out.append(("watchdog timeout", p.cmd(), False))
        p = new("late", rtt=(2, 4), late=(0, 1100))
        p.desc(0, 0, 0x60, 3, 0x700, 2)
        p.drain(limit=1400)
        p.idle(1200)
        p.drain()
        out.append(("watchdog, then stale beats dropped", p.cmd(), False))
    # channel reuse without a clear: the sim-only stall assertion
    p = new("reuse", rtt=(6, 6))
    p.desc(0, 0, 0x60, 7, 0x700, 2)
    p.desc(0, 0, 0x90, 7, 0x900, 2, legal=False)
    p.drain()
    out.append(("channel reuse before clear", p.cmd(), False))
    # reset mid-transfer, then a fresh descriptor
    p = new("rst", rtt=(3, 8))
    p.desc(0, 1, 0x60, 31, 0x700, 1)
    p.desc(1, 0, 0x80, 31, 0x800, 1)
    p.idle(9)
    p.idle(2, rst_n=0)
    p.desc(1, 0, 0x90, 7, 0x900, 1)
    p.drain()
    out.append(("reset mid-transfer", p.cmd(), True))
    return out


def traces(inst):
    tr = directed(inst)
    n = {"core": 3, "o1": 2, "o4": 2, "bw": 1}[inst]
    for s in range(n):
        tr.append((f"random-{s}", random_program(inst, s), True))
    if inst == "core":
        tr.append(("random-err", random_program(inst, 9, n=25, p_err=0.1, p_gnt=0.7), True))
    return tr


# ---------------------------------------------------------------------------
# Probes
# ---------------------------------------------------------------------------

def _first_change(col, event):
    vals = rtl.unpack(col)
    for i in range(event, len(vals)):
        if vals[i] != vals[event - 1]:
            return i - event
    return None


def _run(inst, cmd):
    u = INSTANCES[inst]
    return rtl.run_trace(u, {p: rtl.pack(cmd[p], w) for p, w in u.inputs})


def probes(inst):
    """``[(label, declared, measured)]`` measured on the RTL, no reference."""
    res = []
    rng = rng_for("dma-probe", inst)
    # desc_valid -> desc_accept (combinational: 0 edges)
    p = Program(inst, rng, Bridge(rng, rtt=(4, 4), p_gap=0.0))
    p.idle(4)
    ev = len(p.rows)
    p.desc(0, 0, 0x40, 3, 0x100, 1)
    p.drain()
    r = _run(inst, p.cmd())
    res.append(("desc_valid -> desc_accept (comb)", 0, _first_change(r["desc_accept"], ev)))
    res.append(("accept -> first dm_req_valid", 2, _first_change(r["dm_req_valid"], ev)))
    # last response beat -> dma_channel_done
    cmd = p.cmd()
    last = max(i for i, (v, l) in enumerate(zip(cmd["dm_rsp_valid"], cmd["dm_rsp_last"])) if v and l)
    res.append(("last response beat -> dma_channel_done", 2, _first_change(r["dma_channel_done"], last)))
    # done -> clear -> a held descriptor on that channel is accepted
    p = Program(inst, rng, Bridge(rng, rtt=(4, 4), p_gap=0.0))
    p.desc(0, 0, 0x40, 3, 0x100, 1)
    while not p.m.done & 1:
        p.cycle()
    p.idle(3)
    ev = len(p.rows)
    p.cycle(clear_channel_done=1, desc_valid=1, desc_channel=0, desc_rows=3, desc_stride=1)
    d = dict(desc_valid=1, desc_channel=0, desc_rows=3, desc_stride=1)
    while not p.cycle(**d)["desc_accept"]:
        pass
    p.drain()
    r = _run(inst, p.cmd())
    res.append(("clear_channel_done -> held descriptor accepted", 1, _first_change(r["desc_accept"], ev)))
    # store: vmem_rd_en -> the cycle whose vmem_rd_data is captured, by function:
    # a marker on exactly one offset k after the read; which k reaches dm_req_wdata
    got = None
    for k in (1, 2, 3):
        p = Program(inst, rng, Bridge(rng, rtt=(4, 4), p_gap=0.0))
        p.desc(0, 1, 0x40, 0, 0x100, 1)
        cmd = p.cmd()
        # find the read, rebuild the trace with junk VMEM data and the marker at +k
        while True:
            o = p.cycle()
            if o["vmem_rd_en"]:
                rd = len(p.rows) - 1
                break
        p.drain()
        cmd = p.cmd()
        cmd["vmem_rd_data"] = [_word("probe-junk", t) for t in range(len(cmd["rst_n"]))]
        marker = (1 << 255) | 0xC0FFEE
        cmd["vmem_rd_data"][rd + k] = marker
        r = _run(inst, cmd)
        wd = rtl.unpack(r["dm_req_wdata"])
        wv = rtl.unpack(r["dm_req_valid"])
        if any(v and w == marker for v, w in zip(wv, wd)):
            got = k
    res.append(("store: vmem_rd_en -> captured vmem_rd_data (VMEM_DMA_READ_LATENCY)", 2, got))
    return res


# ---------------------------------------------------------------------------
# Seed: MiniTPU's tb_dma_bandwidth (DUT = dma alone, TIMEOUT_CYCLES = 0)
# ---------------------------------------------------------------------------

SEED_TB = "tb_dma_bandwidth"
SEED_SOURCES = ["src/pkg/minitpu_config_pkg.sv", "src/core/vpu/vpu_pkg.sv",
                "src/core/sequencer/sequencer_pkg.sv", "src/core/dma/dma_addr_gen.sv",
                "src/core/dma/dma.sv"]


def _seed_vcd():
    """Build and run ``tb_dma_bandwidth`` unchanged with a VCD dump, cached
    beside vcd_seed's; it prints a bare ``PASS``, so vcd_seed's own
    ``PASS <tb>`` check does not apply."""
    from examples.minitpu.harness import vcd_seed  # noqa: F401
    home = rtl.minitpu_home()
    cache = os.environ.get("MINITPU_HARNESS_CACHE", os.path.join(home, ".build", "allo_harness"))
    h = hashlib.sha256(SEED_TB.encode())
    for s in SEED_SOURCES + [f"tb/{SEED_TB}.sv"]:
        with open(os.path.join(home, s), "rb") as f:
            h.update(f.read())
    d = os.path.join(cache, f"seed-{SEED_TB}-{h.hexdigest()[:12]}")
    vcd = os.path.join(d, "dump.vcd")
    if os.path.exists(vcd):
        return vcd
    os.makedirs(d, exist_ok=True)
    top = os.path.join(d, "u4_seed_top.sv")
    with open(top, "w", encoding="utf-8") as f:
        f.write("`timescale 1ns/1ps\nmodule u4_seed_top;\n  tb_dma_bandwidth tb();\n"
                f'  initial begin $dumpfile("{vcd}"); $dumpvars(0, tb.dut); end\nendmodule\n')
    cmd = ([shutil.which("verilator") or "verilator", "--binary", "--timing", "--trace",
            "-Wno-fatal", "-j", "8", "--top-module", "u4_seed_top", "--Mdir", d]
           + [os.path.join(home, s) for s in SEED_SOURCES]
           + [os.path.join(home, "tb", f"{SEED_TB}.sv"), top])
    r = subprocess.run(cmd, cwd=home, env=dict(os.environ, CXX=rtl._cxx()),
                       capture_output=True, text=True)
    exe = os.path.join(d, "Vu4_seed_top")
    if r.returncode != 0 or not os.path.exists(exe):
        raise RuntimeError(f"seed build failed:\n{r.stdout[-3000:]}\n{r.stderr[-3000:]}")
    r = subprocess.run([exe], cwd=d, capture_output=True, text=True, timeout=900)
    if r.returncode != 0 or "PASS" not in r.stdout:
        if os.path.exists(vcd):
            os.remove(vcd)
        raise RuntimeError(f"{SEED_TB} did not pass:\n{r.stdout[-2000:]}")
    return vcd


def seeds():
    from examples.minitpu.harness import vcd_seed

    vcd = _seed_vcd()
    u = INSTANCES["bw"]
    ins = [p for p, _ in u.inputs]
    outs = [rtl.out_spec(o) for o in u.outputs]
    ch = vcd_seed.read_vcd(vcd, "tb.dut", ["clk"] + ins + [o[0] for o in outs])
    edges = [t for (t, v), (_, pv) in zip(ch["clk"][1:], ch["clk"][:-1]) if v == 1 and pv == 0]

    def before(sig, times):
        out, cur, i, c = [], 0, 0, ch[sig]
        for t in times:
            while i < len(c) and c[i][0] < t:
                cur = c[i][1]
                i += 1
            out.append(cur)
        return out

    times = edges + [float("inf")]
    cmd = {p: before(p, times) for p in ins}
    seen = {p: before(p, times) for p, _, _ in outs}
    return [(SEED_TB, "bw", cmd, seen, True)]


VARIANTS = {}
