# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""U4: ``dma``, MiniTPU's core DMA engine, against a cycle model.

``src/core/dma/dma.sv``: two descriptor channels (IDLE -> PENDING -> ACTIVE
-> DONE, done sticky until a W1C clear), one issue engine serving the
PENDING channels round-robin, a credit counter of ``OUTSTANDING`` bursts, an
in-order order FIFO, a ``LANDING_DEPTH`` landing FIFO that drains response
beats into VMEM (loads) or retires them (stores), a bridge-silence watchdog,
and sticky error/statistics registers. A stride-1 descriptor fuses rows into
bursts of up to 128 DM words, cut at every 4 KiB page; any other stride is
one word per burst. A store reads each beat from VMEM (``vmem_rd_en``, data
``VMEM_DMA_READ_LATENCY`` = 2 cycles later) before sending it.

**Closed loop: open-loop traces from a Python bridge (choice (b)).** The
response side (``dm_rsp_*``) and the VMEM read data depend on the requests
the DMA made. The traces are generated by running the cycle model
(``harness/ref_ctrl_dma.py``) together with a Python model of an in-order
bridge (programmable round trip, response gaps, ``dm_req_ready``
backpressure, SLVERR injection, a dropped response for the watchdog, late
stale beats) and a 2-cycle VMEM read pipe; the inputs it produced are then the
command trace, replayed on the RTL unchanged. No RTL is added (no fixture), so
the DUT is ``dma.sv`` alone and the seeded ``tb_dma_bandwidth`` replays on
the same unit. If the model and the RTL diverge, the RTL meets responses the
model expected; the divergence still shows as a REF-DIFF at its first cycle.

Instances: ``core`` (the parameters ``minitpu_core.sv`` builds: 2 channels,
``OUTSTANDING`` 2, ``LANDING_DEPTH`` 8, watchdog 1024), ``o1``
(``OUTSTANDING`` 1), ``o4`` (``OUTSTANDING`` 4, ``LANDING_DEPTH`` 4: the
equality edge of the ``>=`` rule), ``bw`` (``TIMEOUT_CYCLES`` 0, as
``tb_dma_bandwidth`` builds it; carries that tb's seed).
"""

import hashlib
import os
import random
import shutil
import subprocess

from examples.minitpu.harness import rtl
from examples.minitpu.harness.ref_ctrl_dma import (INPUTS, OUTPUTS, DmaModel, IDLE, dma_trace)
from examples.minitpu.harness.traces import rng_for

SOURCES = ["src/pkg/minitpu_config_pkg.sv", "src/core/vpu/vpu_pkg.sv",
           "src/core/dma/dma_addr_gen.sv", "src/core/dma/dma.sv"]
PARAMS = {
    "core": dict(channels=2, outstanding=2, timeout=1024, landing=8),
    "o1": dict(channels=2, outstanding=1, timeout=1024, landing=8),
    "o4": dict(channels=2, outstanding=4, timeout=1024, landing=4),
    "bw": dict(channels=2, outstanding=2, timeout=0, landing=8),
}


def _unit(p):
    return rtl.RtlUnit(
        top="dma",
        sources=SOURCES,
        inputs=list(INPUTS),
        outputs=[(q, w, "pre") for q, w in OUTPUTS],
        shape="trace",
        clk="clk",
        rst_n="rst_n",
        params={"DMA_CHANNEL_COUNT": p["channels"], "OUTSTANDING": p["outstanding"],
                "TIMEOUT_CYCLES": p["timeout"], "LANDING_DEPTH": p["landing"],
                "M_AXI_DATA_WIDTH": 256},
        assertions=True,
    )


INSTANCES = {k: _unit(p) for k, p in PARAMS.items()}
DEFAULT = "core"
RTL = INSTANCES[DEFAULT]
LATENCY_SOURCE = ("derived from dma.sv (no localparam states them): accept->request 2, "
                  "store VMEM read VMEM_DMA_READ_LATENCY 2 (vpu_pkg.sv:58), last beat->done 2")


def REF(inst, cmd):
    plain = {p: rtl.unpack(cmd[p]) for p, _ in INPUTS}
    n = len(plain["rst_n"])
    out, why, ev = dma_trace(plain, n, PARAMS[inst])
    import numpy as np
    want = {p: rtl.pack(out[p], w) for p, w in OUTPUTS}
    reason = {p: np.array(why[p], dtype=object) for p, _ in OUTPUTS}
    return want, reason, ev


# ---------------------------------------------------------------------------
# Stimulus: the cycle model + a Python bridge and VMEM read pipe
# ---------------------------------------------------------------------------

def _word(seed, k):
    """A deterministic 256-bit word for (seed, k)."""
    h = hashlib.sha256(f"{seed}:{k}".encode()).digest()
    return int.from_bytes(h, "little")


class Bridge:
    """In-order DM bridge: loads answer len+1 beats, stores one B beat after
    their last W beat; each burst becomes eligible ``rtt`` cycles after its
    request (or its last W beat), beats may have gaps; valid is held until
    ``dm_rsp_ready``."""

    def __init__(self, rng, rtt=(2, 12), p_gap=0.1, p_err=0.0, drop=None, late=None):
        self.rng, self.rtt, self.p_gap, self.p_err = rng, rtt, p_gap, p_err
        self.drop = drop  # index of the burst never answered (watchdog)
        self.late = late  # (index, extra cycles): answered that much late (stale beats)
        self.q = []  # [eligible, beats[(data, last, resp)]]
        self.cur = None  # beat on the bus: (data, last, resp)
        self.nburst = 0
        self.st_left = None  # W beats left in the current store burst
        self.st_addr = 0

    def reset(self):
        self.q, self.cur, self.st_left = [], None, None

    def _enqueue(self, t, beats):
        k = self.nburst
        self.nburst += 1
        if k == self.drop:
            return
        lo, hi = self.rtt
        when = t + self.rng.randint(lo, hi) + (self.late[1] if self.late and self.late[0] == k else 0)
        if self.q:
            when = max(when, self.q[-1][0])
        self.q.append([when, beats])

    def drive(self, t):
        """This cycle's response inputs."""
        if self.cur is None and self.q and self.q[0][0] <= t and self.rng.random() >= self.p_gap:
            self.cur = self.q[0][1].pop(0)
            if not self.q[0][1]:
                self.q.pop(0)
        if self.cur is None:
            return dict(dm_rsp_valid=0, dm_rsp_data=_word("idle", t), dm_rsp_last=0, dm_rsp_resp=0)
        d, last, resp = self.cur
        return dict(dm_rsp_valid=1, dm_rsp_data=d, dm_rsp_last=last, dm_rsp_resp=resp)

    def after(self, t, x, o):
        if x["dm_rsp_valid"] and o["dm_rsp_ready"]:
            self.cur = None
        if o["dm_req_valid"] and x["dm_req_ready"]:
            resp = lambda: 2 if self.rng.random() < self.p_err else 0  # noqa: E731
            if o["dm_req_we"]:
                if self.st_left is None:
                    self.st_left = o["dm_req_len"]
                    self.st_addr = o["dm_req_addr"]
                else:
                    self.st_left -= 1
                if self.st_left == 0:
                    self.st_left = None
                    self._enqueue(t, [(_word("b", self.st_addr), 1, resp())])
            else:
                n = o["dm_req_len"] + 1
                a = o["dm_req_addr"]
                self._enqueue(t, [(_word("ddr", a + i), int(i == n - 1), resp()) for i in range(n)])

    def busy(self):
        return bool(self.q) or self.cur is not None


class Program:
    """Descriptors issued as the sequencer issues them (held until accepted);
    a legal program waits for a channel's done and clears it before reusing
    it (``wait.channel``), an illegal one does not."""

    def __init__(self, inst, rng, bridge, p_ready=1.0, p_gnt=1.0):
        self.p = PARAMS[inst]
        self.rng, self.br = rng, bridge
        self.m = DmaModel(**self.p)
        self.rows = []
        self.p_ready, self.p_gnt = p_ready, p_gnt
        self.rd_pipe = {}  # cycle -> vmem_rd_data to drive
        self.ev = {}
        self.cycle(rst_n=0)
        self.cycle(rst_n=0)

    def _defaults(self):
        t = len(self.rows)
        return dict(rst_n=1, desc_valid=0, desc_is_store=0, desc_channel=0, desc_vmem_row=0,
                    desc_rows=0, desc_cols=0, desc_base=0, desc_stride=0, clear_channel_done=0,
                    dm_req_ready=int(self.rng.random() < self.p_ready),
                    vmem_rd_data=self.rd_pipe.pop(t, _word("vjunk", t)),
                    vmem_gnt=int(self.rng.random() < self.p_gnt))

    def cycle(self, **kv):
        t = len(self.rows)
        x = self._defaults()
        x.update(self.br.drive(t) if kv.get("rst_n", 1) else
                 dict(dm_rsp_valid=0, dm_rsp_data=0, dm_rsp_last=0, dm_rsp_resp=0))
        x.update(kv)
        if not x["rst_n"]:
            self.m.reset()
            self.br.reset()
            self.rd_pipe = {}
        o, it = self.m.comb(x)
        if x["rst_n"]:
            self.br.after(t, x, o)
            if o["vmem_rd_en"]:
                self.rd_pipe[t + 2] = _word("vmem", o["vmem_rd_ptr"])
            self.m.edge(x, o, it, self.ev)
        self.rows.append(x)
        return o

    def desc(self, ch, store, vmem, rows, base, stride, legal=True, cols=0):
        """Issue one descriptor; returns the accept cycle."""
        if legal:
            while self.m.st[ch] != IDLE:
                if (self.m.done >> ch) & 1:
                    self.cycle(clear_channel_done=1 << ch)
                else:
                    self.cycle()
        d = dict(desc_valid=1, desc_is_store=store, desc_channel=ch, desc_vmem_row=vmem,
                 desc_rows=rows, desc_cols=cols, desc_base=base & 0xFFFFFFFF,
                 desc_stride=stride & 0xFFFFFFFF)
        for _ in range(20000 if legal else 30):
            t = len(self.rows)
            o = self.cycle(**d)
            if o["desc_accept"]:
                return t
        if not legal:  # the RTL would hang here; give up, then issue it legally
            self.cycle()
            return self.desc(ch, store, vmem, rows, base, stride, legal=True, cols=cols)
        raise RuntimeError("descriptor never accepted")

    def drain(self, limit=6000, clear=True):
        for _ in range(limit):
            if self.m.comb(self._probe_x())[0]["dma_idle"] and not self.br.busy():
                break
            self.cycle()
        if clear:
            self.cycle(clear_channel_done=3)
        self.idle(4)

    def _probe_x(self):
        return dict(desc_valid=0, desc_channel=0)

    def idle(self, k, **kv):
        for _ in range(k):
            self.cycle(**kv)

    def cmd(self):
        return {p: [r[p] for r in self.rows] for p, _ in INPUTS}


def _rand_desc(rng, big=False):
    store = rng.random() < 0.4
    stride = rng.choice([1, 1, 1, 0, 2, 3, 7, 128, 0x10000, rng.getrandbits(32)])
    if store and stride == 0:
        stride = 1  # stride 0 is a load-only broadcast (dma.sv port comment)
    words = rng.choice([1, 1, 2, 4, 8, 16, 33]) if not big else rng.choice([70, 80, 100])
    rows = 4 * words - 1  # dma_desc_adapter: (words + 1) * NUM_SUBLANES - 1 beats
    if rng.random() < 0.1:
        rows = rng.randrange(0, 40)  # a beat count the adapter cannot form: still defined
    vmem = rng.getrandbits(14) & ~3
    base = rng.choice([rng.getrandbits(32), 0x1F80 + rng.randrange(0, 256),
                       0xFFFFFFF0, rng.getrandbits(20)])
    return dict(store=int(store), vmem=vmem, rows=rows, base=base, stride=stride)


def random_program(inst, seed, n=40, p_ready=0.8, p_gnt=1.0, p_err=0.0):
    rng = rng_for("dma", inst, seed)
    br = Bridge(rng, rtt=(1, 20), p_gap=0.15, p_err=p_err)
    pr = Program(inst, rng, br, p_ready=p_ready, p_gnt=p_gnt)
    for _ in range(n):
        d = _rand_desc(rng)
        pr.desc(rng.randrange(2), d["store"], d["vmem"], d["rows"], d["base"], d["stride"])
        pr.idle(rng.choice([0, 0, 1, 3, 10]))
    pr.drain()
    return pr.cmd()


def directed(inst):
    """``[(label, cmd, legal)]``."""
    out = []

    def new(tag, **kw):
        rng = rng_for("dma-dir", inst, tag)
        br = Bridge(rng, **{k: v for k, v in kw.items() if k in ("rtt", "p_gap", "p_err", "drop", "late")})
        return Program(inst, rng, br, **{k: v for k, v in kw.items() if k in ("p_ready", "p_gnt")})

    # one load and one store, contiguous, word-sized
    p = new("ldst", rtt=(3, 3), p_gap=0.0)
    p.desc(0, 0, 0x100, 15, 0x2000, 1)
    p.desc(1, 1, 0x200, 15, 0x3000, 1)
    p.drain()
    out.append(("load+store contiguous", p.cmd(), True))
    # page split: a contiguous load starting 3 words before a 4 KiB boundary, >256 rows
    p = new("page", rtt=(2, 6), p_gap=0.05)
    p.desc(0, 0, 0x40, 299, 0x1000 * 7 + 125, 1)
    p.drain()
    out.append(("page split, 300 rows", p.cmd(), True))
    # store across a page, >256 beats, backpressured
    p = new("stpage", rtt=(2, 9), p_gap=0.1, p_ready=0.6)
    p.desc(1, 1, 0x800, 263, 0x40000 - 2, 1)
    p.drain()
    out.append(("store page split, ready 0.6", p.cmd(), True))
    # stride 0 broadcast load and strided loads/stores
    p = new("strided", rtt=(1, 5))
    p.desc(0, 0, 0x10, 7, 0x5555, 0)
    p.desc(1, 0, 0x30, 11, 0x100, 7)
    p.desc(0, 1, 0x50, 7, 0xFFFFFFF0, 0x10000)
    p.drain()
    out.append(("stride 0 / 7 / 64Ki, wrap", p.cmd(), True))
    # two channels interleaved: both pending at once, round robin
    p = new("rr", rtt=(4, 4), p_gap=0.0)
    p.desc(0, 0, 0x100, 3, 0x10, 2)
    p.desc(1, 1, 0x200, 3, 0x20, 2)
    p.desc(0, 0, 0x300, 3, 0x30, 2)
    p.desc(1, 0, 0x400, 3, 0x40, 2)
    p.drain()
    out.append(("two channels round robin", p.cmd(), True))
    # VMEM grant withheld half the time (the core ties it to 1)
    p = new("gnt", rtt=(1, 4), p_gnt=0.5)
    p.desc(0, 1, 0x60, 11, 0x700, 1)
    p.desc(1, 0, 0x90, 11, 0x900, 1)
    p.drain()
    out.append(("vmem_gnt 0.5", p.cmd(), True))
    # response error: SLVERR on some beats (load beats dropped, sticky error)
    p = new("err", rtt=(1, 6), p_err=0.2)
    p.desc(0, 0, 0x60, 19, 0x700, 3)
    p.desc(1, 1, 0x90, 7, 0x900, 5)
    p.drain()
    out.append(("SLVERR responses", p.cmd(), True))
    if PARAMS[inst]["timeout"]:
        # watchdog: the bridge never answers the 2nd burst, then a stale late beat
        p = new("wd", rtt=(2, 4), drop=1)
        p.desc(0, 0, 0x60, 11, 0x700, 2)
        p.drain(limit=1400)
        p.desc(1, 0, 0x90, 3, 0x900, 1)
        p.drain()
        out.append(("watchdog timeout", p.cmd(), False))
        p = new("late", rtt=(2, 4), late=(0, 1100))
        p.desc(0, 0, 0x60, 3, 0x700, 2)
        p.drain(limit=1400)
        p.idle(1200)
        p.drain()
        out.append(("watchdog, then stale beats dropped", p.cmd(), False))
    # channel reuse without a clear: the sim-only stall assertion
    p = new("reuse", rtt=(6, 6))
    p.desc(0, 0, 0x60, 7, 0x700, 2)
    p.desc(0, 0, 0x90, 7, 0x900, 2, legal=False)
    p.drain()
    out.append(("channel reuse before clear", p.cmd(), False))
    # reset mid-transfer, then a fresh descriptor
    p = new("rst", rtt=(3, 8))
    p.desc(0, 1, 0x60, 31, 0x700, 1)
    p.desc(1, 0, 0x80, 31, 0x800, 1)
    p.idle(9)
    p.idle(2, rst_n=0)
    p.desc(1, 0, 0x90, 7, 0x900, 1)
    p.drain()
    out.append(("reset mid-transfer", p.cmd(), True))
    return out


def traces(inst):
    tr = directed(inst)
    n = {"core": 3, "o1": 2, "o4": 2, "bw": 1}[inst]
    for s in range(n):
        tr.append((f"random-{s}", random_program(inst, s), True))
    if inst == "core":
        tr.append(("random-err", random_program(inst, 9, n=25, p_err=0.1, p_gnt=0.7), True))
    return tr


# ---------------------------------------------------------------------------
# Probes
# ---------------------------------------------------------------------------

def _first_change(col, event):
    vals = rtl.unpack(col)
    for i in range(event, len(vals)):
        if vals[i] != vals[event - 1]:
            return i - event
    return None


def _run(inst, cmd):
    u = INSTANCES[inst]
    return rtl.run_trace(u, {p: rtl.pack(cmd[p], w) for p, w in u.inputs})


def probes(inst):
    """``[(label, declared, measured)]`` measured on the RTL, no reference."""
    res = []
    rng = rng_for("dma-probe", inst)
    # desc_valid -> desc_accept (combinational: 0 edges)
    p = Program(inst, rng, Bridge(rng, rtt=(4, 4), p_gap=0.0))
    p.idle(4)
    ev = len(p.rows)
    p.desc(0, 0, 0x40, 3, 0x100, 1)
    p.drain()
    r = _run(inst, p.cmd())
    res.append(("desc_valid -> desc_accept (comb)", 0, _first_change(r["desc_accept"], ev)))
    res.append(("accept -> first dm_req_valid", 2, _first_change(r["dm_req_valid"], ev)))
    # last response beat -> dma_channel_done
    cmd = p.cmd()
    last = max(i for i, (v, l) in enumerate(zip(cmd["dm_rsp_valid"], cmd["dm_rsp_last"])) if v and l)
    res.append(("last response beat -> dma_channel_done", 2, _first_change(r["dma_channel_done"], last)))
    # done -> clear -> a held descriptor on that channel is accepted
    p = Program(inst, rng, Bridge(rng, rtt=(4, 4), p_gap=0.0))
    p.desc(0, 0, 0x40, 3, 0x100, 1)
    while not p.m.done & 1:
        p.cycle()
    p.idle(3)
    ev = len(p.rows)
    p.cycle(clear_channel_done=1, desc_valid=1, desc_channel=0, desc_rows=3, desc_stride=1)
    d = dict(desc_valid=1, desc_channel=0, desc_rows=3, desc_stride=1)
    while not p.cycle(**d)["desc_accept"]:
        pass
    p.drain()
    r = _run(inst, p.cmd())
    res.append(("clear_channel_done -> held descriptor accepted", 1, _first_change(r["desc_accept"], ev)))
    # store: vmem_rd_en -> the cycle whose vmem_rd_data is captured, by function:
    # a marker on exactly one offset k after the read; which k reaches dm_req_wdata
    got = None
    for k in (1, 2, 3):
        p = Program(inst, rng, Bridge(rng, rtt=(4, 4), p_gap=0.0))
        p.desc(0, 1, 0x40, 0, 0x100, 1)
        cmd = p.cmd()
        # find the read, rebuild the trace with junk VMEM data and the marker at +k
        while True:
            o = p.cycle()
            if o["vmem_rd_en"]:
                rd = len(p.rows) - 1
                break
        p.drain()
        cmd = p.cmd()
        cmd["vmem_rd_data"] = [_word("probe-junk", t) for t in range(len(cmd["rst_n"]))]
        marker = (1 << 255) | 0xC0FFEE
        cmd["vmem_rd_data"][rd + k] = marker
        r = _run(inst, cmd)
        wd = rtl.unpack(r["dm_req_wdata"])
        wv = rtl.unpack(r["dm_req_valid"])
        if any(v and w == marker for v, w in zip(wv, wd)):
            got = k
    res.append(("store: vmem_rd_en -> captured vmem_rd_data (VMEM_DMA_READ_LATENCY)", 2, got))
    return res


# ---------------------------------------------------------------------------
# Seed: MiniTPU's tb_dma_bandwidth (DUT = dma alone, TIMEOUT_CYCLES = 0)
# ---------------------------------------------------------------------------

SEED_TB = "tb_dma_bandwidth"
SEED_SOURCES = ["src/pkg/minitpu_config_pkg.sv", "src/core/vpu/vpu_pkg.sv",
                "src/core/sequencer/sequencer_pkg.sv", "src/core/dma/dma_addr_gen.sv",
                "src/core/dma/dma.sv"]


def _seed_vcd():
    """Build and run ``tb_dma_bandwidth`` unchanged with a VCD dump, cached
    beside vcd_seed's; it prints a bare ``PASS``, so vcd_seed's own
    ``PASS <tb>`` check does not apply."""
    from examples.minitpu.harness import vcd_seed  # noqa: F401
    home = rtl.minitpu_home()
    cache = os.environ.get("MINITPU_HARNESS_CACHE", os.path.join(home, ".build", "allo_harness"))
    h = hashlib.sha256(SEED_TB.encode())
    for s in SEED_SOURCES + [f"tb/{SEED_TB}.sv"]:
        with open(os.path.join(home, s), "rb") as f:
            h.update(f.read())
    d = os.path.join(cache, f"seed-{SEED_TB}-{h.hexdigest()[:12]}")
    vcd = os.path.join(d, "dump.vcd")
    if os.path.exists(vcd):
        return vcd
    os.makedirs(d, exist_ok=True)
    top = os.path.join(d, "u4_seed_top.sv")
    with open(top, "w", encoding="utf-8") as f:
        f.write("`timescale 1ns/1ps\nmodule u4_seed_top;\n  tb_dma_bandwidth tb();\n"
                f'  initial begin $dumpfile("{vcd}"); $dumpvars(0, tb.dut); end\nendmodule\n')
    cmd = ([shutil.which("verilator") or "verilator", "--binary", "--timing", "--trace",
            "-Wno-fatal", "-j", "8", "--top-module", "u4_seed_top", "--Mdir", d]
           + [os.path.join(home, s) for s in SEED_SOURCES]
           + [os.path.join(home, "tb", f"{SEED_TB}.sv"), top])
    r = subprocess.run(cmd, cwd=home, env=dict(os.environ, CXX=rtl._cxx()),
                       capture_output=True, text=True)
    exe = os.path.join(d, "Vu4_seed_top")
    if r.returncode != 0 or not os.path.exists(exe):
        raise RuntimeError(f"seed build failed:\n{r.stdout[-3000:]}\n{r.stderr[-3000:]}")
    r = subprocess.run([exe], cwd=d, capture_output=True, text=True, timeout=900)
    if r.returncode != 0 or "PASS" not in r.stdout:
        if os.path.exists(vcd):
            os.remove(vcd)
        raise RuntimeError(f"{SEED_TB} did not pass:\n{r.stdout[-2000:]}")
    return vcd


def seeds():
    from examples.minitpu.harness import vcd_seed

    vcd = _seed_vcd()
    u = INSTANCES["bw"]
    ins = [p for p, _ in u.inputs]
    outs = [rtl.out_spec(o) for o in u.outputs]
    ch = vcd_seed.read_vcd(vcd, "tb.dut", ["clk"] + ins + [o[0] for o in outs])
    edges = [t for (t, v), (_, pv) in zip(ch["clk"][1:], ch["clk"][:-1]) if v == 1 and pv == 0]

    def before(sig, times):
        out, cur, i, c = [], 0, 0, ch[sig]
        for t in times:
            while i < len(c) and c[i][0] < t:
                cur = c[i][1]
                i += 1
            out.append(cur)
        return out

    times = edges + [float("inf")]
    cmd = {p: before(p, times) for p in ins}
    seen = {p: before(p, times) for p, _, _ in outs}
    return [(SEED_TB, "bw", cmd, seen, True)]


# ---------------------------------------------------------------------------
# Allo variants (U4 track C, ``dev/records/minitpu/u4_track_c_2026-10-08.rst``)
# ---------------------------------------------------------------------------
#
# Every variant is driven by the SAME per-cycle command trace as the RTL (the
# open-loop traces above) and returns every output port per cycle. Region
# ports are four lane arrays (U3 P-8; a 256-bit port has no numpy dtype, B6,
# and a 64-bit lane is lost in csim at >= 2**63, S8):
#
#   CIN  UInt(32)[n, 15]  the scalar inputs, CIN_NAMES order
#   DIN  UInt(32)[n, 16]  dm_rsp_data lanes 0..7, vmem_rd_data lanes 0..7
#   COUT UInt(32)[n, 20]  the scalar outputs, COUT_NAMES order
#   DOUT UInt(32)[n, 16]  dm_req_wdata lanes 0..7, vmem_wr_data lanes 0..7
#
# "Cycle t" is iteration t: reset (asynchronous, so a row with rst_n low is
# sampled in reset), then the outputs from the state the cycle starts in and
# its inputs (rtl.py's "pre" sampling), then the edge. The edge is dma.sv's
# one always_ff transcribed in its order with non-blocking semantics: every
# register written goes to an ``n_*`` copy, reads see the old value, the
# last write wins, and the copies commit at the end of the iteration.

import numpy as np  # noqa: E402

import allo.dataflow as df  # noqa: E402
from allo.ir.types import Stateful, UInt, int32  # noqa: E402

from examples.minitpu.units.dma_addr_gen import addr  # noqa: E402,F401 (the body calls it)
from examples.minitpu.units.dma_params import GEOMETRIES  # noqa: E402

CIN_NAMES = ["rst_n", "desc_valid", "desc_is_store", "desc_channel", "desc_vmem_row", "desc_rows",
             "desc_cols", "desc_base", "desc_stride", "clear_channel_done", "dm_req_ready",
             "dm_rsp_valid", "dm_rsp_last", "dm_rsp_resp", "vmem_gnt"]
DIN_NAMES = ["dm_rsp_data", "vmem_rd_data"]
COUT_NAMES = ["desc_accept", "dma_channel_done", "dma_idle", "dm_req_valid", "dm_req_we",
              "dm_req_addr", "dm_req_len", "dm_req_wstrb", "dm_rsp_ready", "vmem_wr_en",
              "vmem_wr_ptr", "vmem_rd_en", "vmem_rd_ptr", "dma_err", "dma_err_channel",
              "dma_err_cause", "dma_err_resp", "dma_rsp_seen", "beat_count_o", "overlap_stat_o"]
DOUT_NAMES = ["dm_req_wdata", "vmem_wr_data"]
assert sorted(CIN_NAMES + DIN_NAMES) == sorted(p for p, _ in INPUTS)
assert sorted(COUT_NAMES + DOUT_NAMES) == sorted(p for p, _ in OUTPUTS)
WIDTH = {k: 256 for k in PARAMS}


def bits(n, w=256, inst="core", payload="unreset"):
    """Plan D1: ``dma.sv`` transcribed into one cycle-locked kernel.

    ``payload``: the landing FIFO's payload RAM (``lnd_mem``, never reset in
    the RTL). ``"unreset"`` declares it ``@ Stateful(reset=False)`` (P-7,
    D-14: the planned D1); ``"reset"`` declares it ``@ Stateful`` -- reset
    storage, a recorded deviation from the RTL (D-13's note), invisible on
    the defined slots because the RTL's payload is masked while the FIFO is
    empty."""
    PAYLOAD = Stateful(reset=False) if payload == "unreset" else Stateful
    g = GEOMETRIES[inst].legality()
    assert g.CHANNELS == 2, "the trace ports are sized for two channels (ref_ctrl_dma)"
    CH = g.CHANNELS
    OUT = g.OUTSTANDING
    LND = g.LANDING_DEPTH
    TO = g.TIMEOUT_CYCLES
    L = g.LANES
    NC = len(CIN_NAMES)
    NO = len(COUT_NAMES)
    CRED_M = (1 << g.CRED_W) - 1
    OUTC_M = (1 << g.CRED_W) - 1  # OUT_CNT_W == CRED_W
    LNDC_M = (1 << g.LND_CNT_W) - 1
    TO_M = (1 << g.TO_W) - 1
    TO_LAST = (TO - 1) & TO_M
    PW_M1 = g.PAGE_WORDS - 1
    ROW_M = (1 << g.ROW_BITS) - 1
    RDL_M1 = g.VMEM_DMA_READ_LATENCY - 1
    LND_LAST = LND - 1
    OUT_LAST = OUT - 1
    ADDR_M = (1 << g.DRAM_BEAT_ADDR_W) - 1

    @df.region()
    def top(CI: UInt(32)[n, NC], DI: UInt(32)[n, 2 * L], CO: UInt(32)[n, NO], DO: UInt(32)[n, 2 * L]):
        @df.kernel(mapping=[1], args=[CI, DI, CO, DO])
        def dma(cin: UInt(32)[n, NC], din: UInt(32)[n, 2 * L], cout: UInt(32)[n, NO],
                dout: UInt(32)[n, 2 * L]):
            # ---- per-channel descriptor state (reset) ----
            st: int32[CH] = 0
            cstore: int32[CH] = 0
            cvmem: int32[CH] = 0
            clast: int32[CH] = 0
            cbase: UInt(32)[CH] = 0
            cstride: UInt(32)[CH] = 0
            cnext: int32[CH] = 0
            call: int32[CH] = 0
            cbif: int32[CH] = 0
            n_st: int32[CH] = 0
            n_cstore: int32[CH] = 0
            n_cvmem: int32[CH] = 0
            n_clast: int32[CH] = 0
            n_cbase: UInt(32)[CH] = 0
            n_cstride: UInt(32)[CH] = 0
            n_cnext: int32[CH] = 0
            n_call: int32[CH] = 0
            n_cbif: int32[CH] = 0
            cdone: int32 = 0  # not `done`: C1 (the SystemC process has a `done` port)
            # ---- issue engine ----
            eng: int32 = 0
            iss: int32 = 0
            rr: int32 = 0
            st_beat: int32 = 0
            rd_lat: int32 = 0
            st_data: UInt(32)[L] = 0
            credit: int32 = OUT
            # ---- order FIFO (reset) ----
            ord_ch: int32[OUT] = 0
            ord_vmem: int32[OUT] = 0
            ord_store: int32[OUT] = 0
            ord_head: int32 = 0
            ord_tail: int32 = 0
            ord_count: int32 = 0
            # ---- landing FIFO: payload never reset (P-7, D-14); control reset ----
            lnd_ch: int32[LND] @ PAYLOAD
            lnd_store: int32[LND] @ PAYLOAD
            lnd_dest: int32[LND] @ PAYLOAD
            lnd_data: UInt(32)[LND, L] @ PAYLOAD
            lnd_r: int32[LND] @ PAYLOAD
            lnd_last: int32[LND] @ PAYLOAD
            lnd_head: int32 = 0
            lnd_tail: int32 = 0
            lnd_count: int32 = 0
            rsp_beat: int32 = 0
            to_cnt: int32 = 0
            err: int32 = 0
            err_ch: int32 = 0
            err_cause: int32 = 0
            err_resp: int32 = 0
            rsp_seen: int32 = 0
            beats: UInt(32) = 0
            ovl_max: int32 = 0
            ovl_cyc: int32 = 0
            for t in range(n):
                # S6: every port element read once, unconditionally
                rst: int32 = cin[t, 0]
                dv: int32 = cin[t, 1]
                dis: int32 = cin[t, 2]
                dch: int32 = cin[t, 3]
                dvr: int32 = cin[t, 4]
                drows: int32 = cin[t, 5]
                dcols: int32 = cin[t, 6]  # carried, unused (dma.sv:37)
                dbase: UInt(32) = cin[t, 7]
                dstride: UInt(32) = cin[t, 8]
                clr: int32 = cin[t, 9]
                rdy: int32 = cin[t, 10]
                rv: int32 = cin[t, 11]
                rlast: int32 = cin[t, 12]
                rresp: int32 = cin[t, 13]
                gnt: int32 = cin[t, 14]
                rdata: UInt(32)[L] = 0
                vdata: UInt(32)[L] = 0
                for k in range(L):
                    rdata[k] = din[t, k]
                    vdata[k] = din[t, L + k]
                if rst == 0:  # asynchronous reset: everything but the landing payload
                    for c in range(CH):
                        st[c] = 0
                        cstore[c] = 0
                        cvmem[c] = 0
                        clast[c] = 0
                        cbase[c] = 0
                        cstride[c] = 0
                        cnext[c] = 0
                        call[c] = 0
                        cbif[c] = 0
                    cdone = 0
                    eng = 0
                    iss = 0
                    rr = 0
                    st_beat = 0
                    rd_lat = 0
                    for k in range(L):
                        st_data[k] = 0
                    credit = OUT
                    for j in range(OUT):
                        ord_ch[j] = 0
                        ord_vmem[j] = 0
                        ord_store[j] = 0
                    ord_head = 0
                    ord_tail = 0
                    ord_count = 0
                    lnd_head = 0
                    lnd_tail = 0
                    lnd_count = 0
                    rsp_beat = 0
                    to_cnt = 0
                    err = 0
                    err_ch = 0
                    err_cause = 0
                    err_resp = 0
                    rsp_seen = 0
                    beats = 0
                    ovl_max = 0
                    ovl_cyc = 0
                # ---- combinational issue view (dma.sv:195-218) ----
                cur: int32 = cnext[iss]
                cur14: UInt(14) = cur
                agu: UInt(32) = addr(cbase[iss], cur14, cstride[iss])
                logical: int32 = agu & ADDR_M
                contiguous: int32 = 0
                if cstride[iss] == 1:
                    contiguous = 1
                left_m1: int32 = (clast[iss] - cur) & ROW_M
                to_bound_m1: int32 = PW_M1 - (logical & PW_M1)
                left_sat: int32 = left_m1 & 255
                if (left_m1 >> 8) != 0:
                    left_sat = 255
                blen: int32 = 0
                if contiguous == 1:
                    blen = left_sat
                    if to_bound_m1 < left_sat:
                        blen = to_bound_m1
                last: int32 = 0
                if blen == left_m1:
                    last = 1
                vbase: int32 = (cvmem[iss] + cur) & 0xFFFF
                # ---- landing head ----
                hch: int32 = lnd_ch[lnd_head]
                hstore: int32 = lnd_store[lnd_head]
                hdest: int32 = lnd_dest[lnd_head]
                hr: int32 = lnd_r[lnd_head]
                hlast: int32 = lnd_last[lnd_head]
                # ---- outputs ----
                req_valid: int32 = 0
                if eng == 1:
                    if credit != 0:
                        req_valid = 1
                elif eng == 4:
                    if st_beat != 0 or credit != 0:
                        req_valid = 1
                we: int32 = 0
                if eng == 4:
                    we = 1
                rsp_ready: int32 = 1
                if ord_count != 0:
                    if lnd_count >= LND:
                        rsp_ready = 0
                lnd_ne: int32 = 0
                if lnd_count != 0:
                    lnd_ne = 1
                wr_en: int32 = 0
                if lnd_ne == 1 and hstore == 0 and hr == 0:
                    wr_en = 1
                rd_en: int32 = 0
                if eng == 2 and wr_en == 0:
                    rd_en = 1
                accept: int32 = 0
                if dv == 1 and st[dch] == 0:
                    accept = 1
                idle: int32 = 0
                if ord_count == 0 and lnd_count == 0:
                    idle = 1
                for c in range(CH):
                    if st[c] == 1 or st[c] == 2:
                        idle = 0
                ovl: UInt(32) = ovl_cyc
                ovl = (ovl << 8) | ovl_max
                cout[t, 0] = accept
                cout[t, 1] = cdone
                cout[t, 2] = idle
                cout[t, 3] = req_valid
                cout[t, 4] = we
                cout[t, 5] = logical
                cout[t, 6] = blen
                cout[t, 7] = 0xFFFFFFFF
                cout[t, 8] = rsp_ready
                cout[t, 9] = wr_en
                cout[t, 10] = hdest
                cout[t, 11] = rd_en
                cout[t, 12] = (cvmem[iss] + cur + st_beat) & 0xFFFF
                cout[t, 13] = err
                cout[t, 14] = err_ch
                cout[t, 15] = err_cause
                cout[t, 16] = err_resp
                cout[t, 17] = rsp_seen
                cout[t, 18] = beats
                cout[t, 19] = ovl
                for k in range(L):
                    dout[t, k] = st_data[k]
                    dout[t, L + k] = lnd_data[lnd_head, k]
                # ---- the edge (dma.sv:300-560) ----
                if rst == 1:
                    req_fire: int32 = 0
                    if req_valid == 1 and rdy == 1:
                        req_fire = 1
                    rsp_fire: int32 = 0
                    if rv == 1 and rsp_ready == 1:
                        rsp_fire = 1
                    real_rsp: int32 = 0
                    if rsp_fire == 1 and ord_count != 0:
                        real_rsp = 1
                    lnd_pop: int32 = 0
                    if lnd_ne == 1:
                        if hstore == 1 or hr != 0 or gnt == 1:
                            lnd_pop = 1
                    issue_push: int32 = 0
                    ord_pop: int32 = 0
                    lnd_push: int32 = 0
                    drain_last: int32 = lnd_pop & hlast
                    timeout: int32 = 0
                    oh_ch: int32 = ord_ch[ord_head]
                    oh_vmem: int32 = ord_vmem[ord_head]
                    oh_store: int32 = ord_store[ord_head]
                    for c in range(CH):
                        n_st[c] = st[c]
                        n_cstore[c] = cstore[c]
                        n_cvmem[c] = cvmem[c]
                        n_clast[c] = clast[c]
                        n_cbase[c] = cbase[c]
                        n_cstride[c] = cstride[c]
                        n_cnext[c] = cnext[c]
                        n_call[c] = call[c]
                        n_cbif[c] = cbif[c]
                    n_done: int32 = cdone
                    n_eng: int32 = eng
                    n_iss: int32 = iss
                    n_rr: int32 = rr
                    n_st_beat: int32 = st_beat
                    n_rd_lat: int32 = rd_lat
                    cap: int32 = 0
                    n_ord_head: int32 = ord_head
                    n_ord_tail: int32 = ord_tail
                    n_lnd_head: int32 = lnd_head
                    n_lnd_tail: int32 = lnd_tail
                    n_rsp_beat: int32 = rsp_beat
                    n_to_cnt: int32 = to_cnt
                    n_err: int32 = err
                    n_err_ch: int32 = err_ch
                    n_err_cause: int32 = err_cause
                    n_err_resp: int32 = err_resp
                    n_rsp_seen: int32 = rsp_seen
                    n_ovl_max: int32 = ovl_max
                    n_ovl_cyc: int32 = ovl_cyc
                    # 1) descriptor accept
                    if accept == 1:
                        n_st[dch] = 1
                        n_cstore[dch] = dis
                        n_cvmem[dch] = dvr
                        n_clast[dch] = drows
                        n_cbase[dch] = dbase
                        n_cstride[dch] = dstride
                        n_cnext[dch] = 0
                        n_call[dch] = 0
                    # 2) W1C clear
                    for c in range(CH):
                        if ((clr >> c) & 1) == 1:
                            n_done = n_done & (3 - (1 << c))
                            if st[c] == 3:
                                n_st[c] = 0
                    # 3) issue engine
                    if eng == 0:
                        pick: int32 = 0
                        any_p: int32 = 0
                        for k in range(CH):
                            idx: int32 = (rr + (CH - 1 - k)) % CH
                            if st[idx] == 1:
                                any_p = 1
                                pick = idx
                        if any_p == 1:
                            n_iss = pick
                            n_st[pick] = 2
                            n_rr = (pick + 1) % CH
                            n_st_beat = 0
                            if cstore[pick] == 1:
                                n_eng = 2
                            else:
                                n_eng = 1
                    elif eng == 1:
                        if req_fire == 1:
                            issue_push = 1
                            if last == 1:
                                n_call[iss] = 1
                                n_eng = 0
                            else:
                                n_cnext[iss] = (cur + blen + 1) & ROW_M
                    elif eng == 2:
                        if rd_en == 1 and gnt == 1:
                            n_rd_lat = 0
                            n_eng = 3
                    elif eng == 3:
                        if rd_lat == RDL_M1:
                            cap = 1
                            n_eng = 4
                        else:
                            n_rd_lat = (rd_lat + 1) & 3
                    elif eng == 4:
                        if req_fire == 1:
                            if st_beat == 0:
                                issue_push = 1
                            if st_beat == blen:
                                if last == 1:
                                    n_call[iss] = 1
                                    n_eng = 0
                                else:
                                    n_cnext[iss] = (cur + blen + 1) & ROW_M
                                    n_st_beat = 0
                                    n_eng = 2
                            else:
                                n_st_beat = (st_beat + 1) & 255
                                n_eng = 2
                    # 4) response accept
                    if rv == 1:
                        n_rsp_seen = 1
                    if real_rsp == 1:
                        if lnd_tail == LND_LAST:
                            n_lnd_tail = 0
                        else:
                            n_lnd_tail = lnd_tail + 1
                        lnd_push = 1
                        if rlast == 1:
                            ord_pop = 1
                            if ord_head == OUT_LAST:
                                n_ord_head = 0
                            else:
                                n_ord_head = ord_head + 1
                            n_rsp_beat = 0
                        else:
                            n_rsp_beat = (rsp_beat + 1) & 255
                    # 5) order FIFO push
                    if issue_push == 1:
                        ord_ch[ord_tail] = iss
                        ord_vmem[ord_tail] = vbase
                        ord_store[ord_tail] = cstore[iss]
                        if ord_tail == OUT_LAST:
                            n_ord_tail = 0
                        else:
                            n_ord_tail = ord_tail + 1
                    n_ord_count: int32 = (ord_count + issue_push - ord_pop) & OUTC_M
                    # 6) landing FIFO pop
                    if lnd_pop == 1:
                        if lnd_head == LND_LAST:
                            n_lnd_head = 0
                        else:
                            n_lnd_head = lnd_head + 1
                        if hr != 0:
                            n_err = 1
                            if err == 0:
                                n_err_ch = hch
                                n_err_cause = 1
                                n_err_resp = hr
                    n_lnd_count: int32 = (lnd_count + lnd_push - lnd_pop) & LNDC_M
                    bc: int32 = 0
                    if lnd_pop == 1 and hstore == 0 and hr == 0:
                        bc = 1
                    if req_fire == 1 and we == 1:
                        bc = bc + 1
                    n_beats: UInt(32) = beats + bc
                    # 6c) overlap
                    nonidle: int32 = 0
                    for c in range(CH):
                        if st[c] == 1 or st[c] == 2:
                            nonidle = nonidle + 1
                    if nonidle > ovl_max:
                        n_ovl_max = nonidle & 255
                    if nonidle >= 2 and ovl_cyc != 0xFFFFFF:
                        n_ovl_cyc = ovl_cyc + 1
                    # 7) credit
                    n_credit: int32 = (credit - issue_push + ord_pop) & CRED_M
                    # 8) per-channel in flight + completion
                    for c in range(CH):
                        inc: int32 = 0
                        if issue_push == 1 and iss == c:
                            inc = 1
                        dec: int32 = 0
                        if drain_last == 1 and hch == c:
                            dec = 1
                        n_cbif[c] = (cbif[c] + inc - dec) & OUTC_M
                        if dec == 1 and inc == 0 and cbif[c] == 1 and call[c] == 1:
                            n_done = n_done | (1 << c)
                            n_st[c] = 3
                    # 9) watchdog
                    if ord_count == 0 or rv == 1 or req_fire == 1:
                        n_to_cnt = 0
                    elif TO != 0 and to_cnt == TO_LAST:
                        timeout = 1
                    else:
                        n_to_cnt = (to_cnt + 1) & TO_M
                    # 10) watchdog flush
                    if timeout == 1:
                        n_err = 1
                        if err == 0:
                            n_err_ch = oh_ch
                            n_err_cause = 2
                            n_err_resp = 0
                        for c in range(CH):
                            n_cbif[c] = 0
                            if st[c] == 1 or st[c] == 2:
                                n_done = n_done | (1 << c)
                                n_st[c] = 3
                        n_credit = OUT
                        n_ord_head = 0
                        n_ord_tail = 0
                        n_ord_count = 0
                        n_lnd_head = 0
                        n_lnd_tail = 0
                        n_lnd_count = 0
                        n_rsp_beat = 0
                        n_st_beat = 0
                        n_eng = 0
                        n_to_cnt = 0
                    # the landing payload write (its own always_ff: rst_n && real_rsp)
                    if real_rsp == 1:
                        lnd_ch[lnd_tail] = oh_ch
                        lnd_store[lnd_tail] = oh_store
                        lnd_dest[lnd_tail] = (oh_vmem + rsp_beat) & 0xFFFF
                        lnd_r[lnd_tail] = rresp
                        lnd_last[lnd_tail] = rlast
                        for k in range(L):
                            lnd_data[lnd_tail, k] = rdata[k]
                    if cap == 1:
                        for k in range(L):
                            st_data[k] = vdata[k]
                    # commit
                    for c in range(CH):
                        st[c] = n_st[c]
                        cstore[c] = n_cstore[c]
                        cvmem[c] = n_cvmem[c]
                        clast[c] = n_clast[c]
                        cbase[c] = n_cbase[c]
                        cstride[c] = n_cstride[c]
                        cnext[c] = n_cnext[c]
                        call[c] = n_call[c]
                        cbif[c] = n_cbif[c]
                    cdone = n_done & 3
                    eng = n_eng
                    iss = n_iss
                    rr = n_rr
                    st_beat = n_st_beat
                    rd_lat = n_rd_lat
                    credit = n_credit
                    ord_head = n_ord_head
                    ord_tail = n_ord_tail
                    ord_count = n_ord_count
                    lnd_head = n_lnd_head
                    lnd_tail = n_lnd_tail
                    lnd_count = n_lnd_count
                    rsp_beat = n_rsp_beat
                    to_cnt = n_to_cnt
                    err = n_err
                    err_ch = n_err_ch
                    err_cause = n_err_cause
                    err_resp = n_err_resp
                    rsp_seen = n_rsp_seen
                    beats = n_beats
                    ovl_max = n_ovl_max
                    ovl_cyc = n_ovl_cyc

    return top


def _lanes(vals, nl, lb=32):
    m = (1 << lb) - 1
    return np.array([[(int(v) >> (lb * k)) & m for k in range(nl)] for v in vals], dtype=np.uint32)


def _join(arr, lb=32):
    return [sum(int(x) << (lb * k) for k, x in enumerate(row)) for row in arr]


def run_bits(mod, cmd, n, w=256):
    L = 8
    ci = np.zeros((n, len(CIN_NAMES)), dtype=np.uint32)
    for j, p in enumerate(CIN_NAMES):
        ci[:, j] = np.asarray([int(x) for x in cmd[p][:n]], dtype=np.uint32)
    di = np.concatenate([_lanes(cmd["dm_rsp_data"][:n], L), _lanes(cmd["vmem_rd_data"][:n], L)], axis=1)
    co = np.zeros((n, len(COUT_NAMES)), dtype=np.uint32)
    do = np.zeros((n, 2 * L), dtype=np.uint32)
    mod(ci, np.ascontiguousarray(di), co, do)
    out = {p: [int(x) for x in co[:, j]] for j, p in enumerate(COUT_NAMES)}
    out["dm_req_wdata"] = _join(do[:, :L])
    out["vmem_wr_data"] = _join(do[:, L:])
    return out


def bits_reset(n, w=256, inst="core"):
    return bits(n, w, inst, payload="reset")


def streams(n, w=256, inst="core", payload="unreset"):
    """D1 as the track states it: ``dma_unit.dma_engine`` (this file's ``bits``
    with every port a token) between a source and a sink over Streams, one
    token per link per cycle; the same port arrays as ``bits``."""
    from examples.minitpu.units.dma_unit import streams_architecture  # noqa: PLC0415

    return streams_architecture(n, inst, payload).region("simulator")


def streams_reset(n, w=256, inst="core"):
    return streams(n, w, inst, payload="reset")


VARIANTS = {"bits": (bits, run_bits), "bits_reset": (bits_reset, run_bits),
            "streams": (streams, run_bits), "streams_reset": (streams_reset, run_bits)}
