# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Export a configuration's generated Verilog for the ASIC synthesis handoff.

zhang-21 has a synthesis-only mflowgen flow (DC on freepdk-45nm, memories as
flip-flops, no place-and-route) that enters at `sv2v` and takes RTL through
git. This writes one directory per configuration containing the `.v`/`.sv`
files, an `sv2v_manifest.f` in dependency order, the top module name, and a
README with the configuration's parameters, the commit it was emitted from and
its measured cycles and resources -- so the DC area numbers can be compared
against something rather than standing alone.

**The manifest is GENERATED, not written by hand.** Order comes from the
module instantiation graph of the files themselves, topologically sorted with
the leaves first, so it is derived from the project's own output and cannot
drift from it. Vitis emits one module per file for a dataflow region and no
compile-order file of its own, which is why the graph is the only source.

    python export_rtl.py                    # the three handoff configurations
    python export_rtl.py --only ship16

Used as a library by `latency_grid.py`, which exports from a project it was
going to synthesize anyway rather than paying for a second synthesis.
"""

import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DEST = os.path.join(ROOT, "examples", "accelerator", "tinytpu_vitis", "rtl_handoff")
TOP = "tinytpu_isa"

# `module <name>` and `<Name> <inst> (` / `<Name> #(... ) <inst> (`.
_MODULE = re.compile(r"^\s*module\s+([A-Za-z_]\w*)", re.M)
_INST = re.compile(r"^\s*([A-Za-z_]\w*)\s*(?:#\s*\([^;]*?\)\s*)?"
                   r"([A-Za-z_]\w*)\s*\(", re.M)
# Verilog keywords that the instantiation pattern would otherwise pick up.
_KW = {"module", "endmodule", "input", "output", "inout", "reg", "wire",
       "always", "assign", "if", "else", "case", "begin", "end", "for",
       "while", "initial", "function", "task", "generate", "parameter",
       "localparam", "integer", "real", "genvar", "logic", "bit", "return",
       "posedge", "negedge", "or", "and", "not", "signed", "unsigned",
       "default", "endcase", "wait", "repeat", "forever", "disable"}


def compile_order(files):
    """Leaves first: a topological sort of the module instantiation graph.

    `files` maps a filename to its text. A file is emitted only after every
    file defining a module it instantiates. A cycle (which Verilog should not
    have) degrades to alphabetical for the files involved rather than
    raising -- an unusable manifest is worse than a slightly wrong order,
    and `sv2v` will say so.
    """
    defines, uses = {}, {}
    for name, text in files.items():
        mods = set(_MODULE.findall(text))
        for m in mods:
            defines[m] = name
        cand = {m for m, _inst in _INST.findall(text)}
        uses[name] = cand - _KW - mods
    order, seen, stack = [], set(), set()

    def visit(name):
        if name in seen:
            return
        if name in stack:           # a cycle: stop descending
            return
        stack.add(name)
        for mod in sorted(uses.get(name, ())):
            dep = defines.get(mod)
            if dep and dep != name:
                visit(dep)
        stack.discard(name)
        seen.add(name)
        order.append(name)

    # The top last, so start from everything else and finish at the top.
    top_file = defines.get(TOP)
    for name in sorted(files):
        if name != top_file:
            visit(name)
    if top_file:
        visit(top_file)
    return order


def write_design(src_verilog, dest, meta=None):
    """Copy `src_verilog`/*.v|sv into `dest` and write the manifest + README."""
    os.makedirs(dest, exist_ok=True)
    names = sorted(f for f in os.listdir(src_verilog)
                   if f.endswith((".v", ".sv")))
    if not names:
        return None
    files = {}
    for n in names:
        with open(os.path.join(src_verilog, n), errors="replace") as fh:
            files[n] = fh.read()
        shutil.copyfile(os.path.join(src_verilog, n), os.path.join(dest, n))
    order = compile_order(files)
    with open(os.path.join(dest, "sv2v_manifest.f"), "w") as fh:
        fh.write(f"# TinyTPU-isa RTL for sv2v. Top module: {TOP}\n"
                 f"# Paths are relative to this directory, in dependency\n"
                 f"# order (leaves first, {TOP} last). GENERATED by\n"
                 f"# examples/accelerator/tinytpu_vitis/export_rtl.py from the\n"
                 f"# module instantiation graph of these files -- do not edit.\n"
                 f"# '#' comments and a leading '!' excludes a file.\n")
        for n in order:
            fh.write(n + "\n")
    meta = dict(meta or {})
    meta["top"] = TOP
    meta["files"] = len(order)
    with open(os.path.join(dest, "MANIFEST.json"), "w") as fh:
        json.dump(meta, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return meta


def readme(dest, title, params, commit, cycles, resources, notes):
    lines = [f"# {title}", "",
             "Vitis HLS 2023.2 generated Verilog for the ASIC synthesis-only",
             "handoff (DC, freepdk-45nm, memories as flip-flops, no P&R).",
             "Enter the flow at `sv2v` with `sv2v_manifest.f`; the top module",
             f"is `{TOP}`.", "",
             "## Configuration", ""]
    for k, v in params.items():
        lines.append(f"- `{k}` = {v}")
    lines += ["", f"Emitted from allo commit `{commit}`.", "",
              "## Measured on this configuration", "",
              "Cycles are Vitis `cosim` (xsim), `ap_start` to `ap_done`,",
              "`-m_axi_latency 0` unless stated, bit-exact against numpy.", ""]
    for k, v in cycles.items():
        lines.append(f"- {k}: **{v}** cycles")
    lines += ["", "Vitis `csynth` on `xcu280-fsvh2892-2L-e`, 3.33 ns target:", ""]
    for k, v in resources.items():
        lines.append(f"- {k}: {v}")
    if notes:
        lines += ["", "## Notes", ""] + [f"- {n}" for n in notes]
    lines += ["", "`sv2v_manifest.f` and `MANIFEST.json` are generated by",
              "`examples/accelerator/tinytpu_vitis/export_rtl.py`.", ""]
    with open(os.path.join(dest, "README.md"), "w") as fh:
        fh.write("\n".join(lines))


def commit():
    try:
        return subprocess.run(["git", "-C", ROOT, "rev-parse", "HEAD"],
                              capture_output=True, text=True).stdout.strip()
    except Exception:
        return "unknown"


def build_and_export(name, env_extra, dest, shapes):
    """csynth one configuration, export its Verilog, delete the project."""
    prj = os.path.join(HERE, f"export_{name}.prj")
    env = dict(os.environ, TPU_PRJ=prj, **env_extra)
    for v in ("TPU_TB", "TPU_SET", "TPU_SHAPES", "TPU_AXI_LATENCY"):
        env.pop(v, None)
    child = (
        "import os, sys; sys.path.insert(0, %r)\n"
        "from examples.accelerator.tinytpu_vitis import cosim\n"
        "from examples.accelerator.tinytpu_vitis.microarch_isa import "
        "tinytpu_isa, schedule\n"
        "from allo.dataflow import customize\n"
        "prj = cosim.PRJ\n"
        "s = customize(tinytpu_isa); schedule(s)\n"
        "s.build(target='vitis_hls', mode='csyn', project=prj, wrap_io=False,"
        " configs={'align_value': 64})\n"
        "cosim.patch_axi_depths(prj)\n"
        "open(os.path.join(prj, 'tb.cpp'), 'w').write('int main(){return 0;}')\n"
        "cosim.vitis(prj, cosim.TCL_SYN, 'csynth.log')\n"
        "print('CSYNTH DONE')\n" % ROOT)
    try:
        subprocess.run([sys.executable, "-c", child], env=env,
                       capture_output=True, text=True)
        src = os.path.join(prj, "out.prj/solution1/syn/verilog")
        rpt = os.path.join(
            prj, "out.prj/solution1/syn/report/tinytpu_isa_csynth.rpt")
        res = {}
        if os.path.exists(rpt):
            sys.path.insert(0, HERE)
            from csynth_sweep import parse
            res = parse(open(rpt, errors="replace").read())
        meta = write_design(src, dest, meta={"config": env_extra,
                                             "resources": res})
        return meta, res
    finally:
        shutil.rmtree(prj, ignore_errors=True)


if __name__ == "__main__":
    print(f"exporting into {DEST}")
    print("Run `latency_grid.py --keep-verilog <dir>` to export the "
          "burst-widened variant from a build it makes anyway.")
