# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Dump a switching-activity file (SAIF) from the cosim run of a published shape.

WHY. A synthesis power number that is not activity-annotated is a
default-toggle-rate guess. The evaluation's commitment (`dev/paper_outline.md`)
is that power is published only if BOTH sides of the comparison are annotated,
so this produces our side: a SAIF taken from the *same* RTL simulation whose
cycle count we quote, which is what makes power and cycles describe one run.

WHERE IT INJECTS, and why not anywhere else. Vitis regenerates
`sim/verilog/tinytpu_isa.tcl` and `sim/verilog/run_xsim.sh` on every
`cosim_design`, so editing either would be undone by the next run and would
also make the published cycle counts depend on our instrumentation. Instead
this script runs AFTER a normal `cosim.py` has finished and left a project
behind, and re-runs **only the xsim step** from sibling files it writes itself
(`saif_dump.tcl`, `saif_xsim.sh`), into a separate snapshot (`*_dbg`). The
design, the testbench, the C golden vectors and the original snapshot are all
untouched; `cosim.py` and `reproduce.sh` keep working exactly as before.

WHAT IT CHECKS BEFORE CLAIMING SUCCESS. An instrument that reports success
without having run is the failure mode this project keeps catching, and a
zero-activity SAIF annotates cleanly and yields a beautiful meaningless power
number. So the run is only reported as good when all four hold:

  1. the latency the testbench measures is byte-identical to the one the
     original cosim measured (`tinytpu_isa.result.lat.rb`) -- if SAIF logging
     moved the cycle count, that is a bug in the instrumentation, not a result;
  2. the RTL output vectors still match the C golden vectors, i.e. the
     re-simulation computed the same answer;
  3. the SAIF names nets INSIDE the DUT instance, not only the testbench's;
  4. the toggle counts are not all zero.

USAGE

    python cosim.py                      # leaves isa_sweep.prj behind
    python saif_capture.py isa_sweep.prj

    # the two handoff configurations, each from its own project:
    TPU_MAXDIM=16          TPU_SHAPES=16x16x16 TPU_PRJ=$PWD/saif_t4.prj python cosim.py
    python saif_capture.py saif_t4.prj -o /path/T4_MAXDIM16_16x16x16/run.saif
    TPU_T=8 TPU_MAXDIM=64  TPU_SHAPES=16x16x16 TPU_PRJ=$PWD/saif_t8.prj python cosim.py
    python saif_capture.py saif_t8.prj -o /path/T8_MAXDIM64_16x16x16/run.saif

THE INSTANCE PATH, which a downstream `read_saif` needs. Vitis wraps the design
in `apatb_*`: the elaboration top is `apatb_tinytpu_isa_top` and the design sits
under it as `AESL_inst_tinytpu_isa`, so the SAIF's hierarchy begins

    apatb_tinytpu_isa_top/AESL_inst_tinytpu_isa

and that is the string for `read_saif -map_names -instance_name`. It is printed
by every run, read out of the SAIF that was actually written rather than
assumed, because the wrapper naming is Vitis's to change.
"""

import argparse
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VITIS_SETTINGS = "/opt/xilinx/Vitis_HLS/2023.2/settings64.sh"
TOP = "apatb_tinytpu_isa_top"
DUT_INST = "AESL_inst_tinytpu_isa"
DUT_PATH = f"/{TOP}/{DUT_INST}"

#: `-debug typical` is what makes the design's internal nets visible to
#: `get_objects`; Vitis's own `-trace_level none` elaboration has no debug at
#: all and `log_saif` would then see nothing. It is pure observability -- it
#: adds no logic and changes no timing -- and check (1) above is what holds
#: that claim to evidence rather than to belief.
DEBUG_LEVEL = "typical"


class CaptureError(Exception):
    pass


def _simdir(prj):
    d = os.path.join(prj, "out.prj/solution1/sim/verilog")
    if not os.path.isdir(d):
        raise CaptureError(
            f"{d} does not exist: run `cosim.py` on this project first. "
            f"This script instruments an existing cosim, it does not run one.")
    if not os.path.isfile(os.path.join(d, "run_xsim.sh")):
        raise CaptureError(f"{d}/run_xsim.sh is missing (unfinished cosim?)")
    return d


def _derive_xsim_sh(sim, tcl_name, snapshot):
    """A copy of Vitis's own `run_xsim.sh` with the snapshot renamed, debug
    turned on and our tclbatch substituted. Derived, never edited in place:
    the original is regenerated by the next `cosim_design` and must keep
    producing the published cycle count untouched."""
    src = open(os.path.join(sim, "run_xsim.sh")).read()
    out, n1 = re.subn(r"-s tinytpu_isa\s*$",
                      f"-s {snapshot} -debug {DEBUG_LEVEL}", src, flags=re.M)
    out, n2 = re.subn(r"xsim (--\S+ )?tinytpu_isa -tclbatch \S+",
                      lambda m: f"xsim {m.group(1) or ''}{snapshot} "
                                f"-tclbatch {tcl_name}", out)
    if n1 != 1 or n2 != 1:
        raise CaptureError(
            f"could not rewrite run_xsim.sh (xelab match {n1}, xsim match "
            f"{n2}; both must be 1). Vitis changed the script's shape; fix "
            f"the patterns rather than editing run_xsim.sh by hand.")
    path = os.path.join(sim, "saif_xsim.sh")
    open(path, "w").write(out)
    return path


def _saif_stats(path):
    """Walk the SAIF and return what the checks below need.

    The hierarchy is recovered from the indentation, three spaces per level,
    so an `(INSTANCE` at indentation level `d` replaces everything from index
    `d-1` of the running path. Getting that off by one produces paths that
    look right at the top and are nonsense underneath (`pe_3_3_U0` shown as a
    child of its own sibling), which is why the per-instance breakdown, not
    just the total, is what this returns: a wrong walk is visible in it.
    """
    inst = nets = nz = toggles = 0
    duration = None
    stack, cur, dut_path = [], None, None
    per = {}                      # instance path -> [nets, toggling, toggles]
    tc = re.compile(r"\(TC (\d+)\)")
    with open(path, errors="replace") as fh:
        for line in fh:
            s = line.strip()
            if s.startswith("(DURATION"):
                duration = int(re.findall(r"\d+", s)[0])
            if s.startswith("(INSTANCE"):
                name = s.split()[1]
                depth = (len(line) - len(line.lstrip())) // 3
                stack = stack[:max(depth - 1, 0)] + [name]
                cur = "/".join(stack)
                per.setdefault(cur, [0, 0, 0])
                inst += 1
                if name == DUT_INST and dut_path is None:
                    dut_path = cur
            m = tc.search(s)
            if m:
                nets += 1
                v = int(m.group(1))
                per[cur][0] += 1
                if v:
                    nz += 1
                    toggles += v
                    per[cur][1] += 1
                    per[cur][2] += v
    return inst, nets, nz, toggles, duration, dut_path, per


def check_activity(saif):
    """Refuse a SAIF that would annotate cleanly and mean nothing.

    Separate from `capture` and taking only a path, so `--selftest` can feed
    it the three files it is meant to reject. A check nobody has watched fail
    is not evidence that it fires.
    """
    inst, nets, nz, toggles, duration, dut_path, per = _saif_stats(saif)
    if dut_path is None:
        raise CaptureError(
            f"{saif} names no `{DUT_INST}` instance: it holds the testbench's "
            f"nets only, and would annotate nothing in the design.")
    if inst < 2 or nets == 0:
        raise CaptureError(f"{saif} is effectively empty "
                           f"({inst} instances, {nets} nets)")
    if nz == 0:
        raise CaptureError(
            f"{saif} has {nets} nets and NOT ONE nonzero toggle count. A "
            f"zero-activity SAIF annotates cleanly and produces a beautiful "
            f"meaningless power number; refusing to report it as produced.")
    inside = {k: v for k, v in per.items() if k.startswith(dut_path + "/")}
    deep = sum(v[2] for v in inside.values())
    if not inside or deep == 0:
        raise CaptureError(
            f"{saif} has activity only on the DUT's own ports and none in any "
            f"of its submodules: nothing inside the design would be "
            f"annotated. ({len(inside)} submodule instances, {deep} toggles.)")
    return {"instances": inst, "nets": nets, "toggling_nets": nz,
            "toggles": toggles, "duration_ps": duration,
            "instance_path": dut_path, "inside": inside, "deep_toggles": deep}


#: Three SAIFs that a downstream `read_saif` would swallow without complaint
#: and that must NOT be reported as produced: one with the wrapper only, one
#: with the design present but every count zero, and one with activity on the
#: DUT's ports and nothing inside it. Each names the check it is aimed at.
_BAD_SAIFS = [
    ("wrapper only", "holds the testbench's nets only", """(SAIFILE
   (DURATION  1000)
   (INSTANCE  {top}
      (NET
         (ap_clk (T0 500) (T1 500) (TX 0) (TZ 0) (TB 0) (TC 300))
      )
   )
)"""),
    ("all zero", "NOT ONE nonzero toggle count", """(SAIFILE
   (DURATION  1000)
   (INSTANCE  {top}
      (INSTANCE  {dut}
         (NET
            (ap_clk (T0 1000) (T1 0) (TX 0) (TZ 0) (TB 0) (TC 0))
         )
         (INSTANCE  pe_0_0_U0
            (NET
               (x (T0 1000) (T1 0) (TX 0) (TZ 0) (TB 0) (TC 0))
            )
         )
      )
   )
)"""),
    ("ports only", "none in any of its submodules", """(SAIFILE
   (DURATION  1000)
   (INSTANCE  {top}
      (INSTANCE  {dut}
         (NET
            (ap_clk (T0 500) (T1 500) (TX 0) (TZ 0) (TB 0) (TC 300))
         )
         (INSTANCE  pe_0_0_U0
            (NET
               (x (T0 1000) (T1 0) (TX 0) (TZ 0) (TB 0) (TC 0))
            )
         )
      )
   )
)"""),
]


def selftest():
    """Show each guard rejecting the file it exists for, and a good file pass."""
    import tempfile
    ok = True
    good = """(SAIFILE
   (DURATION  1000)
   (INSTANCE  {top}
      (INSTANCE  {dut}
         (NET
            (ap_clk (T0 500) (T1 500) (TX 0) (TZ 0) (TB 0) (TC 300))
         )
         (INSTANCE  pe_0_0_U0
            (NET
               (x (T0 600) (T1 400) (TX 0) (TZ 0) (TB 0) (TC 47))
            )
         )
      )
   )
)"""
    with tempfile.TemporaryDirectory() as d:
        for name, want, body in _BAD_SAIFS:
            p = os.path.join(d, "bad.saif")
            open(p, "w").write(body.format(top=TOP, dut=DUT_INST))
            try:
                check_activity(p)
            except CaptureError as e:
                hit = want in str(e)
                print(f"  {'rejected' if hit else 'REJECTED, WRONG REASON'}"
                      f"  {name}")
                ok &= hit
            else:
                print(f"  ACCEPTED (should not be)  {name}")
                ok = False
        p = os.path.join(d, "good.saif")
        open(p, "w").write(good.format(top=TOP, dut=DUT_INST))
        try:
            r = check_activity(p)
            print(f"  accepted  a well-formed one "
                  f"({r['deep_toggles']} transitions inside the DUT)")
        except CaptureError as e:
            print(f"  REJECTED a well-formed one: {e}")
            ok = False
    print("  SAIF SELFTEST " + ("OK" if ok else "FAILED"))
    return 0 if ok else 1


def _tvout_matches(prj):
    """Did the re-simulation compute the same answer the C model did?"""
    tv = os.path.join(prj, "out.prj/solution1/sim/tv")
    c = os.path.join(tv, "cdatafile/c.tinytpu_isa.autotvout_gmem3.dat")
    r = os.path.join(tv, "rtldatafile/rtl.tinytpu_isa.autotvout_gmem3.dat")
    if not (os.path.isfile(c) and os.path.isfile(r)):
        return None
    strip = lambda p: [l for l in open(p, errors="replace")
                       if not l.startswith(("[[", "]]"))]
    return strip(c) == strip(r)


def capture(prj, out=None):
    prj = os.path.abspath(prj)
    sim = _simdir(prj)
    lat = os.path.join(sim, "tinytpu_isa.result.lat.rb")
    if not os.path.isfile(lat):
        raise CaptureError(
            f"{lat} is missing: the cosim in {prj} never produced a latency, "
            f"so there is no cycle count for the SAIF run to be checked "
            f"against. Re-run cosim.py.")
    before = open(lat).read()

    saif = os.path.join(sim, "run.saif")
    if os.path.exists(saif):
        os.remove(saif)
    tcl = os.path.join(sim, "saif_dump.tcl")
    open(tcl, "w").write(
        f"current_scope {DUT_PATH}\n"
        f"set objs [get_objects -r *]\n"
        f'puts "SAIF-OBJECTS: [llength $objs]"\n'
        f'open_saif "run.saif"\n'
        f"log_saif $objs\n"
        f"run all\n"
        f"close_saif\n"
        f"quit\n")
    _derive_xsim_sh(sim, "saif_dump.tcl", "tinytpu_isa_dbg")

    log = os.path.join(sim, "saif_xsim.log")
    with open(log, "w") as fh:
        rc = subprocess.call(
            ["bash", "-lc",
             # RDI_USE_JDK11 is what Vitis's own run_sim.tcl unsets around
             # this call; xsim fails to start with it set.
             f"source {VITIS_SETTINGS} >/dev/null && unset RDI_USE_JDK11 && "
             f"cd {sim} && sh ./saif_xsim.sh"],
            stdout=fh, stderr=subprocess.STDOUT)
    text = open(log, errors="replace").read()
    if rc != 0 or not os.path.exists(saif):
        tail = "\n".join(text.splitlines()[-25:])
        raise CaptureError(f"xsim SAIF run failed (rc={rc}); tail:\n{tail}")

    # ---- THE CHECKS ----
    after = open(lat).read()
    cyc = re.findall(r'\$TOTAL_EXECUTE_TIME = "(\d+)"', after)
    if after != before:
        raise CaptureError(
            "the SAIF run's latency differs from the cosim's.\n"
            f"  cosim: {before.strip()}\n  saif : {after.strip()}\n"
            "SAIF logging must not move the cycle count; that is a bug in "
            "this instrumentation, not a new result.")
    stats = check_activity(saif)
    inst, nets, nz = stats["instances"], stats["nets"], stats["toggling_nets"]
    toggles, duration = stats["toggles"], stats["duration_ps"]
    dut_path, inside, deep = (stats["instance_path"], stats["inside"],
                              stats["deep_toggles"])
    tv = _tvout_matches(prj)
    if tv is False:
        raise CaptureError(
            "the SAIF re-simulation's RTL output vectors no longer match the "
            "C golden vectors: it did not compute the workload we quote.")

    if out:
        os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
        with open(saif, "rb") as a, open(out, "wb") as b:
            b.write(a.read())
    final = os.path.abspath(out) if out else saif
    # `saif_dump.tcl`, `saif_xsim.sh` and `saif_xsim.log` are left in the sim
    # directory on purpose: they are the record of how this SAIF was made, and
    # they cost nothing next to the project they sit in.
    return {
        "saif": final,
        "bytes": os.path.getsize(final),
        "instance_path": dut_path,
        "cycles": int(cyc[0]) if cyc else None,
        "instances": inst, "nets": nets, "toggling_nets": nz,
        "toggles": toggles, "duration_ps": duration,
        "submodules": len(inside), "deep_toggles": deep,
        "hottest": sorted(inside.items(), key=lambda kv: -kv[1][2])[:8],
        "dut_prefix": dut_path,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("project", nargs="?",
                    help="a project cosim.py has already run in")
    ap.add_argument("-o", "--out", help="copy the SAIF here")
    ap.add_argument("--selftest", action="store_true",
                    help="show the content guards rejecting bad SAIFs "
                         "(no Vitis, no simulation, seconds)")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    if not args.project:
        ap.error("a project is required (or --selftest)")
    try:
        r = capture(args.project, args.out)
    except CaptureError as e:
        print(f"SAIF CAPTURE FAILED\n{e}", file=sys.stderr)
        return 1
    clk = 3.33
    print(f"  SAIF            {r['saif']}")
    print(f"  size            {r['bytes'] / 1e6:.1f} MB")
    print(f"  DUT instance    {r['instance_path']}")
    print(f"  cycles          {r['cycles']} (identical to the cosim's)")
    print(f"  window          {r['duration_ps']} ps "
          f"= {r['duration_ps'] / (clk * 1000):.1f} clocks at {clk} ns")
    print(f"  hierarchy       {r['instances']} instances, {r['nets']} nets")
    print(f"  activity        {r['toggling_nets']} nets toggle, "
          f"{r['toggles']} transitions total")
    print(f"  inside the DUT  {r['submodules']} submodule instances, "
          f"{r['deep_toggles']} transitions "
          f"({100.0 * r['deep_toggles'] / r['toggles']:.0f}% of the total)")
    print("  hottest blocks  (a SAIF that annotates cleanly but is empty or "
          "all-testbench is the failure this guards against)")
    n = len(r["dut_prefix"]) + 1
    for k, v in r["hottest"]:
        print(f"    {v[2]:>9}  {v[1]:>5}/{v[0]:<6} nets  {k[n:]}")
    print("  SAIF OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
