// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_dma_ld_0_1_Pipeline_VITIS_LOOP_654_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        empty,
        sext_ln654,
        rbA_15_address0,
        rbA_15_ce0,
        rbA_15_we0,
        rbA_15_d0,
        rbA_14_address0,
        rbA_14_ce0,
        rbA_14_we0,
        rbA_14_d0,
        rbA_13_address0,
        rbA_13_ce0,
        rbA_13_we0,
        rbA_13_d0,
        rbA_12_address0,
        rbA_12_ce0,
        rbA_12_we0,
        rbA_12_d0,
        rbA_11_address0,
        rbA_11_ce0,
        rbA_11_we0,
        rbA_11_d0,
        rbA_10_address0,
        rbA_10_ce0,
        rbA_10_we0,
        rbA_10_d0,
        rbA_9_address0,
        rbA_9_ce0,
        rbA_9_we0,
        rbA_9_d0,
        rbA_8_address0,
        rbA_8_ce0,
        rbA_8_we0,
        rbA_8_d0,
        rbA_7_address0,
        rbA_7_ce0,
        rbA_7_we0,
        rbA_7_d0,
        rbA_6_address0,
        rbA_6_ce0,
        rbA_6_we0,
        rbA_6_d0,
        rbA_5_address0,
        rbA_5_ce0,
        rbA_5_we0,
        rbA_5_d0,
        rbA_4_address0,
        rbA_4_ce0,
        rbA_4_we0,
        rbA_4_d0,
        rbA_3_address0,
        rbA_3_ce0,
        rbA_3_we0,
        rbA_3_d0,
        rbA_2_address0,
        rbA_2_ce0,
        rbA_2_we0,
        rbA_2_d0,
        rbA_1_address0,
        rbA_1_ce0,
        rbA_1_we0,
        rbA_1_d0,
        rbA_address0,
        rbA_ce0,
        rbA_we0,
        rbA_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [511:0] m_axi_gmem1_WDATA;
output  [63:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [511:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [15:0] empty;
input  [57:0] sext_ln654;
output  [6:0] rbA_15_address0;
output   rbA_15_ce0;
output   rbA_15_we0;
output  [31:0] rbA_15_d0;
output  [6:0] rbA_14_address0;
output   rbA_14_ce0;
output   rbA_14_we0;
output  [31:0] rbA_14_d0;
output  [6:0] rbA_13_address0;
output   rbA_13_ce0;
output   rbA_13_we0;
output  [31:0] rbA_13_d0;
output  [6:0] rbA_12_address0;
output   rbA_12_ce0;
output   rbA_12_we0;
output  [31:0] rbA_12_d0;
output  [6:0] rbA_11_address0;
output   rbA_11_ce0;
output   rbA_11_we0;
output  [31:0] rbA_11_d0;
output  [6:0] rbA_10_address0;
output   rbA_10_ce0;
output   rbA_10_we0;
output  [31:0] rbA_10_d0;
output  [6:0] rbA_9_address0;
output   rbA_9_ce0;
output   rbA_9_we0;
output  [31:0] rbA_9_d0;
output  [6:0] rbA_8_address0;
output   rbA_8_ce0;
output   rbA_8_we0;
output  [31:0] rbA_8_d0;
output  [6:0] rbA_7_address0;
output   rbA_7_ce0;
output   rbA_7_we0;
output  [31:0] rbA_7_d0;
output  [6:0] rbA_6_address0;
output   rbA_6_ce0;
output   rbA_6_we0;
output  [31:0] rbA_6_d0;
output  [6:0] rbA_5_address0;
output   rbA_5_ce0;
output   rbA_5_we0;
output  [31:0] rbA_5_d0;
output  [6:0] rbA_4_address0;
output   rbA_4_ce0;
output   rbA_4_we0;
output  [31:0] rbA_4_d0;
output  [6:0] rbA_3_address0;
output   rbA_3_ce0;
output   rbA_3_we0;
output  [31:0] rbA_3_d0;
output  [6:0] rbA_2_address0;
output   rbA_2_ce0;
output   rbA_2_we0;
output  [31:0] rbA_2_d0;
output  [6:0] rbA_1_address0;
output   rbA_1_ce0;
output   rbA_1_we0;
output  [31:0] rbA_1_d0;
output  [6:0] rbA_address0;
output   rbA_ce0;
output   rbA_we0;
output  [31:0] rbA_d0;

reg ap_idle;
reg m_axi_gmem1_RREADY;
reg rbA_15_ce0;
reg rbA_15_we0;
reg rbA_14_ce0;
reg rbA_14_we0;
reg rbA_13_ce0;
reg rbA_13_we0;
reg rbA_12_ce0;
reg rbA_12_we0;
reg rbA_11_ce0;
reg rbA_11_we0;
reg rbA_10_ce0;
reg rbA_10_we0;
reg rbA_9_ce0;
reg rbA_9_we0;
reg rbA_8_ce0;
reg rbA_8_we0;
reg rbA_7_ce0;
reg rbA_7_we0;
reg rbA_6_ce0;
reg rbA_6_we0;
reg rbA_5_ce0;
reg rbA_5_we0;
reg rbA_4_ce0;
reg rbA_4_we0;
reg rbA_3_ce0;
reg rbA_3_we0;
reg rbA_2_ce0;
reg rbA_2_we0;
reg rbA_1_ce0;
reg rbA_1_we0;
reg rbA_ce0;
reg rbA_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln654_fu_377_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] trunc_ln710_fu_389_p1;
reg   [6:0] trunc_ln710_reg_593;
reg   [6:0] trunc_ln710_reg_593_pp0_iter1_reg;
wire   [31:0] v392_tmp_fu_404_p1;
reg   [31:0] v392_tmp_reg_598;
reg   [31:0] v422_tmp_reg_603;
reg   [31:0] v451_tmp_reg_608;
reg   [31:0] v480_tmp_reg_613;
reg   [31:0] v509_tmp_reg_618;
reg   [31:0] v538_tmp_reg_623;
reg   [31:0] v567_tmp_reg_628;
reg   [31:0] v596_tmp_reg_633;
reg   [31:0] v625_tmp_reg_638;
reg   [31:0] v654_tmp_reg_643;
reg   [31:0] v683_tmp_reg_648;
reg   [31:0] v712_tmp_reg_653;
reg   [31:0] v741_tmp_reg_658;
reg   [31:0] v770_tmp_reg_663;
reg   [31:0] v799_tmp_reg_668;
reg   [31:0] v828_tmp_reg_673;
wire   [63:0] zext_ln710_fu_558_p1;
reg   [15:0] v365_fu_136;
wire   [15:0] add_ln654_fu_383_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_v364;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 v365_fu_136 = 16'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln654_fu_377_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            v365_fu_136 <= add_ln654_fu_383_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            v365_fu_136 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        trunc_ln710_reg_593 <= trunc_ln710_fu_389_p1;
        trunc_ln710_reg_593_pp0_iter1_reg <= trunc_ln710_reg_593;
        v392_tmp_reg_598 <= v392_tmp_fu_404_p1;
        v422_tmp_reg_603 <= {{m_axi_gmem1_RDATA[63:32]}};
        v451_tmp_reg_608 <= {{m_axi_gmem1_RDATA[95:64]}};
        v480_tmp_reg_613 <= {{m_axi_gmem1_RDATA[127:96]}};
        v509_tmp_reg_618 <= {{m_axi_gmem1_RDATA[159:128]}};
        v538_tmp_reg_623 <= {{m_axi_gmem1_RDATA[191:160]}};
        v567_tmp_reg_628 <= {{m_axi_gmem1_RDATA[223:192]}};
        v596_tmp_reg_633 <= {{m_axi_gmem1_RDATA[255:224]}};
        v625_tmp_reg_638 <= {{m_axi_gmem1_RDATA[287:256]}};
        v654_tmp_reg_643 <= {{m_axi_gmem1_RDATA[319:288]}};
        v683_tmp_reg_648 <= {{m_axi_gmem1_RDATA[351:320]}};
        v712_tmp_reg_653 <= {{m_axi_gmem1_RDATA[383:352]}};
        v741_tmp_reg_658 <= {{m_axi_gmem1_RDATA[415:384]}};
        v770_tmp_reg_663 <= {{m_axi_gmem1_RDATA[447:416]}};
        v799_tmp_reg_668 <= {{m_axi_gmem1_RDATA[479:448]}};
        v828_tmp_reg_673 <= {{m_axi_gmem1_RDATA[511:480]}};
    end
end

always @ (*) begin
    if (((icmp_ln654_fu_377_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_v364 = 16'd0;
    end else begin
        ap_sig_allocacmp_v364 = v365_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_10_ce0 = 1'b1;
    end else begin
        rbA_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_10_we0 = 1'b1;
    end else begin
        rbA_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_11_ce0 = 1'b1;
    end else begin
        rbA_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_11_we0 = 1'b1;
    end else begin
        rbA_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_12_ce0 = 1'b1;
    end else begin
        rbA_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_12_we0 = 1'b1;
    end else begin
        rbA_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_13_ce0 = 1'b1;
    end else begin
        rbA_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_13_we0 = 1'b1;
    end else begin
        rbA_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_14_ce0 = 1'b1;
    end else begin
        rbA_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_14_we0 = 1'b1;
    end else begin
        rbA_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_15_ce0 = 1'b1;
    end else begin
        rbA_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_15_we0 = 1'b1;
    end else begin
        rbA_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_1_ce0 = 1'b1;
    end else begin
        rbA_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_1_we0 = 1'b1;
    end else begin
        rbA_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_2_ce0 = 1'b1;
    end else begin
        rbA_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_2_we0 = 1'b1;
    end else begin
        rbA_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_3_ce0 = 1'b1;
    end else begin
        rbA_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_3_we0 = 1'b1;
    end else begin
        rbA_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_4_ce0 = 1'b1;
    end else begin
        rbA_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_4_we0 = 1'b1;
    end else begin
        rbA_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_5_ce0 = 1'b1;
    end else begin
        rbA_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_5_we0 = 1'b1;
    end else begin
        rbA_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_6_ce0 = 1'b1;
    end else begin
        rbA_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_6_we0 = 1'b1;
    end else begin
        rbA_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_7_ce0 = 1'b1;
    end else begin
        rbA_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_7_we0 = 1'b1;
    end else begin
        rbA_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_8_ce0 = 1'b1;
    end else begin
        rbA_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_8_we0 = 1'b1;
    end else begin
        rbA_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_9_ce0 = 1'b1;
    end else begin
        rbA_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_9_we0 = 1'b1;
    end else begin
        rbA_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_ce0 = 1'b1;
    end else begin
        rbA_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rbA_we0 = 1'b1;
    end else begin
        rbA_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln654_fu_383_p2 = (ap_sig_allocacmp_v364 + 16'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln654_fu_377_p2 = ((ap_sig_allocacmp_v364 == empty) ? 1'b1 : 1'b0);

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 512'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 64'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign rbA_10_address0 = zext_ln710_fu_558_p1;

assign rbA_10_d0 = v683_tmp_reg_648;

assign rbA_11_address0 = zext_ln710_fu_558_p1;

assign rbA_11_d0 = v712_tmp_reg_653;

assign rbA_12_address0 = zext_ln710_fu_558_p1;

assign rbA_12_d0 = v741_tmp_reg_658;

assign rbA_13_address0 = zext_ln710_fu_558_p1;

assign rbA_13_d0 = v770_tmp_reg_663;

assign rbA_14_address0 = zext_ln710_fu_558_p1;

assign rbA_14_d0 = v799_tmp_reg_668;

assign rbA_15_address0 = zext_ln710_fu_558_p1;

assign rbA_15_d0 = v828_tmp_reg_673;

assign rbA_1_address0 = zext_ln710_fu_558_p1;

assign rbA_1_d0 = v422_tmp_reg_603;

assign rbA_2_address0 = zext_ln710_fu_558_p1;

assign rbA_2_d0 = v451_tmp_reg_608;

assign rbA_3_address0 = zext_ln710_fu_558_p1;

assign rbA_3_d0 = v480_tmp_reg_613;

assign rbA_4_address0 = zext_ln710_fu_558_p1;

assign rbA_4_d0 = v509_tmp_reg_618;

assign rbA_5_address0 = zext_ln710_fu_558_p1;

assign rbA_5_d0 = v538_tmp_reg_623;

assign rbA_6_address0 = zext_ln710_fu_558_p1;

assign rbA_6_d0 = v567_tmp_reg_628;

assign rbA_7_address0 = zext_ln710_fu_558_p1;

assign rbA_7_d0 = v596_tmp_reg_633;

assign rbA_8_address0 = zext_ln710_fu_558_p1;

assign rbA_8_d0 = v625_tmp_reg_638;

assign rbA_9_address0 = zext_ln710_fu_558_p1;

assign rbA_9_d0 = v654_tmp_reg_643;

assign rbA_address0 = zext_ln710_fu_558_p1;

assign rbA_d0 = v392_tmp_reg_598;

assign trunc_ln710_fu_389_p1 = ap_sig_allocacmp_v364[6:0];

assign v392_tmp_fu_404_p1 = m_axi_gmem1_RDATA[31:0];

assign zext_ln710_fu_558_p1 = trunc_ln710_reg_593_pp0_iter1_reg;

endmodule //tinytpu_isa_dma_ld_0_1_Pipeline_VITIS_LOOP_654_1
