# Copyright / scratch: walk a tiny Allo kernel through the IR stages.
# Run inside the `allo` conda env from the allo repo root.
#
# It prints (and returns as strings) the MLIR/HLS at four observable stages:
#   Stage 0 : frontend MLIR right after allo.customize()  (allo + std dialects)
#   Stage 1 : after applying a schedule primitive          (a new allo.* op appears)
#   Stage 2 : after the loop_transformation lowering pass   (schedule ops consumed)
#   Stage 3 : emitted Vivado/Vitis HLS C++                  (translation, not a pass)
import io
import allo
from allo.ir.types import int32
from allo.passes import _mlir_lower_pipeline
from allo._mlir.dialects import allo as allo_d


# ----------------------------------------------------------------------------
# A deliberately tiny kernel: vector add of two length-8 int32 arrays.
# Small enough that the whole module fits on screen at every stage.
# ----------------------------------------------------------------------------
def vadd(A: int32[8], B: int32[8]) -> int32[8]:
    C: int32[8]
    for i in range(8):
        C[i] = A[i] + B[i]
    return C


def banner(title):
    line = "=" * 78
    return f"\n{line}\n{title}\n{line}\n"


chunks = []


def emit(title, text):
    block = banner(title) + text.rstrip() + "\n"
    chunks.append(block)
    print(block)


# ----------------------------------------------------------------------------
# Stage 0 -- frontend MLIR. allo.customize() runs the Python AST -> MLIR builder
# (allo/ir/builder.py). No optimization yet: this is the raw dialect emission.
# Look for: affine.for loops, memref.alloc, arith.addi, func.func -- and the
# allo dialect only shows up once we add a schedule directive (Stage 1).
# ----------------------------------------------------------------------------
sch = allo.customize(vadd)
emit("STAGE 0  --  Frontend MLIR (raw, straight out of allo/ir/builder.py)",
     str(sch.module))

# ----------------------------------------------------------------------------
# Stage 1 -- apply ONE schedule primitive. customize.py turns .pipeline(...)
# into an `allo.pipeline` op attached to the loop handle. Diff against Stage 0
# to see exactly which op the primitive injected -- this is the whole point of
# the schedule layer: directives live IN the IR as allo.* ops until a pass
# consumes them.
# ----------------------------------------------------------------------------
sch.pipeline("i", initiation_interval=1)
emit("STAGE 1  --  After sch.pipeline('i')  (an allo.pipeline op is now attached)",
     str(sch.module))

# ----------------------------------------------------------------------------
# Stage 2 -- run the loop_transformation lowering pass (allo_d.loop_transformation
# inside _mlir_lower_pipeline). The schedule op from Stage 1 is now CONSUMED: the
# pipeline directive is applied and re-expressed as a loop attribute the backend
# understands. This is the allo.* -> std lowering boundary.
# ----------------------------------------------------------------------------
_mlir_lower_pipeline(sch.module)
emit("STAGE 2  --  After loop_transformation pass  (schedule op consumed/applied)",
     str(sch.module))

# ----------------------------------------------------------------------------
# Stage 3 -- TRANSLATION (not a pass): walk the optimized MLIR and print HLS C++.
# This is lib/Translation/EmitVivadoHLS.cpp, invoked via allo_d.emit_vhls.
# This is the terminal artifact the Vitis flow compiles.
# ----------------------------------------------------------------------------
buf = io.StringIO()
ok = allo_d.emit_vhls(sch.module, buf, flatten=False)
buf.seek(0)
emit("STAGE 3  --  Emitted Vivado/Vitis HLS C++ (EmitVivadoHLS.cpp translation)",
     buf.read() if ok else "<<emit_vhls failed>>")

# ----------------------------------------------------------------------------
# Write everything to the extension folder.
# ----------------------------------------------------------------------------
OUT = "/home/zsm9/pe_core_implementation/Allo_extension/IR_STAGES_WALKTHROUGH.txt"
header = (
    "Allo IR stage-by-stage walkthrough\n"
    "Generated by allo_sup/dump_ir_stages.py on the `vadd` toy kernel.\n"
    "Read top-to-bottom: same program, four progressively-lower representations.\n"
)
with open(OUT, "w") as f:
    f.write(header)
    f.write("".join(chunks))
print(f"\n[written] {OUT}")
