// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dot_tree_8_2_dot_sink_0_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        v248_dout,
        v248_num_data_valid,
        v248_fifo_cap,
        v248_empty_n,
        v248_read,
        m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY,
        m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY,
        m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST,
        m_axi_gmem4_WID,
        m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST,
        m_axi_gmem4_RID,
        m_axi_gmem4_RFIFONUM,
        m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID,
        m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP,
        m_axi_gmem4_BID,
        m_axi_gmem4_BUSER,
        v249_dout,
        v249_num_data_valid,
        v249_fifo_cap,
        v249_empty_n,
        v249_read,
        v281_dout,
        v281_num_data_valid,
        v281_fifo_cap,
        v281_empty_n,
        v281_read,
        v283_dout,
        v283_num_data_valid,
        v283_fifo_cap,
        v283_empty_n,
        v283_read,
        v284_dout,
        v284_num_data_valid,
        v284_fifo_cap,
        v284_empty_n,
        v284_read
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [31:0] m_axi_gmem3_WDATA;
output  [3:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [31:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [63:0] v248_dout;
input  [2:0] v248_num_data_valid;
input  [2:0] v248_fifo_cap;
input   v248_empty_n;
output   v248_read;
output   m_axi_gmem4_AWVALID;
input   m_axi_gmem4_AWREADY;
output  [63:0] m_axi_gmem4_AWADDR;
output  [0:0] m_axi_gmem4_AWID;
output  [31:0] m_axi_gmem4_AWLEN;
output  [2:0] m_axi_gmem4_AWSIZE;
output  [1:0] m_axi_gmem4_AWBURST;
output  [1:0] m_axi_gmem4_AWLOCK;
output  [3:0] m_axi_gmem4_AWCACHE;
output  [2:0] m_axi_gmem4_AWPROT;
output  [3:0] m_axi_gmem4_AWQOS;
output  [3:0] m_axi_gmem4_AWREGION;
output  [0:0] m_axi_gmem4_AWUSER;
output   m_axi_gmem4_WVALID;
input   m_axi_gmem4_WREADY;
output  [31:0] m_axi_gmem4_WDATA;
output  [3:0] m_axi_gmem4_WSTRB;
output   m_axi_gmem4_WLAST;
output  [0:0] m_axi_gmem4_WID;
output  [0:0] m_axi_gmem4_WUSER;
output   m_axi_gmem4_ARVALID;
input   m_axi_gmem4_ARREADY;
output  [63:0] m_axi_gmem4_ARADDR;
output  [0:0] m_axi_gmem4_ARID;
output  [31:0] m_axi_gmem4_ARLEN;
output  [2:0] m_axi_gmem4_ARSIZE;
output  [1:0] m_axi_gmem4_ARBURST;
output  [1:0] m_axi_gmem4_ARLOCK;
output  [3:0] m_axi_gmem4_ARCACHE;
output  [2:0] m_axi_gmem4_ARPROT;
output  [3:0] m_axi_gmem4_ARQOS;
output  [3:0] m_axi_gmem4_ARREGION;
output  [0:0] m_axi_gmem4_ARUSER;
input   m_axi_gmem4_RVALID;
output   m_axi_gmem4_RREADY;
input  [31:0] m_axi_gmem4_RDATA;
input   m_axi_gmem4_RLAST;
input  [0:0] m_axi_gmem4_RID;
input  [8:0] m_axi_gmem4_RFIFONUM;
input  [0:0] m_axi_gmem4_RUSER;
input  [1:0] m_axi_gmem4_RRESP;
input   m_axi_gmem4_BVALID;
output   m_axi_gmem4_BREADY;
input  [1:0] m_axi_gmem4_BRESP;
input  [0:0] m_axi_gmem4_BID;
input  [0:0] m_axi_gmem4_BUSER;
input  [63:0] v249_dout;
input  [2:0] v249_num_data_valid;
input  [2:0] v249_fifo_cap;
input   v249_empty_n;
output   v249_read;
input  [63:0] v281_dout;
input  [3:0] v281_num_data_valid;
input  [3:0] v281_fifo_cap;
input   v281_empty_n;
output   v281_read;
input  [31:0] v283_dout;
input  [3:0] v283_num_data_valid;
input  [3:0] v283_fifo_cap;
input   v283_empty_n;
output   v283_read;
input  [63:0] v284_dout;
input  [3:0] v284_num_data_valid;
input  [3:0] v284_fifo_cap;
input   v284_empty_n;
output   v284_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem3_AWVALID;
reg[63:0] m_axi_gmem3_AWADDR;
reg[0:0] m_axi_gmem3_AWID;
reg[31:0] m_axi_gmem3_AWLEN;
reg[2:0] m_axi_gmem3_AWSIZE;
reg[1:0] m_axi_gmem3_AWBURST;
reg[1:0] m_axi_gmem3_AWLOCK;
reg[3:0] m_axi_gmem3_AWCACHE;
reg[2:0] m_axi_gmem3_AWPROT;
reg[3:0] m_axi_gmem3_AWQOS;
reg[3:0] m_axi_gmem3_AWREGION;
reg[0:0] m_axi_gmem3_AWUSER;
reg m_axi_gmem3_WVALID;
reg m_axi_gmem3_BREADY;
reg v248_read;
reg m_axi_gmem4_AWVALID;
reg[63:0] m_axi_gmem4_AWADDR;
reg[0:0] m_axi_gmem4_AWID;
reg[31:0] m_axi_gmem4_AWLEN;
reg[2:0] m_axi_gmem4_AWSIZE;
reg[1:0] m_axi_gmem4_AWBURST;
reg[1:0] m_axi_gmem4_AWLOCK;
reg[3:0] m_axi_gmem4_AWCACHE;
reg[2:0] m_axi_gmem4_AWPROT;
reg[3:0] m_axi_gmem4_AWQOS;
reg[3:0] m_axi_gmem4_AWREGION;
reg[0:0] m_axi_gmem4_AWUSER;
reg m_axi_gmem4_WVALID;
reg m_axi_gmem4_BREADY;
reg v249_read;
reg v281_read;
reg v283_read;
reg v284_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem3_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    gmem3_blk_n_B;
wire    ap_CS_fsm_state9;
reg    v248_blk_n;
reg    gmem4_blk_n_AW;
reg    gmem4_blk_n_B;
reg    v249_blk_n;
reg    v281_blk_n;
wire   [15:0] v255_fu_113_p1;
reg   [15:0] v255_reg_187;
reg    ap_block_state1;
reg   [61:0] trunc_ln_reg_193;
wire   [16:0] empty_fu_141_p3;
reg   [16:0] empty_reg_199;
reg   [61:0] trunc_ln447_1_reg_204;
reg    ap_block_state2_io;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_done;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_idle;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_ready;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_v283_read;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_v284_read;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWVALID;
wire   [63:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWADDR;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWID;
wire   [31:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWLEN;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWSIZE;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWBURST;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWLOCK;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWCACHE;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWPROT;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWQOS;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWREGION;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWUSER;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WVALID;
wire   [31:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WDATA;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WSTRB;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WLAST;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WID;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WUSER;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARVALID;
wire   [63:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARADDR;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARID;
wire   [31:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARLEN;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARSIZE;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARBURST;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARLOCK;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARCACHE;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARPROT;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARQOS;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARREGION;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARUSER;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_RREADY;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_BREADY;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWVALID;
wire   [63:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWADDR;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWID;
wire   [31:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWLEN;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWSIZE;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWBURST;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWLOCK;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWCACHE;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWPROT;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWQOS;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWREGION;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWUSER;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WVALID;
wire   [31:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WDATA;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WSTRB;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WLAST;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WID;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WUSER;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARVALID;
wire   [63:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARADDR;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARID;
wire   [31:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARLEN;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARSIZE;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARBURST;
wire   [1:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARLOCK;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARCACHE;
wire   [2:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARPROT;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARQOS;
wire   [3:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARREGION;
wire   [0:0] grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARUSER;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_RREADY;
wire    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_BREADY;
reg    grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [63:0] sext_ln447_fu_163_p1;
wire  signed [63:0] sext_ln447_1_fu_177_p1;
wire   [31:0] zext_ln447_fu_173_p1;
reg    ap_block_state9;
wire   [31:0] zext_ln442_fu_159_p1;
wire   [0:0] icmp_ln447_fu_117_p2;
wire   [16:0] shl_ln_fu_133_p3;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start_reg = 1'b0;
end

dot_tree_8_2_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1 grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start),
    .ap_done(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_done),
    .ap_idle(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_idle),
    .ap_ready(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_ready),
    .v283_dout(v283_dout),
    .v283_num_data_valid(4'd0),
    .v283_fifo_cap(4'd0),
    .v283_empty_n(v283_empty_n),
    .v283_read(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_v283_read),
    .v284_dout(v284_dout),
    .v284_num_data_valid(4'd0),
    .v284_fifo_cap(4'd0),
    .v284_empty_n(v284_empty_n),
    .v284_read(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_v284_read),
    .m_axi_gmem4_AWVALID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWVALID),
    .m_axi_gmem4_AWREADY(m_axi_gmem4_AWREADY),
    .m_axi_gmem4_AWADDR(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWADDR),
    .m_axi_gmem4_AWID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWID),
    .m_axi_gmem4_AWLEN(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWLEN),
    .m_axi_gmem4_AWSIZE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWSIZE),
    .m_axi_gmem4_AWBURST(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWBURST),
    .m_axi_gmem4_AWLOCK(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWLOCK),
    .m_axi_gmem4_AWCACHE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWCACHE),
    .m_axi_gmem4_AWPROT(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWPROT),
    .m_axi_gmem4_AWQOS(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWQOS),
    .m_axi_gmem4_AWREGION(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWREGION),
    .m_axi_gmem4_AWUSER(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWUSER),
    .m_axi_gmem4_WVALID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WVALID),
    .m_axi_gmem4_WREADY(m_axi_gmem4_WREADY),
    .m_axi_gmem4_WDATA(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WDATA),
    .m_axi_gmem4_WSTRB(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WSTRB),
    .m_axi_gmem4_WLAST(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WLAST),
    .m_axi_gmem4_WID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WID),
    .m_axi_gmem4_WUSER(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WUSER),
    .m_axi_gmem4_ARVALID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARVALID),
    .m_axi_gmem4_ARREADY(1'b0),
    .m_axi_gmem4_ARADDR(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARADDR),
    .m_axi_gmem4_ARID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARID),
    .m_axi_gmem4_ARLEN(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARLEN),
    .m_axi_gmem4_ARSIZE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARSIZE),
    .m_axi_gmem4_ARBURST(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARBURST),
    .m_axi_gmem4_ARLOCK(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARLOCK),
    .m_axi_gmem4_ARCACHE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARCACHE),
    .m_axi_gmem4_ARPROT(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARPROT),
    .m_axi_gmem4_ARQOS(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARQOS),
    .m_axi_gmem4_ARREGION(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARREGION),
    .m_axi_gmem4_ARUSER(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_ARUSER),
    .m_axi_gmem4_RVALID(1'b0),
    .m_axi_gmem4_RREADY(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_RREADY),
    .m_axi_gmem4_RDATA(32'd0),
    .m_axi_gmem4_RLAST(1'b0),
    .m_axi_gmem4_RID(1'd0),
    .m_axi_gmem4_RFIFONUM(9'd0),
    .m_axi_gmem4_RUSER(1'd0),
    .m_axi_gmem4_RRESP(2'd0),
    .m_axi_gmem4_BVALID(m_axi_gmem4_BVALID),
    .m_axi_gmem4_BREADY(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_BREADY),
    .m_axi_gmem4_BRESP(m_axi_gmem4_BRESP),
    .m_axi_gmem4_BID(m_axi_gmem4_BID),
    .m_axi_gmem4_BUSER(m_axi_gmem4_BUSER),
    .empty(v255_reg_187),
    .m_axi_gmem3_AWVALID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(m_axi_gmem3_AWREADY),
    .m_axi_gmem3_AWADDR(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(m_axi_gmem3_WREADY),
    .m_axi_gmem3_WDATA(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(1'b0),
    .m_axi_gmem3_ARADDR(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(1'b0),
    .m_axi_gmem3_RREADY(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(32'd0),
    .m_axi_gmem3_RLAST(1'b0),
    .m_axi_gmem3_RID(1'd0),
    .m_axi_gmem3_RFIFONUM(9'd0),
    .m_axi_gmem3_RUSER(1'd0),
    .m_axi_gmem3_RRESP(2'd0),
    .m_axi_gmem3_BVALID(m_axi_gmem3_BVALID),
    .m_axi_gmem3_BREADY(grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(m_axi_gmem3_BRESP),
    .m_axi_gmem3_BID(m_axi_gmem3_BID),
    .m_axi_gmem3_BUSER(m_axi_gmem3_BUSER),
    .sext_ln447_1(trunc_ln447_1_reg_204),
    .sext_ln447(trunc_ln_reg_193)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_ready == 1'b1)) begin
            grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_199[16 : 1] <= empty_fu_141_p3[16 : 1];
        trunc_ln447_1_reg_204 <= {{v248_dout[63:2]}};
        trunc_ln_reg_193 <= {{v249_dout[63:2]}};
        v255_reg_187 <= v255_fu_113_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state9)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem3_blk_n_AW = m_axi_gmem3_AWREADY;
    end else begin
        gmem3_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmem3_blk_n_B = m_axi_gmem3_BVALID;
    end else begin
        gmem3_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem4_blk_n_AW = m_axi_gmem4_AWREADY;
    end else begin
        gmem4_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmem4_blk_n_B = m_axi_gmem4_BVALID;
    end else begin
        gmem4_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem3_AWADDR = sext_ln447_1_fu_177_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWADDR = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWADDR;
    end else begin
        m_axi_gmem3_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWBURST = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWBURST;
    end else begin
        m_axi_gmem3_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWCACHE = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWCACHE;
    end else begin
        m_axi_gmem3_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWID;
    end else begin
        m_axi_gmem3_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem3_AWLEN = zext_ln442_fu_159_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWLEN = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWLEN;
    end else begin
        m_axi_gmem3_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWLOCK = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWLOCK;
    end else begin
        m_axi_gmem3_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWPROT = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWPROT;
    end else begin
        m_axi_gmem3_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWQOS = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWQOS;
    end else begin
        m_axi_gmem3_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWREGION = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWREGION;
    end else begin
        m_axi_gmem3_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWSIZE = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWSIZE;
    end else begin
        m_axi_gmem3_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWUSER = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWUSER;
    end else begin
        m_axi_gmem3_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem3_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_AWVALID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_AWVALID;
    end else begin
        m_axi_gmem3_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem3_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_BREADY = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_BREADY;
    end else begin
        m_axi_gmem3_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem3_WVALID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WVALID;
    end else begin
        m_axi_gmem3_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_AWADDR = sext_ln447_fu_163_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWADDR = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWADDR;
    end else begin
        m_axi_gmem4_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWBURST = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWBURST;
    end else begin
        m_axi_gmem4_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWCACHE = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWCACHE;
    end else begin
        m_axi_gmem4_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWID;
    end else begin
        m_axi_gmem4_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_AWLEN = zext_ln447_fu_173_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWLEN = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWLEN;
    end else begin
        m_axi_gmem4_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWLOCK = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWLOCK;
    end else begin
        m_axi_gmem4_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWPROT = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWPROT;
    end else begin
        m_axi_gmem4_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWQOS = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWQOS;
    end else begin
        m_axi_gmem4_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWREGION = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWREGION;
    end else begin
        m_axi_gmem4_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWSIZE = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWSIZE;
    end else begin
        m_axi_gmem4_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWUSER = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWUSER;
    end else begin
        m_axi_gmem4_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem4_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_AWVALID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_AWVALID;
    end else begin
        m_axi_gmem4_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem4_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_BREADY = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_BREADY;
    end else begin
        m_axi_gmem4_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem4_WVALID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WVALID;
    end else begin
        m_axi_gmem4_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        v248_blk_n = v248_empty_n;
    end else begin
        v248_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v248_read = 1'b1;
    end else begin
        v248_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        v249_blk_n = v249_empty_n;
    end else begin
        v249_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v249_read = 1'b1;
    end else begin
        v249_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        v281_blk_n = v281_empty_n;
    end else begin
        v281_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v281_read = 1'b1;
    end else begin
        v281_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v283_read = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_v283_read;
    end else begin
        v283_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v284_read = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_v284_read;
    end else begin
        v284_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((v248_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (v281_empty_n == 1'b0) | (v249_empty_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem4_AWREADY == 1'b0) | (m_axi_gmem3_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state9 = ((m_axi_gmem3_BVALID == 1'b0) | (m_axi_gmem4_BVALID == 1'b0));
end

assign empty_fu_141_p3 = ((icmp_ln447_fu_117_p2[0:0] == 1'b1) ? shl_ln_fu_133_p3 : 17'd0);

assign grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_ap_start_reg;

assign icmp_ln447_fu_117_p2 = ((v255_fu_113_p1 != 16'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem3_ARADDR = 64'd0;

assign m_axi_gmem3_ARBURST = 2'd0;

assign m_axi_gmem3_ARCACHE = 4'd0;

assign m_axi_gmem3_ARID = 1'd0;

assign m_axi_gmem3_ARLEN = 32'd0;

assign m_axi_gmem3_ARLOCK = 2'd0;

assign m_axi_gmem3_ARPROT = 3'd0;

assign m_axi_gmem3_ARQOS = 4'd0;

assign m_axi_gmem3_ARREGION = 4'd0;

assign m_axi_gmem3_ARSIZE = 3'd0;

assign m_axi_gmem3_ARUSER = 1'd0;

assign m_axi_gmem3_ARVALID = 1'b0;

assign m_axi_gmem3_RREADY = 1'b0;

assign m_axi_gmem3_WDATA = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WDATA;

assign m_axi_gmem3_WID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WID;

assign m_axi_gmem3_WLAST = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WLAST;

assign m_axi_gmem3_WSTRB = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WSTRB;

assign m_axi_gmem3_WUSER = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem3_WUSER;

assign m_axi_gmem4_ARADDR = 64'd0;

assign m_axi_gmem4_ARBURST = 2'd0;

assign m_axi_gmem4_ARCACHE = 4'd0;

assign m_axi_gmem4_ARID = 1'd0;

assign m_axi_gmem4_ARLEN = 32'd0;

assign m_axi_gmem4_ARLOCK = 2'd0;

assign m_axi_gmem4_ARPROT = 3'd0;

assign m_axi_gmem4_ARQOS = 4'd0;

assign m_axi_gmem4_ARREGION = 4'd0;

assign m_axi_gmem4_ARSIZE = 3'd0;

assign m_axi_gmem4_ARUSER = 1'd0;

assign m_axi_gmem4_ARVALID = 1'b0;

assign m_axi_gmem4_RREADY = 1'b0;

assign m_axi_gmem4_WDATA = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WDATA;

assign m_axi_gmem4_WID = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WID;

assign m_axi_gmem4_WLAST = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WLAST;

assign m_axi_gmem4_WSTRB = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WSTRB;

assign m_axi_gmem4_WUSER = grp_dot_sink_0_1_Pipeline_VITIS_LOOP_447_1_fu_98_m_axi_gmem4_WUSER;

assign sext_ln447_1_fu_177_p1 = $signed(trunc_ln447_1_reg_204);

assign sext_ln447_fu_163_p1 = $signed(trunc_ln_reg_193);

assign shl_ln_fu_133_p3 = {{v255_fu_113_p1}, {1'd0}};

assign v255_fu_113_p1 = v281_dout[15:0];

assign zext_ln442_fu_159_p1 = v255_reg_187;

assign zext_ln447_fu_173_p1 = empty_reg_199;

always @ (posedge ap_clk) begin
    empty_reg_199[0] <= 1'b0;
end

endmodule //dot_tree_8_2_dot_sink_0_1
