name: commercial-batch-synthesis

inputs:
  - adk
  - macro-batch
  - srams

outputs:
  - synthesis-batch
  - synthesis-status.json

commands:
  - python batch_synthesis.py

parameters:
  clock_period: 10.0
  flatten_effort: 0
  topographical: True
  nthreads: 4
  high_effort_area_opt: False
  gate_clock: True
  uniquify_with_design_name: True
  suppress_msg: False
  suppressed_msg: ''
  write_svsim_wrapper: False

preconditions:
  - assert Tool( 'dc_shell-xg-t' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/macro-batch' )

postconditions:
  - assert File( 'outputs/synthesis-batch' )
  - assert File( 'outputs/synthesis-status.json' )
