// GENERATED by export_rtl.py -- a port-compatible EMPTY module.
// The logic-only synthesis run needs `tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_1010_1_spad_RAM_AUTO_1R1W` to link and to
// contribute zero area. Its ports terminate here instead of
// dangling, so the area figure keeps everything that DRIVES the
// memory -- address generation, enables, write masks -- and
// excludes the array and the array's own interface. Header
// copied verbatim from the real module; do not edit.
module tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_1010_1_spad_RAM_AUTO_1R1W (
     
    address0, ce0,
    d0, we0, 
    q0, 
     
    reset, clk);


parameter DataWidth = 64;
parameter AddressWidth = 9;
parameter AddressRange = 512;
 
input[AddressWidth-1:0] address0;
input ce0;
input[DataWidth-1:0] d0;
input we0; 
output reg[DataWidth-1:0] q0; 

input reset;
input clk;
endmodule
