#!/bin/bash
# AMC memory lowering of the D-12 declarations: run from this directory after sourcing ../env.sh.
# Writes <m>.sv (the emitted SystemVerilog, CIRCT comments stripped) and prints one line per file.
for m in iram loopbuf vmem vmem_split vmem_rw11 repro_rw_split_latency; do
  out=${TMPDIR:-/tmp}/$m.amc.out
  scl enable gcc-toolset-13 -- amctool --memory-only --emit-verilog $m.mlir > $out 2>&1; rc=$?
  if grep -q "Generated by CIRCT" $out; then
    sed -n '/Generated by CIRCT/,$p' $out | sed 's#\t*// within split.*##; s#\t*// .*mlir.*##' > $m.sv
    echo "LOWER $m rc=$rc -> $m.sv ($(grep -c . $m.sv) lines; ports: $(grep -oE 'p[0-9]_(rd_en|wr_en)' $m.sv | sort -u | tr '\n' ' '))  stderr: $(grep -m1 -o 'error: [a-zA-Z( ):_]*' $out)"
  else
    echo "REFUSE $m rc=$rc: $(grep -m1 -o 'error: [^%]*' $out)"
  fi
done
