# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""An OpenRAM macro as a Catapult memory library (Memory Generator, TCL spec).

    python memgen_spec.py <macro.v> <macro.lib> <outdir> [--clock 3.33] [--run]

Reads the OpenRAM behavioural model (module name, DATA_WIDTH, ADDR_WIDTH, the
RW/R/W ports as OpenRAM names them: clk<i>, csb<i>, web<i>, addr<i>, din<i>,
dout<i>) and the Liberty ``area`` (um^2, layout width x height), and writes

* ``<outdir>/<module>_memgen.tcl`` -- the ``/MemGen/MemoryGenerator_BuildLib``
  spec (``catapult_lb_useref.pdf`` ch. 1.2): one ReadWrite port per RW port,
  ``csb`` as an active-low PORT_ENABLE, ``web`` as an active-low WRITE_ENABLE,
  READLATENCY 1 / WRITELATENCY 1 / INITDELAY 1 (the model registers its inputs
  at posedge and reads or writes at negedge: data one cycle later, a write
  seen by the next cycle's read), RDWRRESOLUTION UNKNOWN (a port either reads
  or writes; a cross-port same-word access is the D-12 collision obligation),
  AREA the Liberty area rounded (the nangate-45nm_beh unit is um^2-like: its
  score for the D-12 regfile server was 3,877 against DC's 4,062 um^2), and
  READDELAY = clock/2 + the Liberty's largest dout cell_rise (the output moves
  after the FALLING edge).
* ``<outdir>/<module>_sim.v`` -- the model for Verilator: the ``#(T_HOLD)
  dout = 'bx`` line removed (Verilator ignores the delay, and the X would then
  race the consumer's posedge sample), the ``#(DELAY)`` on the negedge read
  removed (Verilator 5 refuses a timing control without ``--timing``;
  the data still moves at the falling edge), VERBOSE 0. Function otherwise
  identical.

With ``--run``: ``catapult -shell -f`` the spec; the library lands in
``<outdir>/memgen/<module>.lib`` and is used by
``solution library add <module> -file <that .lib>`` +
``directive set <array>:rsc -MAP_TO_MODULE <module>.<module>``.
"""
import argparse, os, re, subprocess, sys, time

ap = argparse.ArgumentParser()
ap.add_argument("verilog"); ap.add_argument("lib"); ap.add_argument("outdir")
ap.add_argument("--clock", type=float, default=3.33)
ap.add_argument("--run", action="store_true")
ap.add_argument("--readdelay", type=float, default=None, help="override READDELAY (ns); default clock/2 + the Liberty dout delay")
a = ap.parse_args()

v = open(a.verilog).read()
mod = re.search(r"^module\s+(\w+)\s*\(", v, re.M).group(1)
dw = int(re.search(r"parameter DATA_WIDTH = (\d+)", v).group(1))
aw = int(re.search(r"parameter ADDR_WIDTH = (\d+)", v).group(1))
ports = []  # (index, kind)
for m in re.finditer(r"// Port (\d+): (RW|R|W)\n", v):
    ports.append((int(m.group(1)), m.group(2)))
assert ports, "no `// Port i: RW|R|W` lines: not an OpenRAM model"
lib = open(a.lib).read()
area = float(re.search(r"^\s*area : ([\d.]+);", lib, re.M).group(1))
# the largest dout cell_rise/cell_fall value in the Liberty (ns)
dq = 0.0
for blk in re.finditer(r"pin\(dout\d+\[.*?\]\)\{(.*?)\n\s*\}\n\s*\}", lib, re.S):
    for tbl in re.finditer(r"cell_(?:rise|fall)\(CELL_TABLE\) \{(.*?)\}", blk.group(1), re.S):
        for num in re.findall(r"[\d.]+", tbl.group(1)):
            dq = max(dq, float(num))
readdelay = a.readdelay if a.readdelay is not None else round(a.clock / 2 + dq, 3)

os.makedirs(a.outdir, exist_ok=True)
sim_v = os.path.join(a.outdir, f"{mod}_sim.v")
sim = re.sub(r"\n\s*#\(T_HOLD\) dout\d+ = \d+'bx;", "", v)
sim = sim.replace("<= #(DELAY) ", "<= ")  # Verilator 5 refuses timing controls without --timing/--no-timing
sim = sim.replace("parameter VERBOSE = 1 ;", "parameter VERBOSE = 0 ;")
open(sim_v, "w").write(sim)

port_decls, pinmaps = [], []
for i, kind in ports:
    p = f"p{i}"
    mode = {"RW": "ReadWrite", "R": "Read", "W": "Write"}[kind]
    port_decls.append(f"  {{ NAME {p} MODE {mode} }}")
    pinmaps.append(f"  {{ PHYPIN clk{i}  LOGPIN CLOCK        DIRECTION in  WIDTH 1.0        PHASE 1  DEFAULT {{}} PORTS {p} }}")
    pinmaps.append(f"  {{ PHYPIN csb{i}  LOGPIN PORT_ENABLE  DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {{}} PORTS {p} }}")
    pinmaps.append(f"  {{ PHYPIN addr{i} LOGPIN ADDRESS      DIRECTION in  WIDTH ADDR_WIDTH PHASE {{}} DEFAULT {{}} PORTS {p} }}")
    if kind in ("RW", "W"):
        if kind == "RW":
            pinmaps.append(f"  {{ PHYPIN web{i}  LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {{}} PORTS {p} }}")
        pinmaps.append(f"  {{ PHYPIN din{i}  LOGPIN DATA_IN      DIRECTION in  WIDTH DATA_WIDTH PHASE {{}} DEFAULT {{}} PORTS {p} }}")
    if kind in ("RW", "R"):
        pinmaps.append(f"  {{ PHYPIN dout{i} LOGPIN DATA_OUT     DIRECTION out WIDTH DATA_WIDTH PHASE {{}} DEFAULT {{}} PORTS {p} }}")

memgen_dir = os.path.join(os.path.abspath(a.outdir), "memgen")
tcl = f"""# Generated by memgen_spec.py from {os.path.basename(a.verilog)} and {os.path.basename(a.lib)}
# (OpenRAM macro {mod}: {1 << aw} x {dw} b, ports {', '.join(k for _, k in ports)}; Liberty area {area:.1f} um^2)
flow package require MemGen
flow run /MemGen/MemoryGenerator_BuildLib {{
VENDOR           *
RTLTOOL          DesignCompiler
TECHNOLOGY       *
LIBRARY          {mod}
MODULE           {mod}
OUTPUT_DIR       {memgen_dir}
FILES {{
  {{ FILENAME {os.path.abspath(a.verilog)} FILETYPE Verilog MODELTYPE generic PARSE 1 PATHTYPE copy STATICFILE 1 }}
}}
VHDLARRAYPATH    {{}}
WRITEDELAY       0.1
INITDELAY        1
READDELAY        {readdelay}
VERILOGARRAYPATH mem
INPUTDELAY       0.01
TIMEUNIT         1ns
WIDTH            DATA_WIDTH
AREA             {int(round(area))}
RDWRRESOLUTION   UNKNOWN
WRITELATENCY     1
READLATENCY      1
DEPTH            {1 << aw}
PARAMETERS {{
  {{ PARAMETER DATA_WIDTH TYPE hdl IGNORE 0 MIN {dw} MAX {dw} DEFAULT {dw} }}
  {{ PARAMETER ADDR_WIDTH TYPE hdl IGNORE 0 MIN {aw} MAX {aw} DEFAULT {aw} }}
  {{ PARAMETER RAM_DEPTH  TYPE hdl IGNORE 1 MIN {{}} MAX {{}} DEFAULT {1 << aw} }}
  {{ PARAMETER DELAY      TYPE hdl IGNORE 1 MIN {{}} MAX {{}} DEFAULT 3 }}
  {{ PARAMETER VERBOSE    TYPE hdl IGNORE 1 MIN {{}} MAX {{}} DEFAULT 1 }}
  {{ PARAMETER T_HOLD     TYPE hdl IGNORE 1 MIN {{}} MAX {{}} DEFAULT 1 }}
}}
PORTS {{
{chr(10).join(port_decls)}
}}
PINMAPS {{
{chr(10).join(pinmaps)}
}}
}}
"""
spec = os.path.join(a.outdir, f"{mod}_memgen.tcl")
open(spec, "w").write(tcl)
print(f"MEMGEN {mod}: {1 << aw} x {dw}, ports {[k for _, k in ports]}, area {area:.1f} um^2, "
      f"dout delay {dq:.3f} ns -> READDELAY {readdelay}; spec {spec}; sim model {sim_v}")
if a.run:
    t0 = time.time()
    r = subprocess.run(f"catapult -shell -f {os.path.basename(spec)} > memgen.log 2>&1", shell=True, cwd=a.outdir)
    out_lib = os.path.join(memgen_dir, f"{mod}.lib")
    print(f"CATAPULT memgen: exit {r.returncode}, {time.time() - t0:.0f}s, "
          f"{'OK ' + out_lib if os.path.exists(out_lib) else 'NO LIB (see memgen.log)'}")
    sys.exit(0 if os.path.exists(out_lib) else 1)
