# Generated by gen_wire.py from examples.minitpu.units.acc24_add_pipe.native (variant 'native'); do not edit.
import allo.dataflow as df
from allo.ir.types import *  # noqa: F401,F403
from examples.minitpu.units.acc24_add_pipe import *  # noqa: F401,F403
from examples.minitpu.units import acc24_add_pipe as _u
for _k in dir(_u):
    if _k.startswith('_') and not _k.startswith('__'):
        globals()[_k] = getattr(_u, _k)


def wire(n):
    @df.region()
    def top(AV_: uint32[n], BV_: uint32[n], CV_: uint32[n]):
        wa: Wire[uint32]
        wb: Wire[uint32]
        wc: Wire[uint32]

        @df.kernel(mapping=[1], args=[AV_, BV_])
        def src(av: uint32[n], bv: uint32[n]):
            for i in range(n):
                wa.put(av[i])
                wb.put(bv[i])

        @df.kernel(mapping=[1], args=[])
        def add():
            for _ in range(n):
                av_w: uint32 = wa.get()
                bv_w: uint32 = wb.get()
                ua: uint32 = av_w << 8
                ub: uint32 = bv_w << 8
                fa: float32 = ua.bitcast()
                fb: float32 = ub.bitcast()
                s: float32 = fa + fb
                u: uint32 = s.bitcast()
                lsb: uint32 = (u >> 8) & 1
                r: uint32 = u + 127 + lsb
                wc.put(r >> 8)


        @df.kernel(mapping=[1], args=[CV_])
        def sink(cv: uint32[n]):
            for i in range(n):
                cv[i] = wc.get()

    return top
