# Generated by gen_wire.py from examples.minitpu.units.mul_acc24.native (variant 'native'); do not edit.
import allo.dataflow as df
from allo.ir.types import *  # noqa: F401,F403
from examples.minitpu.units.mul_acc24 import *  # noqa: F401,F403
from examples.minitpu.units import mul_acc24 as _u
for _k in dir(_u):
    if _k.startswith('_') and not _k.startswith('__'):
        globals()[_k] = getattr(_u, _k)


def wire(n):
    """No acc24 type: a float32 product, rounded RNE to 15 fraction bits by
    integer arithmetic on its bit pattern (as ``microarch.py`` and
    ``tests/dataflow/test_bf16_dataflow.py::test_acc24_emulation_via_bitcast``
    do), returned as the 24-bit pattern in a ``uint32``. A **workaround** for a
    missing abstraction (no custom float format); the rounding is a no-op
    unless the float32 product is itself subnormal."""

    @df.region()
    def top(A_: bfloat16[n], B_: bfloat16[n], C_: uint32[n]):
        wa: Wire[bfloat16]
        wb: Wire[bfloat16]
        wc: Wire[uint32]

        @df.kernel(mapping=[1], args=[A_, B_])
        def src(a: bfloat16[n], b: bfloat16[n]):
            for i in range(n):
                wa.put(a[i])
                wb.put(b[i])

        @df.kernel(mapping=[1], args=[])
        def mul():
            for _ in range(n):
                a_w: bfloat16 = wa.get()
                b_w: bfloat16 = wb.get()
                av: float32 = a_w
                bv: float32 = b_w
                prod: float32 = av * bv
                u: uint32 = prod.bitcast()
                lsb: uint32 = (u >> 8) & 1
                r: uint32 = u + 127 + lsb
                wc.put(r >> 8)


        @df.kernel(mapping=[1], args=[C_])
        def sink(c: uint32[n]):
            for i in range(n):
                c[i] = wc.get()

    return top
