# GENERATED by examples/minitpu/fpga/vhls_build.py -- the flow's own run.tcl (Allo's kernel.cpp verbatim)
open_project out.prj -reset
open_solution -reset solution1 -flow_target vivado
set_top mxu_widev_dim2
add_files kernel.cpp
set_part {xczu7ev-ffvc1156-2-e}
create_clock -period 5.0
set_directive_interface -mode ap_ctrl_none "mxu_widev_dim2"
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2973
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2974
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2975
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2976
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2977
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2978
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2979
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2980
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2981
set_directive_interface -mode ap_fifo "mxu_widev_dim2" v2982
set_directive_array_partition -type complete -dim 0 mxu_back_w_0 mem
set_directive_array_partition -type complete -dim 0 mxu_front_w_0 skd
set_directive_array_partition -type complete -dim 0 mxu_front_w_0 skv
set_directive_array_partition -type complete -dim 0 mxu_front_w_0 cbs
set_directive_array_partition -type complete -dim 0 mxu_front_w_0 wss
set_directive_array_partition -type complete -dim 0 mxu_front_w_0 hdata
set_directive_array_partition -type complete -dim 0 mxu_back_w_0 gidx
set_directive_array_partition -type complete -dim 0 mxu_back_w_0 gq
set_directive_array_partition -type complete -dim 0 mxu_back_w_0 rd
set_directive_array_partition -type complete -dim 0 mxu_back_w_0 wr
set_directive_array_partition -type complete -dim 0 mxu_back_w_0 cnt
set_directive_stream -depth 3 mxu_widev_dim2 v2983  ;# mxu_front_w_0@2 -> pe_unit_0_0@2, holds 1
set_directive_stream -depth 3 mxu_widev_dim2 v2984  ;# pe_unit_0_0@7 -> pe_unit_0_1@2, holds 1
set_directive_stream -depth 9 mxu_widev_dim2 v2986  ;# mxu_front_w_0@2 -> pe_unit_1_0@2, holds 7
set_directive_stream -depth 3 mxu_widev_dim2 v2987  ;# pe_unit_1_0@9 -> pe_unit_1_1@2, holds 1
set_directive_stream -depth 3 mxu_widev_dim2 v2989  ;# mxu_front_w_0@2 -> pe_unit_0_0@2, holds 1
set_directive_stream -depth 9 mxu_widev_dim2 v2990  ;# mxu_front_w_0@2 -> pe_unit_0_1@2, holds 7
set_directive_stream -depth 3 mxu_widev_dim2 v2991  ;# pe_unit_0_0@7 -> pe_unit_1_0@2, holds 1
set_directive_stream -depth 5 mxu_widev_dim2 v2992  ;# pe_unit_0_1@7 -> pe_unit_1_1@2, holds 3
set_directive_stream -depth 3 mxu_widev_dim2 v2997  ;# pe_unit_0_0@7 -> pe_unit_1_0@2, holds 1
set_directive_stream -depth 5 mxu_widev_dim2 v2998  ;# pe_unit_0_1@7 -> pe_unit_1_1@2, holds 3
set_directive_stream -depth 11 mxu_widev_dim2 v2999  ;# pe_unit_1_0@9 -> mxu_back_w_0@2, holds 9
set_directive_stream -depth 3 mxu_widev_dim2 v3000  ;# pe_unit_1_1@9 -> mxu_back_w_0@2, holds 1
set_directive_stream -depth 25 mxu_widev_dim2 v3001  ;# mxu_front_w_0@2 -> mxu_back_w_0@2, holds 23
csynth_design

exit
