// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_pe_3_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        v2262_dout,
        v2262_num_data_valid,
        v2262_fifo_cap,
        v2262_empty_n,
        v2262_read,
        v2213_dout,
        v2213_num_data_valid,
        v2213_fifo_cap,
        v2213_empty_n,
        v2213_read,
        v2238_dout,
        v2238_num_data_valid,
        v2238_fifo_cap,
        v2238_empty_n,
        v2238_read,
        v2246_din,
        v2246_num_data_valid,
        v2246_fifo_cap,
        v2246_full_n,
        v2246_write,
        v2226_din,
        v2226_num_data_valid,
        v2226_fifo_cap,
        v2226_full_n,
        v2226_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] v2262_dout;
input  [2:0] v2262_num_data_valid;
input  [2:0] v2262_fifo_cap;
input   v2262_empty_n;
output   v2262_read;
input  [31:0] v2213_dout;
input  [3:0] v2213_num_data_valid;
input  [3:0] v2213_fifo_cap;
input   v2213_empty_n;
output   v2213_read;
input  [31:0] v2238_dout;
input  [3:0] v2238_num_data_valid;
input  [3:0] v2238_fifo_cap;
input   v2238_empty_n;
output   v2238_read;
output  [127:0] v2246_din;
input  [3:0] v2246_num_data_valid;
input  [3:0] v2246_fifo_cap;
input   v2246_full_n;
output   v2246_write;
output  [7:0] v2226_din;
input  [3:0] v2226_num_data_valid;
input  [3:0] v2226_fifo_cap;
input   v2226_full_n;
output   v2226_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg v2262_read;
reg v2213_read;
reg v2238_read;
reg v2246_write;
reg v2226_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    v2262_blk_n;
wire   [15:0] trunc_ln3384_fu_47_p1;
reg   [15:0] trunc_ln3384_reg_51;
reg    ap_block_state1;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_idle;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_ready;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2262_read;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2213_read;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2238_read;
wire   [127:0] grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2246_din;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2246_write;
wire   [7:0] grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2226_din;
wire    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2226_write;
reg    grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start_reg = 1'b0;
end

tinytpu_isa_pe_3_0_Pipeline_VITIS_LOOP_3396_1 grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start),
    .ap_done(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done),
    .ap_idle(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_idle),
    .ap_ready(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_ready),
    .v2262_dout(v2262_dout),
    .v2262_num_data_valid(3'd0),
    .v2262_fifo_cap(3'd0),
    .v2262_empty_n(v2262_empty_n),
    .v2262_read(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2262_read),
    .v2213_dout(v2213_dout),
    .v2213_num_data_valid(4'd0),
    .v2213_fifo_cap(4'd0),
    .v2213_empty_n(v2213_empty_n),
    .v2213_read(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2213_read),
    .v2238_dout(v2238_dout),
    .v2238_num_data_valid(4'd0),
    .v2238_fifo_cap(4'd0),
    .v2238_empty_n(v2238_empty_n),
    .v2238_read(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2238_read),
    .v2246_din(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2246_din),
    .v2246_num_data_valid(4'd0),
    .v2246_fifo_cap(4'd0),
    .v2246_full_n(v2246_full_n),
    .v2246_write(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2246_write),
    .v2226_din(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2226_din),
    .v2226_num_data_valid(4'd0),
    .v2226_fifo_cap(4'd0),
    .v2226_full_n(v2226_full_n),
    .v2226_write(grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2226_write),
    .empty(trunc_ln3384_reg_51)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_ready == 1'b1)) begin
            grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln3384_reg_51 <= trunc_ln3384_fu_47_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2213_read = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2213_read;
    end else begin
        v2213_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2226_write = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2226_write;
    end else begin
        v2226_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2238_read = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2238_read;
    end else begin
        v2238_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v2246_write = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2246_write;
    end else begin
        v2246_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        v2262_blk_n = v2262_empty_n;
    end else begin
        v2262_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v2262_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v2262_read = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2262_read;
    end else begin
        v2262_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (v2262_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_ap_start_reg;

assign trunc_ln3384_fu_47_p1 = v2262_dout[15:0];

assign v2226_din = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2226_din;

assign v2246_din = grp_pe_3_0_Pipeline_VITIS_LOOP_3396_1_fu_32_v2246_din;

endmodule //tinytpu_isa_pe_3_0
