// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_dma_st_0_1_Pipeline_VITIS_LOOP_4406_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v2185_dout,
        v2185_num_data_valid,
        v2185_fifo_cap,
        v2185_empty_n,
        v2185_read,
        v2189_dout,
        v2189_num_data_valid,
        v2189_fifo_cap,
        v2189_empty_n,
        v2189_read,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        empty,
        v2075_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] v2185_dout;
input  [3:0] v2185_num_data_valid;
input  [3:0] v2185_fifo_cap;
input   v2185_empty_n;
output   v2185_read;
input  [31:0] v2189_dout;
input  [3:0] v2189_num_data_valid;
input  [3:0] v2189_fifo_cap;
input   v2189_empty_n;
output   v2189_read;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [31:0] m_axi_gmem3_WDATA;
output  [3:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [31:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [15:0] empty;
input  [63:0] v2075_1;

reg ap_idle;
reg v2185_read;
reg v2189_read;
reg m_axi_gmem3_AWVALID;
reg m_axi_gmem3_WVALID;
reg m_axi_gmem3_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg   [0:0] v2091_reg_402;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln4406_fu_180_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v2189_blk_n;
wire    ap_block_pp0_stage0;
reg    gmem3_blk_n_AW;
reg    gmem3_blk_n_W;
reg    gmem3_blk_n_B;
reg    v2185_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] v2091_fu_203_p2;
wire   [25:0] trunc_ln4463_1_fu_284_p1;
reg   [25:0] trunc_ln4463_1_reg_406;
wire   [31:0] add_ln4463_1_fu_317_p2;
reg   [31:0] add_ln4463_1_reg_411;
reg   [63:0] gmem3_addr_reg_416;
reg   [31:0] v2102_reg_422;
wire  signed [63:0] sext_ln4406_fu_341_p1;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] v2085_fu_92;
wire   [31:0] v2088_fu_197_p2;
wire    ap_loop_init;
reg   [15:0] v2084_fu_96;
wire   [15:0] v2084_2_fu_185_p2;
reg   [31:0] f14_fu_100;
wire   [31:0] zext_ln4423_fu_234_p1;
reg   [31:0] f23_fu_104;
wire   [31:0] zext_ln4429_fu_248_p1;
reg   [31:0] v2090_fu_108;
wire   [31:0] zext_ln4435_fu_262_p1;
reg   [31:0] ap_sig_allocacmp_v2090_load;
wire   [11:0] v2094_fu_224_p4;
wire   [11:0] v2097_fu_238_p4;
wire   [7:0] v2100_fu_252_p4;
wire   [25:0] trunc_ln4463_fu_294_p1;
wire   [25:0] add_ln4463_fu_298_p2;
wire   [31:0] shl_ln_fu_303_p3;
wire   [31:0] shl_ln4463_fu_311_p2;
wire  signed [63:0] sext_ln4463_fu_323_p1;
wire   [63:0] add_ln4463_2_fu_326_p2;
wire   [61:0] trunc_ln5_fu_331_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_435;
reg    ap_condition_439;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 v2085_fu_92 = 32'd0;
#0 v2084_fu_96 = 16'd0;
#0 f14_fu_100 = 32'd0;
#0 f23_fu_104 = 32'd0;
#0 v2090_fu_108 = 32'd0;
#0 ap_done_reg = 1'b0;
end

tinytpu_isa_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f14_fu_100[0] <= 1'b0;
            f14_fu_100[1] <= 1'b0;
            f14_fu_100[2] <= 1'b0;
            f14_fu_100[3] <= 1'b0;
            f14_fu_100[4] <= 1'b0;
            f14_fu_100[5] <= 1'b0;
            f14_fu_100[6] <= 1'b0;
            f14_fu_100[7] <= 1'b0;
            f14_fu_100[8] <= 1'b0;
            f14_fu_100[9] <= 1'b0;
            f14_fu_100[10] <= 1'b0;
            f14_fu_100[11] <= 1'b0;
        end else if (((v2091_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        f14_fu_100[11 : 0] <= zext_ln4423_fu_234_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        f23_fu_104[0] <= 1'b0;
            f23_fu_104[1] <= 1'b0;
            f23_fu_104[2] <= 1'b0;
            f23_fu_104[3] <= 1'b0;
            f23_fu_104[4] <= 1'b0;
            f23_fu_104[5] <= 1'b0;
            f23_fu_104[6] <= 1'b0;
            f23_fu_104[7] <= 1'b0;
            f23_fu_104[8] <= 1'b0;
            f23_fu_104[9] <= 1'b0;
            f23_fu_104[10] <= 1'b0;
            f23_fu_104[11] <= 1'b0;
        end else if (((v2091_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        f23_fu_104[11 : 0] <= zext_ln4429_fu_248_p1[11 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v2084_fu_96 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln4406_fu_180_p2 == 1'd0))) begin
            v2084_fu_96 <= v2084_2_fu_185_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            v2085_fu_92 <= 32'd4294967295;
        end else if ((1'b1 == ap_condition_439)) begin
            v2085_fu_92 <= v2088_fu_197_p2;
        end else if ((1'b1 == ap_condition_435)) begin
            v2085_fu_92 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                        v2090_fu_108[0] <= 1'b0;
            v2090_fu_108[1] <= 1'b0;
            v2090_fu_108[2] <= 1'b0;
            v2090_fu_108[3] <= 1'b0;
            v2090_fu_108[4] <= 1'b0;
            v2090_fu_108[5] <= 1'b0;
            v2090_fu_108[6] <= 1'b0;
            v2090_fu_108[7] <= 1'b0;
        end else if (((v2091_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                        v2090_fu_108[7 : 0] <= zext_ln4435_fu_262_p1[7 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln4463_1_reg_411[31 : 2] <= add_ln4463_1_fu_317_p2[31 : 2];
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem3_addr_reg_416 <= sext_ln4406_fu_341_p1;
        trunc_ln4463_1_reg_406 <= trunc_ln4463_1_fu_284_p1;
        v2102_reg_422 <= v2189_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        v2091_reg_402 <= v2091_fu_203_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln4406_fu_180_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((v2091_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_v2090_load = zext_ln4435_fu_262_p1;
    end else begin
        ap_sig_allocacmp_v2090_load = v2090_fu_108;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_AW = m_axi_gmem3_AWREADY;
    end else begin
        gmem3_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_B = m_axi_gmem3_BVALID;
    end else begin
        gmem3_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_W = m_axi_gmem3_WREADY;
    end else begin
        gmem3_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_AWVALID = 1'b1;
    end else begin
        m_axi_gmem3_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_BREADY = 1'b1;
    end else begin
        m_axi_gmem3_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_WVALID = 1'b1;
    end else begin
        m_axi_gmem3_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((v2091_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v2185_blk_n = v2185_empty_n;
    end else begin
        v2185_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((v2091_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v2185_read = 1'b1;
    end else begin
        v2185_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        v2189_blk_n = v2189_empty_n;
    end else begin
        v2189_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        v2189_read = 1'b1;
    end else begin
        v2189_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln4463_1_fu_317_p2 = (shl_ln_fu_303_p3 + shl_ln4463_fu_311_p2);

assign add_ln4463_2_fu_326_p2 = ($signed(v2075_1) + $signed(sext_ln4463_fu_323_p1));

assign add_ln4463_fu_298_p2 = (trunc_ln4463_1_reg_406 + trunc_ln4463_fu_294_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem3_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axi_gmem3_AWREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter5))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem3_WREADY == 1'b0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axi_gmem3_AWREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter5))));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = (m_axi_gmem3_BVALID == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((v2091_reg_402 == 1'd0) & (v2185_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = (v2189_empty_n == 1'b0);
end

always @ (*) begin
    ap_condition_435 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v2091_fu_203_p2 == 1'd0) & (icmp_ln4406_fu_180_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_439 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (v2091_fu_203_p2 == 1'd1) & (icmp_ln4406_fu_180_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln4406_fu_180_p2 = ((v2084_fu_96 == empty) ? 1'b1 : 1'b0);

assign m_axi_gmem3_ARADDR = 64'd0;

assign m_axi_gmem3_ARBURST = 2'd0;

assign m_axi_gmem3_ARCACHE = 4'd0;

assign m_axi_gmem3_ARID = 1'd0;

assign m_axi_gmem3_ARLEN = 32'd0;

assign m_axi_gmem3_ARLOCK = 2'd0;

assign m_axi_gmem3_ARPROT = 3'd0;

assign m_axi_gmem3_ARQOS = 4'd0;

assign m_axi_gmem3_ARREGION = 4'd0;

assign m_axi_gmem3_ARSIZE = 3'd0;

assign m_axi_gmem3_ARUSER = 1'd0;

assign m_axi_gmem3_ARVALID = 1'b0;

assign m_axi_gmem3_AWADDR = gmem3_addr_reg_416;

assign m_axi_gmem3_AWBURST = 2'd0;

assign m_axi_gmem3_AWCACHE = 4'd0;

assign m_axi_gmem3_AWID = 1'd0;

assign m_axi_gmem3_AWLEN = 32'd1;

assign m_axi_gmem3_AWLOCK = 2'd0;

assign m_axi_gmem3_AWPROT = 3'd0;

assign m_axi_gmem3_AWQOS = 4'd0;

assign m_axi_gmem3_AWREGION = 4'd0;

assign m_axi_gmem3_AWSIZE = 3'd0;

assign m_axi_gmem3_AWUSER = 1'd0;

assign m_axi_gmem3_RREADY = 1'b0;

assign m_axi_gmem3_WDATA = v2102_reg_422;

assign m_axi_gmem3_WID = 1'd0;

assign m_axi_gmem3_WLAST = 1'b0;

assign m_axi_gmem3_WSTRB = 4'd15;

assign m_axi_gmem3_WUSER = 1'd0;

assign sext_ln4406_fu_341_p1 = $signed(trunc_ln5_fu_331_p4);

assign sext_ln4463_fu_323_p1 = $signed(add_ln4463_1_reg_411);

assign shl_ln4463_fu_311_p2 = f23_fu_104 << 32'd2;

assign shl_ln_fu_303_p3 = {{add_ln4463_fu_298_p2}, {6'd0}};

assign trunc_ln4463_1_fu_284_p1 = v2085_fu_92[25:0];

assign trunc_ln4463_fu_294_p1 = f14_fu_100[25:0];

assign trunc_ln5_fu_331_p4 = {{add_ln4463_2_fu_326_p2[63:2]}};

assign v2084_2_fu_185_p2 = (v2084_fu_96 + 16'd1);

assign v2088_fu_197_p2 = (v2085_fu_92 + 32'd1);

assign v2091_fu_203_p2 = (($signed(v2088_fu_197_p2) < $signed(ap_sig_allocacmp_v2090_load)) ? 1'b1 : 1'b0);

assign v2094_fu_224_p4 = {{v2185_dout[29:18]}};

assign v2097_fu_238_p4 = {{v2185_dout[41:30]}};

assign v2100_fu_252_p4 = {{v2185_dout[61:54]}};

assign zext_ln4423_fu_234_p1 = v2094_fu_224_p4;

assign zext_ln4429_fu_248_p1 = v2097_fu_238_p4;

assign zext_ln4435_fu_262_p1 = v2100_fu_252_p4;

always @ (posedge ap_clk) begin
    add_ln4463_1_reg_411[1:0] <= 2'b00;
    f14_fu_100[31:12] <= 20'b00000000000000000000;
    f23_fu_104[31:12] <= 20'b00000000000000000000;
    v2090_fu_108[31:8] <= 24'b000000000000000000000000;
end

endmodule //tinytpu_isa_dma_st_0_1_Pipeline_VITIS_LOOP_4406_1
