// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_wld_3_0 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        v3075_dout,
        v3075_num_data_valid,
        v3075_fifo_cap,
        v3075_empty_n,
        v3075_read,
        v3088_din,
        v3088_num_data_valid,
        v3088_fifo_cap,
        v3088_full_n,
        v3088_write,
        v3144_din,
        v3144_num_data_valid,
        v3144_fifo_cap,
        v3144_full_n,
        v3144_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] v3075_dout;
input  [3:0] v3075_num_data_valid;
input  [3:0] v3075_fifo_cap;
input   v3075_empty_n;
output   v3075_read;
output  [31:0] v3088_din;
input  [3:0] v3088_num_data_valid;
input  [3:0] v3088_fifo_cap;
input   v3088_full_n;
output   v3088_write;
output  [31:0] v3144_din;
input  [2:0] v3144_num_data_valid;
input  [2:0] v3144_fifo_cap;
input   v3144_full_n;
output   v3144_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg v3075_read;
reg[31:0] v3088_din;
reg v3088_write;
reg[31:0] v3144_din;
reg v3144_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    v3075_blk_n;
reg    v3088_blk_n;
reg    v3144_blk_n;
wire   [15:0] trunc_ln3750_fu_62_p1;
reg   [15:0] trunc_ln3750_reg_81;
reg    ap_block_state1;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_idle;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_ready;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3075_read;
wire   [31:0] grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_din;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_write;
wire   [31:0] grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_din;
wire    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_write;
reg    grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [31:0] zext_ln3763_fu_76_p1;
wire   [15:0] v1867_tmp_fu_66_p4;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start_reg = 1'b0;
end

tinytpu_isa_wld_3_0_Pipeline_VITIS_LOOP_3770_1 grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start),
    .ap_done(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done),
    .ap_idle(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_idle),
    .ap_ready(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_ready),
    .v3075_dout(v3075_dout),
    .v3075_num_data_valid(4'd0),
    .v3075_fifo_cap(4'd0),
    .v3075_empty_n(v3075_empty_n),
    .v3075_read(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3075_read),
    .v3088_din(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_din),
    .v3088_num_data_valid(4'd0),
    .v3088_fifo_cap(4'd0),
    .v3088_full_n(v3088_full_n),
    .v3088_write(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_write),
    .v3144_din(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_din),
    .v3144_num_data_valid(3'd0),
    .v3144_fifo_cap(3'd0),
    .v3144_full_n(v3144_full_n),
    .v3144_write(grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_write),
    .empty(trunc_ln3750_reg_81)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start_reg <= 1'b1;
        end else if ((grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_ready == 1'b1)) begin
            grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln3750_reg_81 <= trunc_ln3750_fu_62_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        v3075_blk_n = v3075_empty_n;
    end else begin
        v3075_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v3075_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v3075_read = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3075_read;
    end else begin
        v3075_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        v3088_blk_n = v3088_full_n;
    end else begin
        v3088_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v3088_din = v3075_dout;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v3088_din = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_din;
    end else begin
        v3088_din = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v3088_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v3088_write = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3088_write;
    end else begin
        v3088_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        v3144_blk_n = v3144_full_n;
    end else begin
        v3144_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v3144_din = zext_ln3763_fu_76_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v3144_din = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_din;
    end else begin
        v3144_din = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v3144_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        v3144_write = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_v3144_write;
    end else begin
        v3144_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (v3144_full_n == 1'b0) | (v3088_full_n == 1'b0) | (v3075_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start = grp_wld_3_0_Pipeline_VITIS_LOOP_3770_1_fu_51_ap_start_reg;

assign start_out = real_start;

assign trunc_ln3750_fu_62_p1 = v3075_dout[15:0];

assign v1867_tmp_fu_66_p4 = {{v3075_dout[31:16]}};

assign zext_ln3763_fu_76_p1 = v1867_tmp_fu_66_p4;

endmodule //tinytpu_isa_wld_3_0
