// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module tinytpu_isa_spm_0 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        v3064_dout,
        v3064_num_data_valid,
        v3064_fifo_cap,
        v3064_empty_n,
        v3064_read,
        v3072_din,
        v3072_num_data_valid,
        v3072_fifo_cap,
        v3072_full_n,
        v3072_write,
        v3068_dout,
        v3068_num_data_valid,
        v3068_fifo_cap,
        v3068_empty_n,
        v3068_read,
        v3070_din,
        v3070_num_data_valid,
        v3070_fifo_cap,
        v3070_full_n,
        v3070_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] v3064_dout;
input  [3:0] v3064_num_data_valid;
input  [3:0] v3064_fifo_cap;
input   v3064_empty_n;
output   v3064_read;
output  [31:0] v3072_din;
input  [3:0] v3072_num_data_valid;
input  [3:0] v3072_fifo_cap;
input   v3072_full_n;
output   v3072_write;
input  [31:0] v3068_dout;
input  [3:0] v3068_num_data_valid;
input  [3:0] v3068_fifo_cap;
input   v3068_empty_n;
output   v3068_read;
output  [31:0] v3070_din;
input  [3:0] v3070_num_data_valid;
input  [3:0] v3070_fifo_cap;
input   v3070_full_n;
output   v3070_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg v3064_read;
reg[31:0] v3072_din;
reg v3072_write;
reg v3068_read;
reg v3070_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    v3064_blk_n;
wire    ap_CS_fsm_state2;
reg    v3072_blk_n;
wire   [15:0] v1369_fu_52_p1;
reg   [15:0] v1369_reg_61;
reg    ap_block_state1;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_idle;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_ready;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3064_read;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3068_read;
wire   [31:0] grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3070_din;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3070_write;
wire   [31:0] grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_din;
wire    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_write;
reg    grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_block_state2;
wire   [31:0] v1373_fu_56_p1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start_reg = 1'b0;
end

tinytpu_isa_spm_0_Pipeline_VITIS_LOOP_2606_1 grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start),
    .ap_done(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done),
    .ap_idle(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_idle),
    .ap_ready(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_ready),
    .v3064_dout(v3064_dout),
    .v3064_num_data_valid(4'd0),
    .v3064_fifo_cap(4'd0),
    .v3064_empty_n(v3064_empty_n),
    .v3064_read(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3064_read),
    .v3068_dout(v3068_dout),
    .v3068_num_data_valid(4'd0),
    .v3068_fifo_cap(4'd0),
    .v3068_empty_n(v3068_empty_n),
    .v3068_read(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3068_read),
    .v3070_din(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3070_din),
    .v3070_num_data_valid(4'd0),
    .v3070_fifo_cap(4'd0),
    .v3070_full_n(v3070_full_n),
    .v3070_write(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3070_write),
    .v3072_din(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_din),
    .v3072_num_data_valid(4'd0),
    .v3072_fifo_cap(4'd0),
    .v3072_full_n(v3072_full_n),
    .v3072_write(grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_write),
    .empty(v1369_reg_61)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_NS_fsm_state3))) begin
            grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start_reg <= 1'b1;
        end else if ((grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_ready == 1'b1)) begin
            grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        v1369_reg_61 <= v1369_fu_52_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        v3064_blk_n = v3064_empty_n;
    end else begin
        v3064_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)))) begin
        v3064_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v3064_read = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3064_read;
    end else begin
        v3064_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v3068_read = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3068_read;
    end else begin
        v3068_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v3070_write = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3070_write;
    end else begin
        v3070_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        v3072_blk_n = v3072_full_n;
    end else begin
        v3072_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        v3072_din = v1373_fu_56_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v3072_din = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_din;
    end else begin
        v3072_din = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_din;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        v3072_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v3072_write = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3072_write;
    end else begin
        v3072_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((v3064_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((v3072_full_n == 1'b0) | (v3064_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_ap_start_reg;

assign start_out = real_start;

assign v1369_fu_52_p1 = v3064_dout[15:0];

assign v1373_fu_56_p1 = v3064_dout[31:0];

assign v3070_din = grp_spm_0_Pipeline_VITIS_LOOP_2606_1_fu_39_v3070_din;

endmodule //tinytpu_isa_spm_0
